### ISSUE TITLE
Can Blink remember the passwords for SSH keys?

### ISSUE THREAD

**Issue by davidcelis** [blinksh/blink#339] opened 2017-08-15 01:39 UTC
My SSH key is password protected, but on machines I trust, I allow whatever credential helper is running to remember the SSH key's password so that I don't have to enter it every time I want to use it.

Would it be possible to add functionality to Blink so that passwords for SSH keys can be remembered?

**Comment by carloscabanero** [comment] 2017-10-03 16:28
Duplicate of #204. We are hiring someone to start rebumping our ssh code, so hopefully will see soon!

**Closed** 2017-10-03 16:28 UTC

**Comment by davidcelis** [comment] 2017-10-03 16:31
@carloscabanero Is this really a dupe of #204? This didn't feel like a fowarding thing to me, but I could be wrong. What I'm looking for is for this interaction to not happen:

```
blink> mosh example.com
Password:
```

I want to be able to save an SSH key's password along with the key itself so that I don't have to type its password each time I use it from the top-level Blink shell.

**Comment by carloscabanero** [comment] 2017-10-03 17:14
You are right, not the same. If you configure the server, you can save the Password there securely, and it will be remembered on any session. Would that work for you?

Otherwise this would be close to #81, which is creating an agent. Let me know!

**Comment by davidcelis** [comment] 2017-10-03 18:38
@carloscabanero Yeah it does look like #81 is asking for the same thing I am. Thanks!!
