### ISSUE TITLE
Arrow buttons doesn't work in mc

### ISSUE THREAD

**Issue by sergeilem** [blinksh/blink#153] opened 2016-10-20 13:06 UTC
Arrows is fully unusable in midnight commander.

**Comment by carloscabanero** [comment] 2016-10-24 02:11
Thanks for the report!! Might be a dupe of #146. Can you confirm this only happens in the on-screen keyboard? Thanks!

**Comment by carloscabanero** [comment] 2016-11-10 21:36
This should be fixed on next version ;)

**Closed by carloscabanero** 2016-11-10 21:36 UTC
