### ISSUE TITLE
Tapping the “Code” button in Files.app removes the leading forward slash from the path to open in VS Code

### ISSUE THREAD

**Issue by aerosoft-om** [blinksh/blink#1752] opened 2023-04-12 09:52 UTC
### Discussed in https://github.com/blinksh/blink/discussions/1743

<sup>Originally posted by **AS-Omar** March 31, 2023</sup>
Here's my host configuration:

```
SSH
Alias: domain
HostName: domain.company.com
User: root
Password: ****

FILES.APP LOCATION
Name: domain
Path: /
```

When I run this command in blink, it opens `myfolder` in VS Code successfully:

`code domain:/project/myfolder/`

However, when I try the following steps, `myfolder` does not open in VS Code. Instead, VS Code just shows the _Open Folder_, _Open Recent_, and _Open Remote Repository_ buttons in the Explorer sidebar:

1. Run the command `ssh domain` in blink.
2. Open Files.app and navigate to **Blink > project**.
3. Long-press on **myfolder** and then tap **Code**.

Upon inspecting blink’s history, I found that the **Code** button in step 3 above sends the following command to blink:

`code domain:project/myfolder/`

As you can see, the forward slash before `project` in the path above is missing. When I enter the command manually with the forward slash, `myfolder` opens successfully in VS Code.

Is there something wrong in my host configuration that’s causing the forward slash to be missing? Or is this a bug in blink?

**Comment by carloscabanero** [comment] 2023-04-12 16:18
I think this was a bug in Blink that we just fixed on https://github.com/blinksh/blink/discussions/1751. The issue is that we developed each command separately and having their own parser, which was not ideal but back in the day made us go fast. Paid our dues now.

Do you have access to TF? I will test this specific scenario from my side anyway.

**Comment by scho0ck** [comment] 2023-04-13 19:07
Can confirm having the same issue was pulling my hair out and even did a complete reinstall of the app to no avail.

**Comment by aerosoft-om** [comment] 2023-04-14 06:43
> Do you have access to TF?

@carloscabanero I’ve applied for the Community Edition but unfortunately haven’t received the invitation so far.

**Closed as completed** 2023-09-04 13:47 UTC
Labels: bug, RTT
