### ISSUE TITLE
Terminal dimensions badge in the middle won’t disappear

### ISSUE THREAD

**Issue by sssilver** [blinksh/blink#414] opened 2018-01-11 06:40 UTC
The square badge that displays the terminal dimensions won’t disappear when Alt+Tabbing to Blink. It’ll only go away if I pinch to adjust the terminal font size.

I’m using the Apple Smart Keyboard with the iPad Pro.

**Comment by javanut13** [comment] 2018-01-11 13:05
Duplicate of #385

**Comment by carloscabanero** [comment] 2018-02-16 20:57
Fixed on 10!

**Closed by carloscabanero** 2018-02-16 20:57 UTC
