### ISSUE TITLE
The caps lock remapping to escape is broken on iPad OS (beta 1 and beta 2) - was working before upgrade

### ISSUE THREAD

**Issue by dainmiller** [blinksh/blink#748] opened 2019-06-21 04:15 UTC
![61267242-F5A0-4495-86E9-340317161591](https://user-images.githubusercontent.com/46613794/59897426-75fc5680-93a1-11e9-87dc-36808f060980.png)

**Comment by zequix** [comment] 2019-06-21 13:54
just noticed the same thing!
what is the difference between caps as esc in the modifier mapping section and the caps as esc in the special keys section?

**Comment by dainmiller** [comment] 2019-06-22 23:08
@zequix no idea - I tried both though. They both seem to not be working at the moment.

**Comment by carloscabanero** [comment] 2019-06-23 16:15
This is a known issue on iOS13. The difference between the modifier and the special key is that the Special Key transform the Caps key press into the ESC key press. The modifier is used as a sequence, usually in combination with other keys.

Closing as dupe of https://github.com/blinksh/blink/issues/732, because although this one refers to Esc, the underlying issue is the same.

**Closed by carloscabanero** 2019-06-23 16:15 UTC
