### ISSUE TITLE
Last update broke it all

### ISSUE THREAD

**Issue by thinkberg** [blinksh/blink#582] opened 2018-11-02 17:38 UTC
It worked a few hours ago. Then I did the big update and now the IP address cannot be found anymore, even if I set the up address instead of the host name in the settings. It asks me to accept the host public key and then just fails again with „Did not find remote IP address“.

**Comment by thinkberg** [comment] 2018-11-02 17:39
ssh host simply returns with no message at all.

**Comment by yury** [comment] 2018-11-02 17:40
Sorry for that. 

You can use `ssh2` command as fallback. 

Investigating...

**Comment by yury** [comment] 2018-11-02 17:44
Can post ‘ssh -vvvvv host’ output here?

**Comment by masochist** [comment] 2018-11-02 18:01
> Sorry for that.
> 
> You can use `ssh2` command as fallback.

Why have two different commands that do the same thing?

**Comment by yury** [comment] 2018-11-02 18:05
`ssh2` is old implementation on top of `libssh2`. Same as it where. We leave it for this version for cases if upgrade doesn't go well. 

We reimplemented ssh client on top of `libssh` with new key types support, port forwarding, proxy command and ssh agent.

libssh and libssh2 are totally different libs (not versions), libssh supports more key types and API is cleaner.

**Comment by carloscabanero** [comment] 2018-11-02 18:20
Sorry about that. We have been working very hard on this and tested it very thoroughly with the whole community for months, so it is unfortunate :(

Changing the whole ssh piece plus adding proper features like ProxyCommand, etc... was no easy feat (that’s why we are the only app that does all of it).

Already working on it :)

**Comment by thinkberg** [comment] 2018-11-02 19:28
And don‘t sorry about me. I have a tendency to stumble over stuff like this ;-)

**Comment by carloscabanero** [comment] 2018-11-02 19:30
We have identified what was going on. A patch is coming.

**Comment by masochist** [comment] 2018-11-02 20:14
> On 2 Nov 2018, at 16:13, carloscabanero <notifications@github.com> wrote:


That’s great! Glad to hear you’ve worked it out. :)

Cheers,
Chris

**Comment by thinkberg** [comment] 2018-11-03 08:55
Great, looking forward testing it.

**Comment by yury** [comment] 2018-11-03 08:56
12.1 is out with the fix.

**Comment by thinkberg** [comment] 2018-11-03 09:51
Works! Thanks a lot.

**Comment by levex** [comment] 2018-11-03 10:33
Hitting this on v12.1

**Comment by levex** [comment] 2018-11-03 10:39
False alarm - looks like the App Store fooled me. I updated this morning and it said 12.1 but now there's another update which is the real 12.1 and it's working. Thanks!

**Comment by philosophish** [comment] 2018-11-04 14:42
Hello, 

Was a bit desperate, since I could not login to my servers (key based), then found this thread.

The update to 12.1 worked 1 time (of starting blink), now getting:

socket_callback_connected: Socket connection callback: 1 (0)
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.5p1-hpn14v12
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.5p1-hpn14v12
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.5 (70500)
blink: setting socket keepalive: 1
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
blink: import key xxxxxxxxxx
blink: open channels
blink: open session
ssh_packet_process: Couldn't do anything with packet type 80
ssh_packet_kexinit: Other side initiating key re-exchange
ssh_packet_process: Couldn't do anything with packet type 120
ssh_socket_exception_callback: Socket exception callback: 1 (0)
ssh_socket_exception_callback: Socket error: disconnected

Socket error: disconnected
blink> 


At least the workaround with ssh2 <hostname> still works...

**Comment by yury** [comment] 2018-11-05 09:05
Hi @philosophish 
what type of the key are you using? `blink: import key xxxxxxxxxx` rsa? ecdsa?

**Comment by philosophish** [comment] 2018-11-05 09:35
Hello, 

Thanks for replying.
I habe double-checked and basically it seems upon testing, I tripped over different versions on the servers.

It does work now with the machines where I have openssh >= 7.7 ; the problem is with the machines running a lower version of openssh e.g. 7.5. (as in the example above).

So, on the machines over which I have control I have upgraded openssl and openssh and everything is fine there; where I do not have the possibility (e.g. client machines) I am connecting to the servers with the "ssh2" command, which prevents the use of mosh but is a workable option.

**Comment by mgbaozi** [comment] 2018-11-06 08:09
Hello,
My problem is perhaps with keyboard-interactive (for two step authentication), but ssh2 is working.

```
blink: import key xxxxx
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
packet_send2: packet: wrote [len=620,padding=8,comp=611,payload=611]
ssh_packet_socket_callback: packet: read type 51 [len=44,padding=17,comp=26,payload=26]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Partial success. Authentication that can continue: keyboard-interactive
blink> 
```

**Comment by yury** [comment] 2018-11-06 08:10
Hi @mgbaozi,

Can you post top part of log? what version of server?

**Comment by mgbaozi** [comment] 2018-11-06 08:14
Thanks for reply,
My server version is `OpenSSH_7.4p1 Debian-10+deb9u3, OpenSSL 1.0.2l`
```
blink> ssh -vvvv xxx
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.4p1 Debian-10+deb9u3
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.4 (70400)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server xxxxxx:xxxx has ssh-ed25519 in known_hosts
ssh_knownhosts_algorithms: server xxxxxx:xxxx has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ssh-rsa"

```

**Comment by yury** [comment] 2018-11-06 08:36
@mgbaozi 
Interesting setup. I found an issue. 
Currently ssh command asks only once for allowed auth methods. So first time, it gets only `publickey`. And do not do `keyboard-interactive` at all after partial success.

Can you share your sshd/config? just for partial auth. 

Thank you.

**Comment by mgbaozi** [comment] 2018-11-06 08:43
@yury 
```
ChallengeResponseAuthentication yes
AuthenticationMethods publickey,keyboard-interactive
UsePAM yes
```

**Comment by yury** [comment] 2018-11-06 08:48
@mgbaozi 

Thank you. I was able to reproduce it. Fixing...

**Comment by mgbaozi** [comment] 2018-11-06 08:50
@yury Thanks a lot!

**Comment by yury** [comment] 2018-11-06 10:00
@mgbaozi fixed that. Thank you for you help.

**Comment by shannonmoeller** [comment] 2018-11-06 23:42
When will this be released? Missing mosh.

**Comment by yury** [comment] 2018-11-06 23:49
@shannonmoeller working on connection issues for some envs. 
Can you share your `ssh -vvvvv host` output?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shannonmoeller** [comment] 2018-11-07 00:04
```
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.7p1 Ubuntu-4
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.7p1 Ubuntu-4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.7p1 Ubuntu-4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.7 (70700)
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server 209.97.150.98:22 has ssh-ed25519 in known_hosts
ssh_knownhosts_algorithms: server 209.97.150.98:22 has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ssh-rsa"
packet_send2: packet: wrote [len=516,padding=4,comp=511,payload=511]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=4,comp=39,payload=39]
ssh_packet_socket_callback: packet: read type 51 [len=28,padding=12,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
```

**Comment by yury** [comment] 2018-11-07 00:11
Yep, that is the one I still can’t reproduce. Can you also post `ssh -G host` output?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shannonmoeller** [comment] 2018-11-07 00:13
You bet:

```
printaddress no
_printconfiguration yes
compression yes
compressionlevel 6
connectionattempts 1
connecttimeout 20
exitonforwardfailure no
forwardagent no
forwardx11 no
hostname 209.97.150.98
identityfile None
kbdinteractiveauthentication yes
loglevel info
numberofpasswordprompts 3
passwordauthentication yes
port 22
pubkeyauthentication yes
requesttty auto
serveralivecountmax 3
serveraliveinterval 0
stricthostkeychecking ask
tcpkeepalive yes
user xxxxxx
```

I’m trying to connect to a DigitalOcean droplet running Ubuntu 18.10.

**Comment by shannonmoeller** [comment] 2018-11-07 00:19
This is wrong:

```
passwordauthentication yes
```

I have password auth turned off at the server.

**Comment by yury** [comment] 2018-11-07 00:28
Ok, thank you for your logs.

What is wrong is `identityfile None`

1. Do you have any keys under `config` -> `keys`? 
2. Do you have `.ssh/ssh_config` file?
3. Can you post output from `ssh -i <your key> -vvvvvv host` and also `ssh -i <your key> -G host`

I will try to create same droplet.

**Comment by shannonmoeller** [comment] 2018-11-07 00:55
1. Yes
2. No
3. Here you go:

```
blink> ssh -vvvvv -i id_rsa remotedev
ssh_connect: libssh 0.7.90 (c) 2003-2018 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.7p1 Ubuntu-4
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.7p1 Ubuntu-4
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.7p1 Ubuntu-4
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.7 (70700)
ssh_connect: current state : 4
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_knownhosts_algorithms: server 209.97.150.98:22 has ssh-ed25519 in known_hosts
ssh_knownhosts_algorithms: server 209.97.150.98:22 has ssh-rsa in known_hosts
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ssh-rsa"
packet_send2: packet: wrote [len=516,padding=4,comp=511,payload=511]
packet_send2: packet: wrote [len=44,padding=6,comp=37,payload=37]
ssh_connect: current state : 6
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
ssh_packet_dh_reply: Received SSH_KEXDH_REPLY
packet_send2: packet: wrote [len=12,padding=10,comp=1,payload=1]
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
crypt_set_algorithms2: Set output algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
crypt_set_algorithms2: Set input algorithm to aes256-ctr
crypt_set_algorithms2: Set HMAC output algorithm to hmac-sha2-256
ssh_packet_newkeys: Signature verified and valid
ssh_connect: current state : 7
blink: setting socket keepalive: 1
packet_send2: packet: wrote [len=28,padding=10,comp=17,payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_userauth_request_service: Failed to request "ssh-userauth" service
ssh_packet_socket_callback: packet: read type 6 [len=28,padding=10,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [len=44,padding=4,comp=39,payload=39]
ssh_packet_socket_callback: packet: read type 51 [len=28,padding=12,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
blink: import key id_rsa
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
packet_send2: packet: wrote [len=1132,padding=5,comp=1126,payload=1126]
ssh_packet_socket_callback: packet: read type 51 [len=28,padding=12,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied. Authentication that can continue: publickey
```

```
blink> ssh -G -i id_rsa remotedev
_printaddress no
_printconfiguration yes
compression yes
compressionlevel 6
connectionattempts 1
connecttimeout 20
exitonforwardfailure no
forwardagent no
forwardx11 no
hostname XXX.XXX.XXX.XXX
identityfile id_rsa
kbdinteractiveauthentication yes
loglevel info
numberofpasswordprompts 3
passwordauthentication yes
port 22
pubkeyauthentication yes
requesttty auto
serveralivecountmax 3
serveraliveinterval 0
stricthostkeychecking ask
tcpkeepalive yes
user XXXxxXX
```

**Comment by shannonmoeller** [comment] 2018-11-07 01:38
Just one key.

**Comment by shannonmoeller** [comment] 2018-11-07 01:39
I recreated my droplet twice and I deleted Blink and reinstalled twice. Exact same issues each time.

**Comment by yury** [comment] 2018-11-07 02:30
ok, I think we are very close. Sorry for bothering you with questions.

Just to be shure what version are you using `help` command prints it.
How you create your key? You import it or create new one?

What I did.
1. I installed latest version 12.1 from App Store. (I have id_rsa key in blink)
2. I created droplet (with no preconfigured keys in DO interface)
3. I got password, shh to root@<ip> with password from email
4. I changed default password
5. I `ssh-copy-id id_rsa root@<ip>` 
6. I'm able to ssh root@<ip> without password and issues.
7. I created host DO with user root and key id_rsa
8. I'm able to connect to droplet with `ssh DO` too

**Comment by shannonmoeller** [comment] 2018-11-07 15:34
I have one Blink key and use it to access DO, yes. I also have a key I use to access DO from a laptop.

1. I installed Blink 12.1 from App Store
2. I created a passwordless key in Blink using `ssh-keygen-t rsa`
3. I copied the key and added it to the list of keys on DO.
4. I created an Ubuntu 18.10 droplet and told it to use the two keys I copied to access the droplet.
5. I accessed root@[ip] from my laptop and added a non root user.
6. I copied `/home/root/.ssh/authorized_keys` to `/home/[username]/.ssh/authorized_keys`.
7. I chown and chgrp the non-root user’s .ssh dir and .ssh/authorized_keys to be the user.
8. I `sudo chmod 0700 .ssh` and `sudo chmod 0600 .ssh/authorized_keys`
9. I exited out of the ssh connection and reconnected to [user]@[ip] from the laptop. It connects just fine.
10. I verified that the .ssh/authorized_keys file contained the Blink id_rsa.pub line and exited the ssh connection
11. I then try to connect to both [root]@[ip] and [user]@[ip] with ssh and mosh via Blink and experience what the OP describes. ssh silently fails and mosh says it can’t find the IP.

**Comment by shannonmoeller** [comment] 2018-11-07 16:17
Oh, and help prints `12.1.4. Nov 2 2018`

**Comment by shannonmoeller** [comment] 2018-11-07 16:23
@yury Shoot me an email with a .pub and I’ll get you root auth to the droplet. I’ll need to recreate it anyway.

me@shannonmoeller.com

**Comment by yury** [comment] 2018-11-08 08:10
@shannonmoeller sorry for late response.
But I think I understand what is going on :)

Blink supports two keys storages: Secure Enclave (`config`->`keys`) and file system (`~/.ssh/`).
Blink looks keys in Secure Enclave first and then in `~/.ssh`.
Also Blink creates id_rsa in Secure Enclave by default. 

So id_rsa key in `config` -> `keys` and in `.ssh/` are different, but with same name. 
`ssh-keygen` is not recommended way to create keys with blink.
You can just copy key from `config` -> `keys` and set it up in DO (no need to generate key with `ssh-keygen`)

I will add extra working to verbose output if we have key with same name in blink and `.ssh`

**Comment by shannonmoeller** [comment] 2018-11-08 14:53
Ok. That makes sense. Why was it working in the old version?

Also, I’m pretty used to the CLI tools and having ssh-keygen available to use when it’s not the right thing to use is super confusing.

**Comment by shannonmoeller** [comment] 2018-11-08 15:12
I copied the key I created with ssh-keygen into `config` > `keys`, created a host with `config` > `hosts` and everything is working now! Thanks for looking into it.

I’d highly recommend either disallowing the use of ssh-keygen or, preferably, some sort of integration between ssh-keygen and the `config` > `keys` UI. Same for `.ssh/config` and `config` > `hosts`.

Thanks again. SO freaking happy to have mosh back! :)

**Comment by yury** [comment] 2018-11-08 16:33
Prev version don't use keys from `.ssh/`. May be you imported key in config?

Anyway, I'm glad that you have mosh back! And yes, I think we should make `ssh-keygen` work with Secure Enclove by default and file system with the flag.

**Comment by tomalok** [comment] 2018-11-15 17:53
trying blink for the first time today, surprised that `ssh` didn't work out of the box.  some investigation on the server side shows that it's not offering sufficiently secure key exchanges...
```
Nov 15 16:22:43 [sshd] fatal: Unable to negotiate with 1.2.3.4: no matching key exchange method found. Their offer: diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1 [preauth]
```
(fortunately, `ssh2` appears to be working.)
is there a way to force the new `ssh` to use better key exchanges?

**Comment by carloscabanero** [comment] 2018-11-15 17:57
What server are you connecting to? The diffie-hellman-group1-sha1 should have done the trick though.

**Comment by tomalok** [comment] 2018-11-15 18:08
@carloscabanero - deleted my original comment -- turns out i was looking at the wrong line server log line, it was a different IP attempting to SSH into my server, which explicitly disallows SHA1 and other older insecure key exchange algorithms.

`ssh2` is working, but the newer `ssh` is failing with the following message on the server:
```
Nov 15 17:56:00 [sshd] fatal: ssh_dispatch_run_fatal: Connection to 1.2.3.4: invalid format
```
From `ssh -vv`, after entering my password I see...
```
blink: open channels
blink: open session
channel_open: Creating a channel 43 with 2097152 window and 32768 max packet
ssh_packet_global_request: Received SSH_MSG_GLOBAL_REQUEST packet
ssh_packet_global_request: UNKNOWN SSH_MSG_GLOBAL_REQUEST hostkeys-00@openssh.com 0
ssh_packet_process: Couldn't do anything with packet type 80
ssh_packet_kexinit: Other side initiating key re-exchange
ssh_packet_dh_reply: Receieved SSH_KEXDH_REPLY
ssh_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
ssh_packet_process: Couldn't do anything with packet type 120
ssh_socket_exception_callback: Socket exception callback: 1 (0)
ssh_socket_exception_callback: Socket error: disconnected
```

**Comment by yury** [comment] 2018-11-15 18:10
@tomalok can you post log with more verbose output (1st-vvvvvv`)?

**Comment by tomalok** [comment] 2018-11-15 18:11
@yury I'll see what I can do -- I hand transcribed the above slice from my iPad...  ;P

**Comment by yury** [comment] 2018-11-15 18:12
You can do smth like `ssh -vvvvvv host 2 > log.txt` then `pbcopy  log.txt`

**Comment by yury** [comment] 2018-11-15 18:34
Oh yea, sorry  it should be`cat log.txt | pbcopy`.

Digging in to logs, thank you.

**Comment by yury** [comment] 2019-01-11 07:43
Since we have all these issues as separate, I close this general one.

**Closed by yury** 2019-01-11 07:43 UTC
