### ISSUE TITLE
Control-space switches input language

### ISSUE THREAD

**Issue by kek** [blinksh/blink#782] opened 2019-08-09 09:02 UTC
The issue #606 seems to appear again in iPadOS 13.0 (17A5547d). Control-space doesn’t go through to the application but rather switches input languages, regardless of ”Capture control-space” setting. A workaround is to disable all alternative input languages and the emoji input method under the keyboard settings of system preferences.

**Comment by yury** [comment] 2019-08-09 09:35
Yep, we are aware about that. We have submitted radar to apple, but please, submit also. That way they will get attention to that issue.

Thank you.

**Comment by mlabbe** [comment] 2019-08-15 20:08
I’m seeing this as well.  I’ve reported it as beta feedback to them. Do they usually fix these sorts of things?

**Comment by treyharris** [comment] 2019-09-06 19:50
> Yep, we are aware about that. <b>We have submitted radar to apple, but please, submit also.</b> That way they will get attention to that issue.

Can you provide or link to instructions on how to “submit radar to Apple” for those who don’t know?

**Comment by yury** [comment] 2019-09-06 19:55
Hi @treyharris 
There is Feedback.app on betas. You should submit issue form there.

**Comment by treyharris** [comment] 2019-09-06 20:12
Also https://feedbackassistant.apple.com/ works.

**Comment by filcab** [comment] 2020-06-01 13:32
Seems like it's not a bug anymore, and it's a "feature" of iOS 13.
Anyone who knows a bit more about iOS: Any clues on what can be done about this? I wonder which of these is preferable:

- Have blink grow a feature to map "some sequence" to ctrl+space
- Have users just not rely on ctrl+space (arguably not doable in general)
  - Would work for some if they're using tmux/anything which can do the mapping
- Have users disable multi-language input (*definitely* not doable in general)

P.S: I wonder if it's best to remove the setting to catch ctrl+space or, at least, mention next to it that if multilanguage keyboards are enabled, it still won't work.

**Comment by yury** [comment] 2020-06-01 14:28
Update:
@filcab actually there is a way to catch ctrl+space on 13.4+

**Comment by yury** [comment] 2020-06-05 11:57
You can add custom press ctrl+space and assign it to ctrl+space.
We don't turn it by default, so other people can use ctrl+space to switch languages.

Blink 13.5.1 is released.

**Closed by yury** 2020-06-05 11:57 UTC

**Comment by geoffp** [comment] 2020-10-09 20:19
@yury Emacs user here! The custom press for ctrl+space workaround is okay, but it requires you to release the control key before issuing another control-key command, which I (as I’d guess many) do immediately afterwards to move the cursor. It really breaks the Emacs flow.

@tjim from Ish found [this way to do it](https://github.com/ish-app/ish/commit/1f5dd7840d9814dc50261efd7c3448609b8fe95e) that seems to work really well.


<img width="586" alt="Screenshot 2020-10-09 at 3 16 39 PM" src="https://user-images.githubusercontent.com/76232/95627923-ad818d00-0a42-11eb-8891-43fc50c7b5ff.png">

**Comment by dddominikk** [comment] 2021-12-26 16:26
Sigh, it's nearly 2022 and this has been wrecking my Intellisense-propped habits so hard. And I thought paying the price of 3 keyboards for one without function keys was the worst thing about it.

While the above workaround didn't work for me on the latest iPad OS, deleting every other language keyboard did it, for obvious reasons.

**Comment by Nondv** [comment] 2022-09-09 07:32
Stumbled upon this issue. Creating a shortcut in latest Blink (I also paid the subscription) helped.

`config` -> Keyboard -> Custom Presses -> Add

Just press Ctr+Space and in "Action" choose "Press ^_" (basically, create a shortcut that just passes the shortcut to the terminal lol)
