### ISSUE TITLE
Feature request for non-English input support 

### ISSUE THREAD

**Issue by mzvast** [blinksh/blink#252] opened 2017-03-08 17:56 UTC
Currently in blink, I can't input language other than English,for instance Chinese.
Will this missing feature be supported?

**Comment by carloscabanero** [comment] 2017-03-20 17:52
We actually already worked on it, and have a few commits waiting to be merged (Atul's branch) supporting this. I wanted to do it right by using an overlay, as I saw that other terminals really sucked with Unicode or had problems sending the codes. If you can help me out testing and ensuring that the experience is fine, we could probably get this rolling for next month :)

**Comment by mzvast** [comment] 2017-03-21 07:41
@carloscabanero I'm happy to test it :)

**Comment by kevingriffin** [comment] 2017-06-24 12:28
I'd be happy to test this for Japanese as well!

**Comment by cijianzy** [comment] 2017-07-22 06:52
@carloscabanero  Would you please give me the link about this support, I didn't find this pull request  -_-!.  Thx.

**Comment by backav** [comment] 2017-12-01 08:30
Is there anything new about this?

**Comment by carloscabanero** [comment] 2017-12-18 20:17
We have rebumped the Terminal code for the new libssh, and this should now be a lot easier to implement. Will reprioritize again.

Closing here as duplicate of #206.

**Closed by carloscabanero** 2017-12-18 20:17 UTC
