### ISSUE TITLE
Blink v15 crashes during v14 settings import on iPad

### ISSUE THREAD

**Issue by Go0nNow** [blinksh/blink#1385] opened 2022-02-11 20:45 UTC
Importing settings from v14 into v15 crashes after v14 app returns to v15 app following confirmation of data export.

Attempting this on iPhone 13 mini was successful, but consistently crashes on iPad Pro 10.5.

**Comment by jadomski** [comment] 2022-02-12 02:45
Interestingly, I experienced the crash when importing on my iPhone 12 mini but not on my iPad mini 6

**Comment by zenspider** [comment] 2022-02-12 20:08
I experienced it on my iphone

**Comment by carloscabanero** [comment] 2022-02-12 23:45
We identified what the issue is and will have a fix by Monday. As a Workaround, settings get copied and it is only ssh keys that won't be restored. Although inconvenient, those can be moved manually if you only have a few.

Apologies for the inconvenience.

**Comment by carloscabanero** [comment] 2022-02-15 20:26
Fixed on latest version 15.0.3, just made it to the AppStore.

**Closed as completed by carloscabanero** 2022-02-15 20:26 UTC
