### ISSUE TITLE
Replace Webview with native renderer

### ISSUE THREAD

**Issue by Schr3da** [blinksh/blink#794] opened 2019-09-05 22:34 UTC
Hey,

I do a lot of development on the go using my iPad and Blinksh. I really like that product!. However I would really suggest to get rid of the Webview based rendering and replace it 
with a native view renderer...

Do you have any plans on that or are there any people available who would like to work on it?
The benefits besides longer battery life would be also more responsive UI...

Kind regards
Schr3da

**Comment by carloscabanero** [comment] 2019-09-05 22:54
Hi Schr3da! Thanks for the kind words and the idea. We did consider it but bringing one more terminal emulator to the world with so many great ones and all the battles we have open already felt like a ton of work. We have been making big optimizations to Hterm though through the years and we have benchmarks that show we are faster than even most of the desktop ones (except the GPU accelerated). So one question for you, where are you feeling it to be responsive? Maybe we can try and fix that first.

PS Thanks for helping out with support tickets too! :)

**Comment by sn00pster** [comment] 2019-09-05 23:01
I see a lot of problems with the renderer, usually manifest when reusing a “session” to start another one, I get a display that is garbled, input that isn’t correct and so forth.

I’ll try to come up with some steps to replicate, but it’s defjnitely related to reusing sessions multiple times.

**Comment by treyharris** [comment] 2019-09-06 20:31
@sn00pster What do you mean by “reusing” sessions? As discussed in mobile-shell/mosh#394, reattaching to detached mosh sessions is not possible.

If you’re using `screen` to reattach to sessions, this is a known issue on screen’s end, not Blink’s; consider using `tmux` instead.

If you are talking about Tmux, some screenshots would be useful.

**Comment by sn00pster** [comment] 2019-09-06 20:35
When I mean reusing a session I mean logging out of the current server that a window is connected to and logging into a new one in the same “window”.

this seems to be a sure fire way of causing the terminal to go haywire, it doesn’t happen every time but it does seem to be the best way to reproduce this issue.

**Comment by yury** [comment] 2019-09-06 20:38
@treyharris, blink can reattach (restore) mosh connection without tmux or screen.

As for grabled screen - it can be if device is restored in different orientation (sometimes iOS rotates app in background to make snapshots). Try to refresh screen with ctrl+^ l

**Comment by yury** [comment] 2019-09-06 20:40
@sn00pster, oh, that is different scenario... interesting..

**Comment by treyharris** [comment] 2019-09-06 20:42
@sn00pster I see.

If you’re using SSH rather than Mosh, you should try Mosh. Part of what Mosh does is abstract terminal emulation—not directly for rendering, but to enable optimizations on bursty/high-latency data channels—and as such has the effect of “washing” “dirty” TTY’s such that it generally leaves them in a good state for later use. SSH does not manipulate its output like this at all.

@yury Fascinating! You do mean _lost_ sessions such as when the window is deleted, right, not simply the “roaming” type of reattachment that Mosh does all the time and that has nothing to do with that issue I referenced? If so, I wonder why the folks working on Mosh seem to believe this is impossible?

**Comment by sn00pster** [comment] 2019-09-06 20:43
I use mosh pretty much exclusively unless it’s on an embedded system that doesn’t support it.

**Comment by treyharris** [comment] 2019-09-06 20:47
@sn00pster I have a very old shell prompt I’ve been agglomerating for decades that has an awful mix of pre-UTF8 and post-UTF8 code, and sometimes I get visual artifacts that usually manifest as mojibake (incorrect Unicode characters) unless I use Mosh + Tmux. Mosh + Screen or just plain Mosh, or SSH + anything, make this happen.

This isn’t a bug on the part of any terminal emulator because I’m giving it bad output. I would have cleaned up my shell code years ago, but Mosh + Tmux clean it all up so I don’t have to.

**Comment by yury** [comment] 2019-09-06 20:47
@treyharris blink mosh client not just “roaming”. You can turn off device, reboot it or event upgrade iOS :).  Blink tries to store mosh state in secure space.

But yes, you cannot reattach to lost session. (For instance, if app crashed or you killed it with app switcher)

**Comment by treyharris** [comment] 2019-09-06 20:52
@yury Yes, we have the same understanding—the case where, on Linux servers, you get a pre-login message `Detached mosh session at [<pid>]`; there’s no way to reattach to `<pid>`.

The other type of reattaching you don’t have to _do_ anything for, and (AFAIK) it’s impossible to tell you’re doing it from the user side, so I presumed @sn00pster must have been talking about something else. 

Getting visual artifacts from a normal restored Mosh session would be very weird since Mosh is paying attention to terminal state—but I don’t think you could report it, since you wouldn’t know that was when it was happening (it would be a “getting visual artifacts sometimes when returning to the app” bug instead).

**Comment by treyharris** [comment] 2019-09-06 20:55
I’d also mention that this might be an unusual presentation of #778 — if you actually try to use the Blink shell to mosh again, you’ll get very weird results indeed.

**Comment by yury** [comment] 2019-09-06 21:15
Trying to reproduce on new version.... and it seems to be ok. Will install app store version and try it too.

**Comment by sn00pster** [comment] 2019-09-06 23:34
> I’d also mention that this might be an unusual presentation of #778 — if you actually try to use the Blink shell to mosh again, you’ll get very weird results indeed.

Looks very similar.

What I also find when this happens is that what I type as a command seems to get corrupted with whatever is on the screen where I type as well.  I’ve noticed this quite a few times that I can’t actually type a command in because what gets to the other end is oncorrect.

**Comment by treyharris** [comment] 2019-09-07 17:24
> What I also find when this happens is that what I type as a command seems to get corrupted with whatever is on the screen where I type as well. I’ve noticed this quite a few times that I can’t actually type a command in because what gets to the other end is oncorrect.

Incorrect? Like, you’ve seen a `bash: DIFFERENT_FROM_WHAT_YOU_TYPED: command not found`? Or possibly are you getting a response from Blink (which would ordinarily be just `...: command not found`, without the `bash:` or anything replacing it)?

**Comment by sn00pster** [comment] 2019-09-07 17:30
> > What I also find when this happens is that what I type as a command seems to get corrupted with whatever is on the screen where I type as well. I’ve noticed this quite a few times that I can’t actually type a command in because what gets to the other end is oncorrect.
> 
> Incorrect? Like, you’ve seen a `bash: DIFFERENT_FROM_WHAT_YOU_TYPED: command not found`? Or possibly are you getting a response from Blink (which would ordinarily be just `...: command not found`, without the `bash:` or anything replacing it)?

Bash command on the other end doesn’t execute correctly, either extra characters or missing characters from what I typed.

**Comment by carloscabanero** [comment] 2021-02-16 13:05
Closing here. We have been tweaking our rendering for the last years and we are still A LOT faster than anything else out there. Plus it is giving us a lot of goodies. If we consider this in the future, we can open a new issue.

**Closed by carloscabanero** 2021-02-16 13:05 UTC
