### ISSUE TITLE
Support for Solarized (Dark) colorscheme

### ISSUE THREAD

**Issue by rekendahl** [blinksh/blink#2] opened 2016-03-31 18:57 UTC
I'd like to see support for the solarized colorshemes https://github.com/altercation/solarized

It has great dark and light colors that are not tiring.

In iTerm I had to import color settings and it then looks like this:

![screen shot 2016-03-31 at 2 42 31 pm](https://cloud.githubusercontent.com/assets/1612072/14187363/9e9b208a-f750-11e5-983f-d0367300ba39.png)

Currently the same view in BLINK looks like this

![img_0022](https://cloud.githubusercontent.com/assets/1612072/14187369/a812a048-f750-11e5-984a-9d9304fc748e.PNG)

It can be read but doesn't look great. 

Getting color schemes to work is a pain in the behind but an important feature for power users

**Comment by cirqueit** [comment] 2016-04-13 23:18
+1
I think Solarized would be a great choice for initial themes

**Comment by jjo93sa** [comment] 2016-05-18 14:23
+1 for Solarized

**Comment by binaryben** [comment] 2016-05-26 11:18
How do colour work using Mosh? Is it different from SSH? I thought the server just sends colour information and the receiving terminal just displays it... So much to learn.

The reason I ask though; does this mean every colour theme has to explicitly be supported by the Mosh client rather than simply setting any custom colour themes in Vim for example?

**Comment by carloscabanero** [comment] 2016-06-02 13:01
Actually Mosh doesn't support truecolor. And the problem isn't with that, we can solve it at the terminal level, the same way that iTerm does. :)

**Comment by Riprock** [comment] 2016-06-15 21:34
This is what I miss the most from JuiceSSH on Android when using Prompt on iOS (and maybe port forwarding). I can use vim in 256 colour mode, as long as I don't look at it with proper colours ever and realise how much better it is. Glad to see Blink does work with 256 colour mode though.

**Comment by carloscabanero** [comment] 2016-08-17 14:57
Closing here, issue created on #86

**Closed by carloscabanero** 2016-08-17 14:57 UTC
Labels: feature
