### ISSUE TITLE
The built-in Source Code Pro font is not available.

### ISSUE THREAD

**Issue by geometryolife** [blinksh/blink#1337] opened 2021-12-16 11:11 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration
iPadOS 15.2

### Describe the bug

The built-in Source Code Pro font is not available.
![16337F1E-880E-433A-9863-55AB11FFB759](https://user-images.githubusercontent.com/54882546/146361170-d7977769-bebc-49e5-b115-61a1dd27ecca.jpeg)

**Comment by yury** [comment] 2021-12-16 11:15
Hello @geometryolife 

For performance reasons, we apply fonts only for new terminals. Please press CMD+T to create new terminal.

I'm closing this issue, feel free to reopen if needed.

**Comment by geometryolife** [comment] 2021-12-16 11:45
> Hello @geometryolife
> 
> For performance reasons, we apply fonts only for new terminals. Please press CMD+T to create new terminal.
> 
> I'm closing this issue, feel free to reopen if needed.

I tried but still didn't work

**Comment by yury** [comment] 2021-12-16 12:06
I can't reproduce this yet. Can you record short video?

**Comment by geometryolife** [comment] 2021-12-16 12:18
> I can't reproduce this yet. Can you record short video?

I succeeded, but every time I came in it would reset and I had to open the settings to use `CTRL-T` to switch, which was a bit of a hassle. I don't know if I can remember my settings.

**Comment by yury** [comment] 2021-12-16 12:20
can I invite you to your TestFlight? We have that fixed, but I think we didn't release on App Store that yet.

**Comment by geometryolife** [comment] 2021-12-16 12:22
> can I invite you to your TestFlight? We have that fixed, but I think we didn't release on App Store that yet.

Sure, thank you.

**Comment by yury** [comment] 2021-12-16 12:23
Can you email me at yury.korolev@gmail.com ? I need your email to send invite.

**Comment by geometryolife** [comment] 2021-12-16 13:57
> Can you email me at [yury.korolev@gmail.com](mailto:yury.korolev@gmail.com) ? I need your email to send invite.

After the test, blink can indeed remember my settings.

**Closed as completed** 2021-12-16 13:58 UTC
Labels: support
