### ISSUE TITLE
Alt+number sending ASCII characters instead of Alt+number sequence

### ISSUE THREAD

**Issue by smidget** [blinksh/blink#94] opened 2016-08-17 02:40 UTC
It looks like Alt+number is intercepted by iOS. For example Alt+2 on the iPad Pro US-English keyboard sends ™ instead of Alt+2, whereas on my Macbook in Terminal.app it sends the proper key sequence.

**Comment by carloscabanero** [comment] 2016-08-17 14:41
Good catch! this is a quick fix, I didn't include numbers for the control sequences.

**Comment by carloscabanero** [comment] 2016-08-17 17:03
This is related to #40

**Comment by carloscabanero** [comment] 2016-08-27 20:10
Should be fixed on next release.

**Closed** 2016-08-27 23:48 UTC
Labels: bug, WIP

**Comment by lukebrowell** [comment] 2016-08-28 01:03
Blink: v0.927.27. Aug 27 2016
**Steps to reproduce:**
  1. Open Blink and try to type a ```#``` character (alt/option+3) on bluetooth keyboard.

**Expected Outcome:**
 * It should display the ```#``` character

**Actual Outcome:**
 * It displays the ```3``` character

**Notes:**
 * Makes editing dotfiles, shell comments and writing markdown awkward. 
 * Not a feature in other ios ssh clients.

**Comment by carloscabanero** [comment] 2016-08-28 16:46
By default Alt is Mapped to altSendsEsc, and that's why it prints three. Set Alt to None and it will behave as normal ;)I might just change the default because as you mention, it isn't the standard behavior.

		_____________________________
