### ISSUE TITLE
add host in config doesn't work with magic keyboard atached

### ISSUE THREAD

**Issue by fredvd** [blinksh/blink#1858] opened 2023-09-10 11:22 UTC
Using blink testflight 17.0.0.833.   iPad OS 16.6.1

Using aMmagic Keyboard, entering config on the terimanl , then select hosts, add host, the host add modal behaves erratically .

 Sometimes entering a field and presssing some keys works, most times it does't. The blink shell in the backend flickers/gets redrawn on some keypresses in the background. Sometimes a field doesn't accept any input. 

When I detach the iPad from the magic keyboard, the hosts add form works fine.

**Comment by yury** [comment] 2023-09-11 10:48
Hello @fredvd 

Trying to reproduce - no luck yet.

Can you record short video?

**Comment by fredvd** [comment] 2023-09-17 11:54
@yury Sorry for the delay. I recorded a screencast, while doing I think I found out what triggers this: using tab to move to the next field in the modal. The screencast isn't very clear in that, but when I tab out of the field, the background terminal seems to be activated/flickers, but other key input is not going into to the field and it seems to be greyed out very shortly as well. 

https://github.com/blinksh/blink/assets/394784/617d2a5b-6e68-48fa-b89f-ecee7ea56f55

**Comment by yury** [comment] 2023-09-17 12:34
Seems like easy fix... Will try on Monday. Thank you!

**Comment by yury** [comment] 2023-09-18 07:48
Good news :) it seems to be fixed in iPadOS 17...

**Comment by fredvd** [comment] 2023-09-18 19:40
I can confirm the problem no longer occurs in the IPadOS 17 build.  With tab I can navigate through the fields in the add host modal and all fields can be edited.  (just updated to iPadOS 17)

**Comment by carloscabanero** [comment] 2023-09-26 14:58
Closing

**Closed as completed** 2023-09-26 14:58 UTC
Labels: bug
