### ISSUE TITLE
Blink appears to lose connection to the foreground tab when device sleeps

### ISSUE THREAD

**Issue by rrgeorge** [blinksh/blink#1063] opened 2020-07-02 19:10 UTC
I’ve been noticing recently that The active tab will lose connection and be unable to reconnect if my iPad goes to sleep while blink is open. iPadOS 13.5.1, blink 13.5.2.238
My working theory is that the packet sequence doesnt get saved
So it tries to reconnect with an older sequence than it has actually used
Only the tab thats in the foreground has issue
It doesn’t always happen, possibly requires the network interface to lose connection, or the device to sleep for a certain period.

**Comment by carloscabanero** [comment] 2020-07-07 15:31
This may be a duplicate of #1048. Thanks for the extra pointers. Will close here and track there.

**Closed by carloscabanero** 2020-07-07 15:31 UTC
Labels: bug
