### ISSUE TITLE
Siri shortcut for mosh command missing host

### ISSUE THREAD

**Issue by Harwood** [blinksh/blink#592] opened 2018-11-07 02:17 UTC
If I use the Siri & Search settings menu to add a Siri command `run: ssh mySystem` everything executed as expected when the command is given. However if I do the same with mosh `run: mosh mySystem` then when executed Blink executes `mosh` without any arguments and displays the help info. 

Seen in TestFlight 12.0 build 38

**Comment by Harwood** [comment] 2018-11-15 21:08
@yury,

Thanks for getting back to me. I've tested with TestFlight 12.2 build 56 with no success. Here are screenshots of me using "Siri test" to run `mosh Pluto`. 

However, if I do the same using "Siri test" to run `ssh Pluto` everything executes as expected.

![img_3060dcb65d54-1](https://user-images.githubusercontent.com/1222752/48581284-01cb7300-e8e7-11e8-9e6f-405edfb811f8.jpeg)
![img_fa21517a5ac5-1](https://user-images.githubusercontent.com/1222752/48581289-05f79080-e8e7-11e8-8f27-c3bf8273f3bd.jpeg)

![img_c271ce522351-1](https://user-images.githubusercontent.com/1222752/48581550-c9786480-e8e7-11e8-9691-f5f1ec9581c3.jpeg)
![img_de6605b58358-1](https://user-images.githubusercontent.com/1222752/48581715-2d029200-e8e8-11e8-87e7-07a90887f760.jpeg)

**Comment by willhbr** [comment] 2018-11-15 22:50
FWIW, I also have the behaviour @Harwood describes when using the "mosh myserver" action from spotlight.

**Comment by maurizio-manuguerra-mq** [comment] 2018-12-27 00:54
Same here.
Any fixes?

**Comment by toph-allen** [comment] 2019-03-08 19:06
I posted #695 (sorry for the dupe — I posted it from my phone, so didn't have a chance to search the issues). I've attached a video here of the issue as a zip file.

Sorry I can't be more helpful. If there's anything else I can provide, let me know.

[IMG_6214.TRIM.MOV.zip](https://github.com/blinksh/blink/files/2947106/IMG_6214.TRIM.MOV.zip)

**Comment by j-tai** [comment] 2019-03-13 01:16
Still occurs if you pass in a command to run, e.g. `mosh myhost echo Hello`. (v12.7 from App Store)

**Comment by yury** [comment] 2019-03-13 06:30
Yep, app version (v12.8) with the fix is not in App Store yet.

**Comment by toph-allen** [comment] 2019-03-13 15:00
@yury Is there a way to sign up for the TestFlight builds? I'd definitely be interested in running them.

**Comment by yury** [comment] 2019-03-13 19:40
@toph-allen sure, ping me at yury.korolev@gmail.com

**Comment by yury** [comment] 2019-03-14 06:24
Pushed 12.8 for TF review. Should be available soon.

**Comment by toph-allen** [comment] 2019-03-14 20:16
I still seem to be having the issue in the new TestFlight build. On my iPhone, I tried deleting-restarting-reinstalling, in case it was some weird old cached shortcut data, but that didn’t work either.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maurizio-manuguerra-mq** [comment] 2019-03-14 20:39
The new testflight build does not work for me as well: while the command “mosh test” works when run from blink’s command line (test is a connection), it doesn’t when run from apple shortcuts.

**Comment by yury** [comment] 2019-03-15 07:48
Do not why my shortcuts where working (`mosh office`, and `mosh imac`). But I finally found original issue (being able to reproduce with `mosh 192.168.0.2`).

Fix in v12.8 build 89.

But you have to rerun those commands first. Because donated activities are broken.

**Comment by toph-allen** [comment] 2019-03-15 13:01
Build 89 seems to have broken `mosh` entirely for me. On both my testing devices (iPhone and iPad running the latest iOS 12.2 beta, I get:

```
blink> test

Socket error: Unknown error: -1
Did not find remote IP address
```

This persists after deleting and reinstalling the app.

**Comment by yury** [comment] 2019-03-15 13:37
Thank you @toph-allen.

**Comment by yury** [comment] 2019-03-15 15:01
Build 91 is out.

**Comment by maurizio-manuguerra-mq** [comment] 2019-03-15 19:55
Build 91 does not solve the original problem for me.
“mosh test” works if run from blink, but does not from apple shortcuts.
“ssh test” always works.

**Comment by yury** [comment] 2019-03-15 19:57
Hi @maurizio-manuguerra-mq 

You have to recreate Siri shortcut. Since issue was in donating wrong command in activity.

**Comment by toph-allen** [comment] 2019-03-15 20:15
Build 91 also didn't fix it for me.

Perhaps this is because the old incorrect command had already been donated to the system's store, and so any new instances don't overwrite it? As far as I can tell, it persists between installs, too, and also includes mistyped and deleted servers (see #700 for a bug report about this behavior).

It's possible for an *app* to delete its donated shortcuts — this page documents how: [Deleting Donated Shortcuts | Apple Developer Documentation](https://developer.apple.com/documentation/sirikit/deleting_donated_shortcuts). Perhaps it's necessary for Blink to have donated shortcuts expire every so often, or to provide some sort of troubleshooting option to manually purge them?

**Comment by yury** [comment] 2019-03-15 20:25
@toph-allen,

We do not donate anything yet with Siri Shortcuts API. We just activating NSUserActivity with command you typed. So yet, we do not control what operation it is (cp, spc, mosh, or smth else). We could try to find any matches of the host and try to delete activity donations for that host. But for now it is not good way to do that.

[Video how I do it](https://youtu.be/2U7dJ_QZ3w4)

**Comment by toph-allen** [comment] 2019-03-15 20:30
Yeah — and I tested the theory from my previous comment by creating a totally new host, and that didn't work, so I guess build 91 still doesn't fix the original issue for me.

Launching ssh connections from Spotlight works, but not mosh connections.

**Comment by yury** [comment] 2019-03-15 20:43
That is super strange... but I have an idea.

I understand why ssh works and mosh  doesn't. Mosh command mess up with original command line (It actually inserts \0 (end of the string) char while spliting arguments - 'mosh args` become `mosh\0args`). So  we donating `mosh\0args` string as command line in activity. 

But for now I don't undersand why I can't repro that.

Tomorrow I will try to implement cmd copy other way. But new TF will be only on Monday. Sorry about that.

Thank you for your time.

**Comment by toph-allen** [comment] 2019-03-15 21:23
Good luck finding a workaround! I’ll keep an eye out for a build sometime soon.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by maurizio-manuguerra-mq** [comment] 2019-03-18 06:26
Version 12.8 Build 93 works!
Thanks

**Comment by toph-allen** [comment] 2019-03-18 13:30
Fixed for me too!

**Comment by Harwood** [comment] 2019-03-19 18:41
Works for me as well on 12.8 (93). Thanks @yury!

**Comment by yury** [comment] 2019-03-24 14:00
Closing, feel free to reopen if something is wrong.

**Closed by yury** 2019-03-24 14:00 UTC

**Comment by maurizio-manuguerra-mq** [comment] 2019-06-01 01:35
It worked up to build  97, but it does not work for me in build 99.
No errors or messages are displayed, just the soft keyboard makes a weird up/down dance.

It’s a different kind of problem than before, as both “mosh myconfig” and “ssh myconfig” do not work from shortcuts.

**Comment by Harwood** [comment] 2019-06-09 00:33
I can confirm I’m seeing the same behavior described by @maurizio-manuguerra-mq with build 99.
