### ISSUE TITLE
Font Caching

### ISSUE THREAD

**Issue by mvandermeulen** [blinksh/blink#342] opened 2017-08-20 04:45 UTC
I'm currently using the latest version of Blink on IOS 10.

At the moment I am using a custom font which I have hosted on GitHub and is available [here](https://github.com/mvandermeulen/blinkfont) - the font is Sauce Code Pro and I use it for ZSH, Tmux and Vim.

When I load Blink, whether connected to the internet via Wifi or Cellular initally no font is displayed at all. I can see the cursor is at the same place as where it should be however there is no text displayed before the cursor. If I hit the return key a number of times then a new line is created as usual however none of the lines have text showing.

It takes anywhere from a few seconds to half a minute before all of a sudden the text appears. Often the text does not display correctly on the first attemtp either(for example a massively wide cursor or some other distortion).

I use Blink to SSH to a remote host and open tmux. I use SSH because mosh does not support true colours. Often when loading the Z shell with powerline prompt on the remote host the fonts are not rendered correctly(usually large coloured squares in place of a character). The moment I resume a tmux session which might have 2 panes with 1 of them being VIM the screen rendering is initially all over the place. I takes about 10-20 seconds for the rendering issue to be resolved.

If I wait for about a minute before I SSH into a host then I don't run into any issues at all. Likewise, if I wait a little while before I SSH into a host and then wait another 30 seconds on the host before I resume a tmux session then the screen rendering is fine.

I should note that this issue does not occur when using the built in fonts. It also seems as though my font is being downloaded every time the app is open - I say that because the delay between opening the app and the screen/text being correctly rendered seems to be directly linked to the speed and latency of the current data connection. I'm in Australia so downloading a font from Github in the US is going to take a lot longer from here.

Any chance we can have custom fonts cached?

**Comment by carloscabanero** [comment] 2017-10-03 16:22
Thanks a lot for your report!

The fonts and themes should already be cached the moment we download them.

What device are you using?

**Comment by carloscabanero** [comment] 2018-02-26 13:44
This caused by something else slowing down loading for cached fonts. We now also support installing fonts in the device and showing them within Blink.

Closing!

**Closed by carloscabanero** 2018-02-26 13:44 UTC
Labels: RTT
