### ISSUE TITLE
Ctrl key stops to work until iPadOS restart

### ISSUE THREAD

**Issue by botanicus** [blinksh/blink#843] opened 2019-10-28 16:53 UTC
Every now and then the `Ctrl` key just stops working. I can be working, everything is fine, and then out of the blue I cannot use `Ctrl-l` to go to the last tmux window, in shell I cannot do `Ctrl-a/e` to navigate to the beginning/end of the line etc.

Closing a tab and reopening doesn't fix it. Curiously enough closing Blink through app switcher and opening it again doesn't fix it either – only device restart does.

_That makes me suspect an iPadOS bug, but I have no idea – I'm not an expert on this._

I'm on the latest Blink from TestFlight, but this has been happening for the past 2 weeks at least.

As for iPadOS, I'm on 13.2.

**Comment by curtismchale** [comment] 2019-11-06 17:39
I’m seeing the same issue with `Ctrl` not working. I haven’t been able to reproduce that an iPadOS restart fixes it, because sometimes simply closing the app and killing it from the app switcher fixes it. Then the `Esc` key stops working so I can’t get out of vim.

none of the remapped `Esc` keys (capslock for me) work either, I’m just stuck in Vim. I haven’t found a reliable way to reproduce that and fix it though.

IPadOS 13.2, iPad Pro 12.9, USB-C to hub HDMI->DVI for the external.

**Comment by yury** [comment] 2020-01-06 19:02
Should be ok in Blink v13.1. Feel free to reopen if needed.

**Closed by yury** 2020-01-06 19:02 UTC
Labels: RTT
