### ISSUE TITLE
True colours over Mosh connection

### ISSUE THREAD

**Issue by jamiedumont** [blinksh/blink#231] opened 2017-01-26 15:42 UTC
Hi - before we start - loving Blink!

That said, I've been having some issues with the display of colours inside Neovim (using True Colours) when connecting to my server via Mosh.

Connecting over SSH sees all the colours render as they should, however Mosh is all over the place (almost inverted, and totally illegible, rather than just a bit 'off').

I understand that Mosh itself doesn't support true colours, but a comment in issue #2 seemed to imply that this could be worked around within the terminal as per iTerm's implementation. Has that work around been built yet, or have I found an edge case?

If I can provide any more details to help explain this, please just ask! Cheers.

**Comment by carloscabanero** [comment] 2017-01-26 15:48
Hi Jamie! So that is correct and there is nothing we can do with Mosh not supporting TrueColor. What the iTerm guys suggest in this case is to basically configure the theme, as you can just use any color you want in there. So the color comes from the theme instead of from the application. 

The weird part is that you ssh can render everything correctly, but not with Mosh. There might be something going on there. Would you mind to send me the colors or the theme you are using to take a better look at it? I'm assuming that Mosh on desktop renders just fine, correct?

Thanks!

**Comment by jamiedumont** [comment] 2017-01-26 16:00
I'm using the included Solarized theme for Blink, and [OceanicNext](https://github.com/mhartington/oceanic-next) for Neovim.

> What the iTerm guys suggest in this case is to basically configure the theme, as you can just use any color you want in there. So the color comes from the theme instead of from the application.

Just so I understand, you mean configure my own Blink theme to adjust the colours that are being used?

SSH is fine on both desktop (iTerm) and Blink. However, I hadn't thought to try iTerm and Mosh, but that also has the same issues. I had assumed that it would have been fine based on the "workaround" comment. You know what they say about assumptions...

So, just to clarify, if I play with the colour values of the theme (either iTerm or Blink), I should be able to recreate an approximation of the correct ones?

**Comment by carloscabanero** [comment] 2017-01-26 16:11
Yes, for example that's what I do with my Monokai dark themes. Define the colors from the terminal so that you get to use any you need, and then just let the terminal use the ones they have to. With neovim the problem is that they define a lot more combinations than the normal 16, so you will still be disappointed. 

In any case, it is weird that it doesn't work in Mosh but it does with SSH. It might be a problem with the way Mosh is encoding the values for true color. Would you mind checking what iTerm or Terminal.app do? Also, I saw the theme has an option to just use 256 colors, maybe that does the trick and the approx. is good enough.

**Comment by jamiedumont** [comment] 2017-01-26 16:18
![img_0003](https://cloud.githubusercontent.com/assets/5637895/22339717/db7a16b2-e3e2-11e6-9669-87aa5b1ff05e.PNG)
![img_0004](https://cloud.githubusercontent.com/assets/5637895/22339718/dba86c24-e3e2-11e6-844b-4987608347a6.PNG)

That's the difference I'm getting between Mosh (top) and SSH (bottom), even after creating a theme for Blink.

As you say, falling back to the 256 option within the theme may be my best bet. Worth it to avoid SSH lag!!!

**Comment by carloscabanero** [comment] 2017-02-08 00:10
@jamiedumont closing here as we cannot fix it from our side. We will reopen once it is possible.

**Closed by carloscabanero** 2017-02-08 00:10 UTC

**Comment by wookayin** [comment] 2017-10-01 16:53
A correct reference: mobile-shell/mosh#649

**Comment by carlosvigil** [comment] 2017-11-08 21:57
Is possible now 👍

**Comment by sethyuan** [comment] 2018-03-07 06:48
Any follow ups with the issue? Basically, mosh and neovim can't be used together in the current state.

**Comment by bchallenor** [comment] 2018-03-07 06:51
I don't think there is a Mosh release with the 24-bit color patch yet. I [opened an issue](https://github.com/mobile-shell/mosh/issues/961) about it.

**Comment by drewcovi** [comment] 2018-11-05 06:09
Can this be reopened? The 24 bit support does exist on keithw’s ppa.

**Comment by softinio** [comment] 2018-11-05 20:02
@drewcovi whats Keithw's ppa? 

I thought this fix on server side still not included in an official release. 

Be good to compile it into blink though which I think is what you are referring to as the server side we can install via cloning master and building to get the support.

@carloscabanero what u think?

**Comment by softinio** [comment] 2018-11-05 20:03
Ref: https://github.com/mobile-shell/mosh/issues/945

**Comment by sbromberger** [comment] 2018-11-09 19:38
It's possible to install a mosh-server with 24-bit color support. This works with unix-based mosh clients. However, blink still does not support 24-bit color. It'd be great to have, since (as discussed above) vim doesn't work properly without it.

**Comment by yury** [comment] 2018-11-09 19:41
@stephenhouser can you provide screenshots, so I can test with them?

**Comment by sbromberger** [comment] 2018-11-09 19:56
@yury - if you're looking for a way to see whether 24-bit color is supported, just use [this script](https://raw.githubusercontent.com/JohnMorales/dotfiles/master/colors/24-bit-color.sh).

**Comment by drewcovi** [comment] 2018-11-09 20:29
I can’t say why they’re waiting forever to cut a release.

**Comment by carloscabanero** [comment] 2018-11-09 21:50
They were doing a lot of work on their side, and I don’t think we should take from any point in master. Will ask.

**Comment by drewcovi** [comment] 2019-03-21 16:17
@carloscabanero were you able to follow-up on this? Seems the mosh product is losing some steam and is long overdue for a new release... I've been running an early release on Ubuntu Server and Mac without issue.

**Comment by norcalli** [comment] 2019-07-03 23:57
@carloscabanero can we add it as `mosh-master` or `mosh-experimental` or something? That way the distinction is obvious and people will know it's experimental, and a second binary doesn't break existing solutions. I seriously need this feature because my current setup assumes true color, and it's kind of difficult to change back now.

Also, I've been using mosh master for 3 years without issue, professionally and personally every single day. I keep finding myself looking for an alternate app that does have this because at this point it's infuriating.

**Comment by carloscabanero** [comment] 2019-07-04 02:40
Hi @norcalli! Our just released 12.9 pushes from master. Let us know if you have any issues.

**Comment by norcalli** [comment] 2019-07-10 00:06
@carloscabanero sorry for the late reply, I was travelling. what timing! It works! finally!

**Comment by carloscabanero** [comment] 2019-07-10 00:29
Great news!! Do you have any cool screenshots showing up true color? I would love to tweet them!

**Comment by norcalli** [comment] 2019-07-10 02:14
@carloscabanero the only cool thing I have is Neovim inside tmux with true colors that isn’t illegible https://share.icloud.com/photos/0-GQwNXfHzQjhCOgD3k5i3Lyw

**Comment by ipetkovic** [comment] 2019-10-02 14:25
Is this fix available on iOS app?
I am interested to buy it, but only if true color is supported.

**Comment by yury** [comment] 2019-10-02 14:29
@ipetkovic yep, it is supported. But you have to server build from the master. [See details](https://github.com/blinksh/blink/issues/609)

**Comment by ipetkovic** [comment] 2019-10-02 14:37
Thanks, will try it out then ;-)
