### ISSUE TITLE
typing “- - blah <space>” erases last “h”

### ISSUE THREAD

**Issue by lyosha** [blinksh/blink#689] opened 2019-02-17 18:18 UTC

**Comment by lyosha** [comment] 2019-02-21 03:38
In mosh, that is.

**Comment by yury** [comment] 2019-02-22 12:47
Hi @lyosha,

I can't reproduce. What shell do you have on the server? Bash, zsh or fish?

**Comment by lyosha** [comment] 2019-02-22 17:51
This is:
GNU bash, version 4.4.19(1)-release (x86_64-pc-linux-gnu)
on Ubuntu 18.04.2 LTS. TERM is set to xterm-256color.

If I run vim and enter in insert mode - - blah <Ctrl-V> <Space> I get:

--blah ^?<Space>, where ^? is 127.

Turns out it’s not specific to mosh, I see the same issue in ssh.

I am using PT Mono font I installed locally, though I think it reproduces with other fonts as well.

**Comment by lyosha** [comment] 2019-02-23 02:51
Uh, that was `<minus> <minus> blah <ctrl-v> <space>`

**Comment by lyosha** [comment] 2019-02-26 17:01
It works fine with on-screen keyboard; reproduces with the external keyboard.

I wonder if it’s related to smart dashes or something like that.

**Comment by yury** [comment] 2019-02-26 19:06
Oh, it could be, however we do remove all "smart" things in the code. Let me check

**Comment by yury** [comment] 2019-02-26 19:09
Nope, didn't worked for me. What KB do you have?

**Comment by lyosha** [comment] 2019-06-05 14:36
Sorry for the delay. Still experiencing this. Using Apple’s “smart keyboard folio”.

**Comment by wiremoons** [comment] 2019-07-25 06:54
Hi

I have noticed this happen too. 

1. - Login to a remote linux computer via mosh from blink.
2. - run a command such as:  `nim —version`
3. - when return is press the ‘n’ of ‘version’ get deleted before the command is run

Recalling the command with up arrow, then adding the missing ‘n’ back to the previous command and pressing return—then runs it correctly. So - bit odd!

Appears to happen a lot with `—version` option to commands... I am using an iPad Pro 12.9” with iOS 12.4 (3rd gen iPad Pro version) with the Apple folio keyboard. Shell is bash v 5.0.3(1).
 
Simon

**Comment by yury** [comment] 2019-07-25 07:14
Hi @wiremoons and @lyosha.

I still can't reproduce this issue. Can you post screenshots of 
1. Settings.app -> General -> Keyboard
2. Settings.app -> General -> Keyboard -> Hardware Keyboard
3. Blink.app -> config -> Keyboard.
So I will try with your settings.

Thank you

**Comment by wiremoons** [comment] 2019-07-25 07:59
Hi Yory

Images you requested are attached. Let me know if you need anything further.

Cheers

Simon

![IMG_0380](https://user-images.githubusercontent.com/6184230/61856517-3225d100-aeba-11e9-8a51-08029170d821.png)

![IMG_0381](https://user-images.githubusercontent.com/6184230/61856544-3d78fc80-aeba-11e9-85fc-d6a4b0961196.png)

![IMG_0382](https://user-images.githubusercontent.com/6184230/61856564-48339180-aeba-11e9-92e2-75bbc91661e3.png)

![IMG_0383](https://user-images.githubusercontent.com/6184230/61856579-4ec20900-aeba-11e9-9b4e-fba2e9a0ff0b.png)

![IMG_0384](https://user-images.githubusercontent.com/6184230/61856656-77e29980-aeba-11e9-8b0e-7de3f2ebc0ce.png)

**Comment by wiremoons** [comment] 2019-07-25 08:10
Hi Yury

I have just removed the Apple iPad Pro folio keyboard, and instead connected an Apple Magic Keyboard via Bluetooth. It still has the same issue—so whatever the cause is not specific to the iPad Pro folio keyboard I suspect.

Just thought I would let you know.

Simon

**Comment by wiremoons** [comment] 2019-07-25 08:40
Hi Yury

Sorry for all the messages - just trying to help figure this out.

I have run the same command that drops the ‘n’ (ie `nim —version`) by typing the command in Blink while running `sudo showkey -a`.  The is an extra key being sent `^?` before the carriage return I think?  It is not there if I type other text in and press return—so is this being generated by Blink somehow?  Screen shot below of different outputs to show what I am seeing.

Simon

![IMG_0386](https://user-images.githubusercontent.com/6184230/61859446-0b6a9900-aec0-11e9-8011-3a9f5e152ce1.jpeg)

**Comment by yury** [comment] 2019-07-25 08:41
same thing with `showkey` command in blink?

**Comment by yury** [comment] 2019-07-25 08:43
Still can't reproduce with your settings :(

**Comment by wiremoons** [comment] 2019-07-25 08:45
The screen shot above showing the `showkey` outputs was done from within Blink.

**Comment by yury** [comment] 2019-07-25 08:45
Hmm, I see you run showkey on linux box. But blink have its own showkey command

**Comment by wiremoons** [comment] 2019-07-25 08:52
Ok - didn’t realise was in Blink too :)  
Run in Blink now too - shows extra key there as well. Appears to be to to do with `—` do you think?  

Also (second screenshot below) is captured `showkey` via SSH from within TextTastic app, which doesn’t include the extra key in the output... so guessing Blink is adding it for some reason?

![IMG_0388](https://user-images.githubusercontent.com/6184230/61860313-ab74f200-aec1-11e9-90e1-10248098edb7.jpeg)

![IMG_0387](https://user-images.githubusercontent.com/6184230/61860338-b596f080-aec1-11e9-96b3-531ccf9049f2.png)

**Comment by yury** [comment] 2019-07-25 09:10
I'm trying on 

- 12.9 second gen and iOS 12.4
- 11 iOS 13

still no luck... 

May be you have smth under Settings.app -> General -> Text Replacement?

**Comment by yury** [comment] 2019-07-25 09:12
Also, can you try to turn off 'Auto Repeat'  in Blink.app -> config -> Keyboard

**Comment by wiremoons** [comment] 2019-07-25 10:00
Hi Yury

I have found the cause, at least in my case! 

Under `iOS Settings -> General -> Keyboard -> Text Replacement`  I had a text replacement setup (years ago I think) to replace two dashes ‘- -‘ with an em dash ‘—‘ which I use for writing in iOS text apps. See screenshot below for info.

I have removed this Text Replacement command and now the ‘n’ no longer get chopped of the end of the command (as posted examples) in Blink!  I guess that extra key being seen was iOS trying to replace the text because of the two dashes typed, as I expect it does the replacement at the end of the word or a carriage return.

Anyway - I have removed the Text Replacement and works as expect now, so at least you dont have some weird keyboard bug to find :)  Not sure if @lyosha can confirm if that is the cause there too?

I am also not sure if this is desired behaviour for Blink to pass these Text Replacements into the Blink sessions? Your choice I guess as it might be seen as a feature in some way to other people..? 

Thanks for your help @yury in looking into this anyway, I do appreciate your support and the fantastic Blink applications too :) 

Simon


![IMG_0389](https://user-images.githubusercontent.com/6184230/61865431-1ecf3180-aecb-11e9-8ead-948a1b59469f.jpeg)

**Comment by yury** [comment] 2019-07-25 10:04
For text replacements in blink. We have to support them for some soft keyboards with autocorrection.  
But I'm super glad that you find the root of that.

**Comment by lyosha** [comment] 2019-07-25 14:08
Excellent find! Removing dash-dash to emdash replacement fixed blink for me.

I wonder if blink could add a setting to ignore text replacements.

**Comment by lyosha** [comment] 2019-08-15 14:21
I think this can be closed. Though if somebody has this issue again, how would they find the solution?

**Comment by yury** [comment] 2019-08-15 14:40
I'm closing this issue.

1. Closed issues are searchable too.
2. I will help to solve that issue for any new person :)

**Comment by yury** [comment] 2019-08-15 14:40
Thank you!

**Closed by yury** 2019-08-15 14:40 UTC
