### ISSUE TITLE
iOS 16 Lockdown mode cannot be disabled for Blink

### ISSUE THREAD

**Issue by anttivs** [blinksh/blink#1564] opened 2022-09-13 10:06 UTC
Running Blink on iPhone 13 with iOS 16. Turning the the new Lockdown mode on causes problems with text rendering. According to Apple, it should be possible to turn Lockdown off on a per-application basis, but Blink does not appear in the list that iOS provides under Settings / Privacy and Security / Lockdown Mode / Configure Web Browsing (other apps that are impacted seem to be listed).

I don't know if this an iOS 16 bug or whether there is some other incompatibility with Lockdown mode on the app side.

**Comment by carloscabanero** [comment] 2022-09-29 15:59
Thanks for the report!

It is unclear how we should behave in this scenario. Blink contains a WKWebView that may be limited from loading functionality, but at the same time, Apple seems to provide a way to "enable" those apps if their functionality has been limited, and it doesn't look like we can do much from our side.
`To exclude an app, turn that app off in the menu. Only apps that you have opened since enabling Lockdown Mode and which have limited functionality appear on this list.`

Apple has designed Lockdown mode for "a few individuals" and contemplates that "some some experiences might not be available at all.".

I don't think this is a priority, so we won't be fixing it for now. If someone is really one of those individuals, please contact us.

**Closed as completed by carloscabanero** 2022-09-29 15:59 UTC
Labels: won't fix

**Comment by anttivs** [comment] 2022-09-29 16:02
Yes, I agree with the reasoning, just wanted to clarify for anyone that might find this issue later that Blink did not appear in the allowlist even if it was opened after enabling the mode. Tried twice. Other apps appeared there.

**Comment by yury** [comment] 2022-10-03 14:13
We made fallback to system monospaced font for now. So Blink will be at least usable in that mode. Still investigating...
<img width="1389" alt="Screenshot 2022-10-03 at 17 13 28" src="https://user-images.githubusercontent.com/5250/193599435-9f7c827d-704a-4328-972c-3bf864c21ece.png">

**Comment by orazioedoardo** [comment] 2023-11-02 22:01
> Blink does not appear in the list that iOS provides under Settings / Privacy and Security / Lockdown Mode / Configure Web Browsing (other apps that are impacted seem to be listed).

You (devs) can probably trigger the system to include Blink in that list by loading web content like an html page somewhere in the app, in info/credits for example. Would be useful to whitelist Blink not just for the shell font but also VSCode that’s broken since custom fonts are not loaded and WebAssembly is not available.
