### ISSUE TITLE
Bottom bar in tmux missing in slide over & smallest split view (12.9" iPad)

### ISSUE THREAD

**Issue by solarfl4re** [blinksh/blink#1009] opened 2020-04-28 13:10 UTC
After the latest update, I can't see tmux's bottom bar that shows tabs and the current time when using blink in slide over or the smallest split view. I'm using Blink on a 2017 12.9" iPad Pro.
It's visible in 50/50 split view and fullscreen.

**Not visible**
![Screenshot showing the missing bottom bar in minimized side-view](https://davidlane.io/files/blink-side-view1.png)

**Visible in 50/50 split**
![Screenshot of blink in a 50/50 split on the iPad, with tmux's bottom bar visible](https://davidlane.io/files/blink-tmux-splitview_5050.png)

**Comment by yury** [comment] 2020-04-28 13:41
Interesting, can you share your tmux config? Can't repro (on 11")

**Comment by yury** [comment] 2020-04-28 13:42
Also is this mosh or ssh?

**Comment by javierdemartin** [comment] 2020-07-07 16:02
Closing, can't reproduce the issue. If you find a way to reproduce it please reopen it.

**Closed by javierdemartin** 2020-07-07 16:02 UTC
