### ISSUE TITLE
Option to remap § to esc

### ISSUE THREAD

**Issue by hsleewis** [blinksh/blink#770] opened 2019-07-22 18:00 UTC
Would be awesome for the keyboard folio,..

**Comment by kek** [comment] 2019-08-09 08:45
A workaround is to wrap your shell session in a tmux and then bind § to esc in tmux. I used to do this but then I just dropped it to free § for various application-specific bindings (for example by using it as a prefix key for my often used Emacs commands), and on the few occasions I need to send escape, I press Ctrl-3, which will send the same code as the Escape key would. 

Also if you use Vim I believe it will suffice with `map § <Esc>` and `imap § <Esc>` to make it work just as an Escape key in that particular program. Apart from Vim and to an extent Emacs I have come to realize that the escape key on its own is actually not a very common binding in terminal programs.

**Comment by kek** [comment] 2019-08-09 08:49
Duplicate of #649

**Comment by yury** [comment] 2020-01-06 10:41
With blink v13.1 you can assign custom combo to esc in config->keyboard->custom presses.

**Closed by yury** 2020-01-06 10:41 UTC
Labels: RTT
