### ISSUE TITLE
Text (txt) files are incorrectly associated with Blink

### ISSUE THREAD

**Issue by vectorstorm** [blinksh/blink#533] opened 2018-06-18 08:28 UTC
**Hardware/Software**

- iPad (2018)
- iOS 11.4
- Blink 11.11.1 (app store version)

**Description**
Opening a txt file (e.g., from Files) launches Blink.  The text file is not displayed.

**Reproduce**
Put a txt file somewhere on your device and use the Files application to attempt to view it.

I don't know why Blink would be taking control of opening text files?  Certainly it doesn't seem to do anything with the text file;  Blink just opens and sits at the standard "blink>" prompt.  I've been unable to find any workaround.

(This bug kind of kills blink for me until it's fixed;  as much as I far prefer Blink over all the other ssh tools I've tried on iOS, I do absolutely need to be able to view text files on my iPad.)

**Comment by yury** [comment] 2018-06-18 08:32
It is iOS behavior. You can long press on your txt file, tap share, choose any program you like. Then File.app will open that files in that program.

**Comment by vectorstorm** [comment] 2018-06-18 08:44
What do you mean when you say that it is iOS behaviour to open Blink when the user opens a text file?

Surely it only does it because Blink declares that it can be used to view text files, somewhere in its code?  I can't believe that Apple have chosen to do it for no reason at all.

**Comment by thaurelia** [comment] 2018-06-18 08:54
I'll chime in too, but regarding ZIP files
I want to download ZIP archive from my iCloud to the device to be able to share them over Airdrop later with my laptops (zipped software etc).
Right now, Blink launches instead.

Blink v11.11.1 Jun 2018 (AppStore version)
iOS 11.4
iPad Pro 10.5

**Comment by yury** [comment] 2018-06-18 08:54
I working on the fix. Just let you know workaround for this issue for now.

**Comment by vectorstorm** [comment] 2018-06-18 08:58
Ah, cool.  Thanks, yury!

If the same thing is happening with zip files, then this may be a generic problem that affects a bunch of file types;  perhaps a single fix will fix them all at once.  From a quick search, I also see a similar recent report in [issue 502.](https://github.com/blinksh/blink/issues/502)

**Comment by vectorstorm** [comment] 2018-06-18 09:09
Ah, yeah, I see the problem.  

Blink is registered as a handler for both public.content (the base class under text files, audio files, videos, etc) and public.archive (the base class under zips and other archives), in its Document Types.  That'd be why iOS is trying to open files and archives in it.

(Open up the project file in Xcode, select Blink, switch to the 'Info' tab, under 'Document Types', to see where that's done.  I probably should have tried to track down the issue before reporting it.  I presume you're way ahead of me, yury, but figured I'd post with this just in case not.)

**Comment by yury** [comment] 2018-06-18 09:21
LSHandlerRank: Owner setting is wrong here. 

I will set it to Alternate.

**Comment by yury** [comment] 2018-07-04 07:59
We released 11.26 with the fix.

**Comment by vectorstorm** [comment] 2018-07-04 08:35
Hm..  not working for me.  With a newly installed Blink Shell 11.26, if I tap on a text file in the Files app, it still launches Blink instead of displaying the file.

**Comment by yury** [comment] 2018-07-04 08:37
We removed file associations at all. Must be iOS cache thing.

**Comment by thaurelia** [comment] 2018-07-04 09:09
I uninstalled Blink, confirmed that text and zip files are handled with the Files.app now and then installed new Blink from the AppStore. Unfortunately, I have the same problem as @vectorstorm.

Is there a workaround like removing old / cached file associations which is less radical than resetting the device that may fix this?

**Comment by yury** [comment] 2018-07-04 09:16
@thaurelia can you try to hard reboot device? (long press power and home).

Trying to reproduce with txt files - no luck :(

**Comment by vectorstorm** [comment] 2018-07-04 09:17
I've had a look in Xcode and agree that your change *ought* to have fixed the issue.

But after a hard reboot, I still have the issue.  :/

**Comment by yury** [comment] 2018-07-04 09:23
On my device I had iVim and Blink installed. iVim is associated with txt files. When I deleted iVim and tap on txt files - they opened in file.app (preview). 

My be that is solution. Try to install any app with file association and then delete it. So iOS can fix txt association. Just an idea :)

**Comment by vectorstorm** [comment] 2018-07-04 09:33
After installing, launching, closing, and uninstalling iVim, I still have the same problem.

I should be able to try wiping a device and doing a fresh install on the weekend, to see if that sorts things out.

As a point of interest..  while it's not shown in Xcode's GUI interface, inside Blink/Info.plist in the 'raw' branch (which I assume is where releases are built?), blink has the "UISupportsDocumentBrowser" option set, which I don't believe is appropriate for Blink?  You're also still exporting and importing `public.item` UTIs.  Which shouldn't be an issue, but worth noting that that's still actually there in the Info.plist even though Xcode doesn't show it.

**Comment by yury** [comment] 2018-07-04 09:46
11-stable is release branch. Raw is for next stuff and it is unstable.
`UISupportsDocumentBrowser` is for able to copy files to blink within File.app (File.app -> Location -> On My iPad/iPhone -> Blink). It is useful to scp and etc.

**Comment by thaurelia** [comment] 2018-07-04 09:52
@yury hard reset didn't help. Also, while iVim might fix text file associations, what about other file types, like zip archives I've mentioned? 

I can try erasing device to see if it helps (for science!) but looks to me like the root cause might still be lingering somewhere

**Comment by yury** [comment] 2018-07-04 09:53
Do not reset yet. Still searching for solution :(

**Comment by yury** [comment] 2018-07-04 11:13
Be able to repo with iA TextWriter and text files. After reinstalling it and hard reboot issue persists...

**Comment by yury** [comment] 2018-07-04 11:36
Event deleting Files.app don't help :)

I can write simple app to grab all associations. Just need to compile it and install. Open all files (txt, zip, etc) with it. And then delete it. That would help.

I know @vectorstorm can compile it and install. @thaurelia, can you compile it and install?

**Comment by thaurelia** [comment] 2018-07-04 11:52
I don't follow the purpose completely. App will be associated with every file type – and then, after deleting, Files.app will (theoretically) associate itself with what it was previously associated with?

Anyway, I wouldn't be able to do it right away. I have a vague understanding how app side-loading is performed and need to download Xcode.

**Comment by yury** [comment] 2018-07-04 11:59
Ok,

I was able to reproduce issue with iA Writer associated with all txt files. I tried to delete, reboot. Nothing helped.
Next I installed iVim and open txt file in it. Now iVim is associated with all my txt files.
Next I deleted iVim and Files.app do not open iA Writer anymore it opens it's internal preview.

In your case Blink would be iA Writer. And new app is a tool to grab associations would be like iVim.

**Comment by thaurelia** [comment] 2018-07-04 12:07
Figured that much.

(On a completely unrelated note: how were you able to tie iA Writer to txt files? Mine is not opening .txt/.md from files even when they were created or edited with it).

**Comment by thaurelia** [comment] 2018-07-04 13:19
OK, this just got more weird.

I installed Blink on my iPhone (it has been installed before, so it's not a first time installation).

And “it works™”. No weird file associations, as expected.

Same iOS version (11.4); iPhone 8 if that matters.

**Comment by yury** [comment] 2019-01-11 07:49
We have removed any file association for now. Closing this issue.

**Closed by yury** 2019-01-11 07:49 UTC
