### ISSUE TITLE
Updates not drawn in mosh session, iPad OS 15

### ISSUE THREAD

**Issue by jgrg** [blinksh/blink#1272] opened 2021-09-25 17:14 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

iPad OS 15.0
blink.sh 13.5.14

### Describe the bug

When switching to the app, the mosh session to my server frequently fails to draw updates. My typing still goes to the server, but is not shown on the screen. Force quitting and restarting blink.sh always fixes it, with all the updates being shown. This used to happen a few times a week on iPad OS 14, but now on 15 seems to happen several times a day.

**Comment by yury** [comment] 2021-09-27 06:10
@jgrg we are working on this. Quick workaround is not to close app, but switching tabs. I hope I will fix this today anyway.

**Comment by jgrg** [comment] 2021-09-27 08:58
Ah, so I guess this is happening when iPad OS is closing the app when it's in the background? It is a 9.7" iPad Pro, so only has 2GB RAM.
I'm not closing the app myself. (Unless you mean not leaving the app.)

**Comment by snan** [comment] 2021-10-04 07:33
Switching tabs doesn't seem to redraw it; closing and reopening does.

**Comment by carloscabanero** [comment] 2021-10-04 12:43
@jgrg & @snan, thanks for your reports! Looks like we may have a confusion. Does this happen with the external display? When the "mosh" session hangs, do you still see the previous state or is it just a blank screen?

**Comment by jgrg** [comment] 2021-10-04 13:04
No, I never use an external display or keyboard.
I see the previous state. My typing goes to the session on the server, but the terminal state is frozen.

**Comment by snan** [comment] 2021-10-04 13:58
I see blank screen. I type stuff, still blank. Quit and restart blink, no more blank, and the stuff I did while it was blank is there. Like, I type `ls` into the blank, do the restart, and there's my list of files.

**Comment by yury** [comment] 2021-10-04 15:23
@snan we are working on that blank screen issue. 

Sad news is that bug in UIPageViewController - core of your application. So we need to replace it with custom one.

**Comment by carloscabanero** [comment] 2021-10-08 14:45
This should have been fixed on latest RC on TF. Please let us know.

**Comment by jgrg** [comment] 2021-10-08 15:44
RC = Release Candidate, TF = ?

**Comment by yury** [comment] 2021-10-08 15:48
@jgrg TF == “TestFlight”

**Comment by jgrg** [comment] 2021-10-08 15:53
Ah, yes! I'd need an invite to join Blink beta testing TestFlight, wouldn't I?

**Comment by yury** [comment] 2021-10-08 16:22
@jgrg yes. Mail me (yury.korolev@gmail.com) your Apple ID - I will send you invite.

**Comment by jgrg** [comment] 2021-10-11 10:35
No stuck screen issue with RC4 over the weekend. Since it was happening several times a day, it looks like it is fixed.

**Comment by yury** [comment] 2021-10-11 12:06
Thank you @jgrg. We will push release today to App Store.

**Comment by sgeb** [comment] 2021-10-12 13:34
I had the same issue as described above on an iPad 6th gen (iPadOS 15.0) using an external keyboard. I've tested build 13.90.3 (345) on TestFlight these past days (thanks @yury for the prompt invite). The frequency has definitely decreased -- it used to freeze multiple times per day -- but I still had the issue once.

Maybe it's a different edge case, here's the scenario:

1. Blink on iPad with external keyboard, connected to a linux server via mosh + tmux
2. I issued a git command that required the SSH key password
1. I app-switched to 1Password to copy the SSH key password
1. I switched back to Blink
1. Cursor frozen at the password entry, no more screen refresh, impossible to issue any tmux shortkeys
1. I opened a new Blink tab, created a new mosh connection, entered the same tmux session, could continue where I left off
1. I closed the frozen tab in Blink

**Comment by yury** [comment] 2021-10-12 13:48
Hi @sgeb.

Is this 100% repro scenario? 
If it is not 100% reproducible and you have it again, could you try put app in background and swift to it back again? 

It may be suspended mosh session and not resumed properly.... anyway, I will look. Thanks for report.

**Comment by sgeb** [comment] 2021-10-12 15:51
Hi @yury. No, not 100% reproducible. I just tried a couple of times, and Blink didn't freeze. In the meantime I've updated to build 347 on TF. I'll try your suggestion if the freeze happens again. Thanks!

**Comment by sgeb** [comment] 2021-10-16 16:16
Hi @yury. I just had the issue of blink/mosh UI freezing while key events still went to the session (latest build 14.0.1, 351). Your suggestion worked: I killed Blink, opened it again and the mosh session was automatically restored. HTH. Thanks

**Comment by snan** [comment] 2022-02-15 20:30
I still get frozen blink on v13.5.15.266

**Comment by carloscabanero** [comment] 2022-02-15 20:38
Reopening then. We may need more information though. The former issue was about a bug affecting iOS 15 that we fixed a while ago. Are the frozen screens you experience showing the timeout for Mosh? What is the behavior and does it happen when interacting with specific apps?

Thanks

**Comment by snan** [comment] 2022-02-15 20:49
I'm in Blink either in Emacs or in zsh and it'll freeze (sorta as if I had hit Ctrl-S but I haven't) and doing force quit fixes it. It's often when using an USB keyboard, I think there's some key that triggers it but I haven't figured out which.

I do also sometimes get the blinking blue (or frozen blue) mosh thing, that's more rare.

**Comment by carloscabanero** [comment] 2022-10-24 20:42
Have not experienced this for a while. Closing again but feel free to open a new Issue if this comes back.

**Closed as completed by carloscabanero** 2022-10-24 20:42 UTC
Labels: bug, support, RTT, iOS 15 bug
