### ISSUE TITLE
Crash upon passcode input after cancelling Touch ID

### ISSUE THREAD

**Issue by juneoh** [blinksh/blink#571] opened 2018-10-23 08:41 UTC
Steps to reproduce:
1. With a Touch ID enabled device, turn on lock feature in config.
2. Restart the app, and press cancel on the Touch ID alert. Or just fail Touch ID multiple times with a slippery finger.
3. Input PIN instead.

What happens:
Crashes.

![9222c537-c598-4956-bed3-f62a1f839bb4](https://user-images.githubusercontent.com/18067322/47347718-c88a5380-d6ea-11e8-8a5d-6502b36361db.png)

**Comment by yury** [comment] 2018-10-23 14:00
Hmm, can't reproduce with version from App Store and latest TF.

What version are you using?

**Comment by juneoh** [comment] 2018-10-24 02:32
Currently on 11.26. Latest iOS on iPad Pro 10.5. Using iCloud Sync on, Auto Lock on, keyboard settings default, Smart keys off on external keyboard, and a custom color theme. Happens with and without an external keyboard connected. I wouldn't say the bug is critical to me, as I can just reopen the app and retry with Touch ID. But thanks for looking in.

**Comment by yury** [comment] 2019-01-11 07:59
It should be fixed now.

Thank you.

**Closed by yury** 2019-01-11 07:59 UTC

**Comment by juneoh** [comment] 2019-01-13 01:51
Thank you so much! 50% of my iPad productivity owes to Blinksh.

**Comment by craSH** [comment] 2019-02-07 05:03
Hi there! I think I may be experiencing this same bug, on the current version (12.4) on an iPad with iOS 12.1.3. I had FaceID enabled, and had to disable it recently and currently have a 6-digit passcode in use. Blink opens and presents a **4** (not 6) digit passcode prompt, and after entering any 4 digits, the app crashes.

Let me know if I can provide any further information.
