### ISSUE TITLE
Building and installing blink insufficient permissions.

### ISSUE THREAD

**Issue by TheKasam** [blinksh/blink#362] opened 2017-10-11 02:33 UTC
After extracting package while trying to build Blink I get two errors. I've tried reinstalling my developer profile but it seems like it only allows Carlos's profile. This seems to be a similar issue to issue #184 I have a free account as well.
<img width="550" alt="screen shot 2017-10-10 at 9 32 40 pm" src="https://user-images.githubusercontent.com/12706847/31419662-96e73b84-ae02-11e7-8b3a-8ccca76359b0.png">

**Comment by carloscabanero** [comment] 2017-10-13 16:27
Hi TheKasam! I think that might just be a  problem with your configuration. Just change the bundle id.

There is a lot of people who compile it themselves everyday so this shouldn't be an issue.

**Comment by daylightbrightledlight** [comment] 2017-10-13 22:19
I have a similar issue, but I can't even get a Team. Xcode continually shows "No Team".

**Comment by carloscabanero** [comment] 2017-10-17 22:18
@daylightbrightledlight - that is an issue with Xcode. Unfortunately Xcode is a weird animal sometimes. Have you created yourself a Personal account to select?

@TheKasam did that solve the issue?

I'm closing this as it isn't related to Blink, but we can continue the conversation.

**Closed by carloscabanero** 2017-10-17 22:18 UTC

**Comment by NightMachinary** [comment] 2018-09-02 10:44
@carloscabanero Hey, I have this problem as well, and after some googling, it seems the problem is that this app is using some capabilities that are available only for paid Apple accounts (e.g., remote notifications, iCloud).
Can something be done about this? Like a patch (or branch) to apply to disable these features and compile the project using a free Apple account?

**Comment by carloscabanero** [comment] 2018-09-02 13:53
We can try to have this for a next version. We are now focused on shipping with new ssh, so give us some time to figure this out.

**Comment by NightMachinary** [comment] 2018-09-04 17:07
Sure! Thanks. 💙
