### ISSUE TITLE
Enable wiki on this repo?

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#795] opened 2019-09-06 20:07 UTC
I feel like there’s a good amount of community-driven help done in issues that could be more usefully put in wiki form so it can be referred to by people who may not know how to search for relevant issues (and pointed at in new issues that address the same topics again).

If you enabled the wiki, I would contribute Blink with Emacs and Blink with Tmux pages, as well as taking a hack at describing some of the limitations on Blink imposed by hterm.

**Comment by yury** [comment] 2019-09-07 04:37
Good idea. 
Enabled.

**Comment by yury** [comment] 2020-04-16 15:31
Ok, closing, since wiki is created

**Closed by yury** 2020-04-16 15:31 UTC

**Comment by videoMonkey** [comment] 2020-04-22 16:01
I see a wiki has been created, how does one contribute?
I can’t code, but I have learned a lot about using blink and would love to share what I have learned with others as my way of contributing to the project.

**Comment by yury** [comment] 2020-04-23 14:10
@videoMonkey sorry, we enabled it but not made public. Now you can contribute to it.
Thank you!

**Comment by carloscabanero** [comment] 2020-04-24 17:33
Hi @videoMonkey!! Thanks for offering yourself to help with the docs. I got someone to work on some basic ones, but I'm dropping a list of others which may be interesting but obviously feel free. We are happy to help with any resources you need, meaning cloud machines, shipping you a Pi or whatever for the articles. Get in touch with me at cc at blink.sh.

-  Raspberry Pi
https://www.raspberrypi.org/documentation/remote-access/ssh/ios.md
Installing Mosh on the Raspberry Pi
Connecting to the PI over Bluetooth with the iPad. 
Figuring out the initial IP
There may be already other articles we can link to.
- Distraction free work environment
Mechanical keyboards
External displays
- AWS or DigitalOcean on Blink
Handling PKI. Importing your AWS key to Blink. Copying your Public Key to DigitalOcean
Starting machines and connecting to them.
Creating a host within Blink
- Blink enhancements to improve your productivity
Running within tmux. Copy / Paste for Mosh
Configuring startup commands
Common servers, different users. Test connections (verbose modes)
- Running your machines on a VPN and connecting. TailScale + Blink
- Emacs or Vim like a Pro. How to configure Emacs or Vim on Blink
> Emacs
Usual keyboard combinations on Emacs and how to reproduce them on Blink
External keyboard, Ctrl or Caps and Alt as ESC, Cmd as Ctrl.
On-screen tricks. Continuous presses.
> Vim
Moving within the buffer, auto repeat and special keys.
Color modes?
Usual keyboard combinations on Vim and how to reproduce them on Blink
http://superuser.com/questions/517439/iterm2-vim-cannot-map-alt-key
Esc key
Auto repeat
- Using Blink with a trackpad on iOS13.4.
What is cool.
Setup.
Interacting. Clicks (left and right), scroll.
Configuring tmux. Tip for mouse and Tmux article. Start copy mode on scroll https://davidverhasselt.com/better-mouse-scrolling-in-tmux/
- Mosh vs SSH comparison
- Power shells (zsh or fish) and Powerline fonts.
- Building Blink Shell, more info. (like tricks, etc…)
- Basic UNIX commands roundup

**Comment by videoMonkey** [comment] 2020-04-24 19:37
I do own a raspberry pi and am getting up to speed on tmux. I will do what I can. 

—Jamie sent this from his mobile.
