### ISSUE TITLE
Save state intermitantly; recover after application crash

### ISSUE THREAD

**Issue by io41** [blinksh/blink#340] opened 2017-08-18 10:51 UTC
Occasionally apps crash. Same goes for the OS. Since `mosh` survives connection outages, would it be possible to recover the connections after a cash?

**Comment by goerz** [comment] 2017-08-20 18:39
Duplicate of #59?

**Comment by carloscabanero** [comment] 2017-10-03 16:26
Thanks for the message. Closing here.

**Closed by carloscabanero** 2017-10-03 16:26 UTC
