### ISSUE TITLE
VSCode not showing files

### ISSUE THREAD

**Issue by christianswanepoel** [blinksh/blink#1480] opened 2022-05-20 19:53 UTC
### Configuration
M1 iPad with latest OS, Folio Keyboard

### Describe the bug
I try open vs code from files and get an error. But I had to screen record and go through the recording to be able to see the error. See screenshot

VSCode seems to be frozen or super unresponsive, and the folder content doesn't show.

Screen Grab
https://share.icloud.com/photos/09deqYYr9k3G_3ZL6jBSr1ITQ

Screen Recording
https://share.icloud.com/photos/006wICYuFgibqOMwuxL7LRisA

**Comment by alvarofc** [comment] 2022-05-21 12:04
Had the same problem, do not use aliases that do not match your username. Try this https://github.com/blinksh/blink/issues/1440

**Comment by gabr1elt-arc** [comment] 2022-06-07 16:13
It appears to be a pb with the name of the alias. I solved it using all lowercase alphanumeric chars.

i still get the same error as you on Files.app but seems to work ok otherwise.

#1440

**Comment by carloscabanero** [comment] 2022-10-03 14:11
Closing here as duplicate of #1440. Fixed there.

**Closed as completed by carloscabanero** 2022-10-03 14:11 UTC
Labels: support
