### ISSUE TITLE
Changing fonts has no effect in Blink 14.0.3 running on iPad OS 15.3 Beta

### ISSUE THREAD

**Issue by sheriferson** [blinksh/blink#1351] opened 2022-01-03 08:44 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: 14.0.3
iOS version: iPad OS 15.3 Beta

### Describe the bug

**Observed behavior**

Changing the font in the Appearance has no effect on the font appearing in the app.
Tried force quitting the app and launching it again, changing the chosen font multiple times.

**Expected behavior**

For the font to change.

I can attach screenshots if needed, but all they would show is the exact same font and font size appearing in the terminal no matter what option is chosen in the settings.

**Comment by kleerkoat** [comment] 2022-01-03 20:15
been having this issue since i first installed weeks ago. i think i have a workaround for us. 

- open blink
- open a new terminal window (2 finger tap in terminal"
- switch to new terminal
- make changes to config, you should see you changes
- swipe back to original terminal
- exit terminal

at this point you should only have this one terminal with your changes open. close blink, reopen. it should have kept all your changes and your config is applied. test by opening another terminal. 

it seems to be working here as designed now. 

hope that helps.

**Comment by yury** [comment] 2022-01-04 11:28
@sheriferson we apply new appearance settings only for new terminals for performance and font accuracy measurements. 

So, please set new font/theme, create new tab (2f tap or cmd+t). New theme/font will be applied. Go back to previous terminal and close it with CMD+W.

We may improve that this year bc a lot of people are confused with that behaviour.

**Comment by kleerkoat** [comment] 2022-01-05 00:36
after thinking about it, it makes sense that you have to open a new terminal to see the changes. it's like running source on your profile. i felt pretty dumb when i thought of that.

**Comment by carloscabanero** [comment] 2022-01-12 15:11
I was checking the docs, and we do have a warning on [Customize](https://docs.blink.sh/basics/customize). Will close here then.

**Closed as completed by carloscabanero** 2022-01-12 15:11 UTC
Labels: support

**Comment by sheriferson** [comment] 2022-01-12 18:06
I also just noticed there's a subtle "Configuration will be applied to new terminal sessions" caveat in the Appearance menu. I discovered this because I _was_ going to suggest adding a warning there, and thought to check if it already existed, which it does! So I guess in my rush I had selective blindness to it.

Also I had no idea these docs existed, so I'm looking forward to reading them all because I always suspected I wasn't using blink to its full ability.
