### ISSUE TITLE
Feature Request: Custom colour schema per host

### ISSUE THREAD

**Issue by xpbe0** [blinksh/blink#1038] opened 2020-06-09 08:49 UTC
Host custom colours would help very much navigation between blink screens with open connections (especially on small displays).

assigning a specific theme or background and font colour would be cool:
e.g.:

```
blink screen 1: test server
  white on blue

blink screen 2: prod server
  yellow on black

blink screen 3: app server
  green on black
```

**Comment by xxiii23** [comment] 2021-10-14 18:48
I would like to second this request. I use this with putty and it really helps keep track of things when multiple windows are open.

**Comment by yury** [comment] 2022-12-30 13:55
I'm closing this issue as duplicate of #200.

**Closed by yury** 2022-12-30 13:55 UTC
Labels: Customization
