### ISSUE TITLE
Arrow keys don't cycle previous commands

### ISSUE THREAD

**Issue by 0xCMP** [blinksh/blink#196] opened 2016-12-05 00:27 UTC
When I want to run a previous command using the arrow keys on the iPad Pro Smart Keyboard does not cycle back to the previous command.

**Comment by carloscabanero** [comment] 2016-12-06 03:11
That's weird, what Blink version are you running? Cannot reproduce it :(

**Comment by 0xCMP** [comment] 2016-12-06 04:41
You know what. Today now it's working. It goes in and out. Don't close the issue, I'll keep a closer eye out for it. I couldn't move up and down at all through the history. I'm not sure if I tried quitting

**Comment by fearoffish** [comment] 2016-12-17 18:32
I just had this, the only way I fixed it was by closing blink (swiping up) and starting again.

**Comment by 0xCMP** [comment] 2016-12-17 21:34
@fearoffish is that killing the app or just the session?

**Comment by fearoffish** [comment] 2016-12-18 00:12
I wasn't in a session the last time it happened. So not sure. I just closed the app and swiped up on it in the app switcher.

**Comment by MacDragon** [comment] 2016-12-30 11:34
Had this happen several times aswell, not spotted a pattern, but sometimes history just seems to not work.

**Comment by carloscabanero** [comment] 2017-01-10 15:51
I think I might have it, does it happen after exiting a session? It looks like the terminal doesn't reset the raw mode correctly for linenoise. A hotfix for now for the time being is to use the emacs shortcut Ctrl+p or Ctrl+n.

**Comment by bergie** [comment] 2017-10-04 11:07
@carloscabanero one way I can reproduce this is by opening a MOSH session, then running `killall mosh-server` on the machine I connected to. This drops me back to Blink's shell, but without history on arrow keys.

**Comment by carloscabanero** [comment] 2018-02-26 13:03
This was due to issues with the Raw mode within Blink. It should have been fixed in v10.

**Closed by carloscabanero** 2018-02-26 13:03 UTC
Labels: RTT, bug
