### ISSUE TITLE
Connecting via proxy (ProxyCmd) stopped working

### ISSUE THREAD

**Issue by anjos** [blinksh/blink#1381] opened 2022-02-07 08:46 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink version: v14.0.7.434

iOS version: 15.3

### Describe the bug

I cannot use ProxyCmd or ProxyJump to connect to a remote host through a bastion host anymore - this used to work in previous releases.  The configuration seems correct, however.  Either setting:

ProxyCmd to "ssh -W %h:%p proxy"

or 

ProxyJump to "proxy"

Does not seem to work in my case.  `ssh proxy` works without issues and I can connect to the bastion host, however, I cannot jump through it to a host in the intranet.

A similar configuration with ProxyCmd works well from my macOS Terminal, however, that is using `OpenSSH_8.1p1, LibreSSL 2.7.3` instead.  I also highlight that an identical configuration used to work in the past.

Using `ssh -vvv` does not reveal much (see attached logs).

I expect the proxying to work fine.  Otherwise, I expect debugging output to help me fix the (misconfiguration?) issue.

Here is the output of running `ssh -vvv internal` on the Blink shell (the full name of the "intranet" host has been replaced with internal**********):

```
blink> ssh -vvv internal
Setting up connection callbacks.
Starting connection to internal**********
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_socket_connect_proxycommand: Executing proxycommand 'ssh -W internal***********:22 proxy'
ssh_socket_connect_proxycommand: ProxyCommand connection pipe: [18,19]
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 2
ssh_socket_exception_callback: Socket exception callback: 1 (0)
ssh_socket_exception_callback: Socket error: disconnected
connError(msg: "Session Exception - Socket error: disconnected")
Starting connection to internal***********
ssh_connect: current state : 9
Error connecting to internal. connError(msg: "Socket error: disconnected")
Session deinit
```

**Comment by carloscabanero** [comment] 2022-02-07 16:12
@anjos Confirmed and apologies because I am the one who introduced the bug. Fixed on next.

**Comment by anjos** [comment] 2022-02-11 13:03
OK, @carloscabanero.  Do you have an ETA for this new release?

**Comment by carloscabanero** [comment] 2022-02-11 13:06
Out in a few minutes 👍🏼

**Comment by anjos** [comment] 2022-02-11 13:15
Awesome - thanks for the support.

**Closed as completed** 2022-02-15 20:28 UTC
Labels: support, RTT

**Comment by anjos** [comment] 2022-02-16 07:57
I confirm this is now working for me.
