### ISSUE TITLE
Authentication with puiblic key fails on iOS 14/iPadOS 14

### ISSUE THREAD

**Issue by AlanDecode** [blinksh/blink#1129] opened 2020-10-05 09:00 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

Blink: v13.5.7.244
iOS 14
iPadOS 14

### Describe the bug

Blink always fails to connect remote server with puiblic key authentication, and it will fallback to password authentication. I've confirmed that the key is correct and it works on iPadOS 13.

```
blink> ssh -v ali
socket_callback_connected: Socket connection callback: 1 (0)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
blink: setting socket keepalive: 1
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
blink: using auth methods attempt: 1 of 5
blink: import key id_rsa
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey,password
Password:
```

**Comment by javierdemartin** [comment] 2020-10-05 09:06
@AlanDecode could you please be a bit more specific on what the issue is and describe what's going on? Thanks!

**Comment by AlanDecode** [comment] 2020-10-05 09:11
Sorry, I hit enter key by incident when I create this issue😅.
Details are added as above.

**Comment by javierdemartin** [comment] 2020-10-05 09:12
Could you try using the `-i` flag as in the [docs](https://blink.sh/docs/basics/ssh-keys#establishing-a-connection-using-ssh-keys). We're rewriting core aspects of Blink like SSH to improve these kinds of issues and we'll ship in the coming future.

**Comment by AlanDecode** [comment] 2020-10-05 09:22
Thanks, but the same error occurred:

![15514997-E5B0-438D-8611-D2F0193735EB](https://user-images.githubusercontent.com/28399641/95061886-c9c5b700-072e-11eb-84ca-d20bc7e3ff4a.jpeg)
![65CB1A0F-5FED-4EFB-BC22-6B44DD9457B0](https://user-images.githubusercontent.com/28399641/95061881-c7635d00-072e-11eb-8c6b-b9d8fd69bb55.png)

So it’s a known issue?

**Comment by martingms** [comment] 2020-10-13 09:26
I have the same issue, apart from the second attempt logging `Access denied for 'none'.` instead of `Access denied for 'publickey'.` Both when using `-i id_rsa` and not.

**Comment by javierdemartin** [comment] 2020-10-13 09:35
@martingms  @AlanDecode We're on full speed rewriting how we handle all of this. We'll release a TestFlight whenever we glue all of the parts together and make sure it's not a regression.

**Comment by martingms** [comment] 2020-10-13 10:49
Thanks for the quick reply. What does this mean, is there an ETA? Right now I can't connect to any of my servers, leaving the app kind of useless..

**Comment by javierdemartin** [comment] 2020-10-13 11:44
I know it's a hassle but maybe try to reinstall the app and create a new key and set is as default on the Settings pane and let me know if that works. 

I can't give you both an exact date, we'd love to have a functional beta shipped next week. So yup, soon.

**Comment by javierdemartin** [comment] 2020-10-13 11:46
Linking also issue #1043 for future references.

**Comment by carloscabanero** [comment] 2020-10-13 14:42
Hi @martingms and @AlanDecode , sorry about this issue. Although we are doing changes from our side to support new features, this should still work without issue. I need to ask you a few questions and there are a few workarounds, if you could please get back to us so we can try to track down what may be going on:

- Have you tried logging in with ssh2 command?
- Was this key working before in Blink and all of a sudden stopped? 
- Is this key imported or was it created by Blink?
- How have you uploaded the public key to the server?

Thanks!

**Comment by martingms** [comment] 2020-10-13 14:46
Tried using `ssh2 -v` now, got: `SSHSession:DEBUG:Could not find public key files.`
This has been working, and suddenly stopped working with no change to my servers. I use blink sporadically, so hard to pinpoint exactly when it happened, though. The key was created by Blink.

**Comment by AlanDecode** [comment] 2020-10-13 14:48
* Yes, I've tried `ssh2` and `ssh2 -i`, still doesn't work
* Yes
* It was created by Blink
* Yes

**Comment by AlanDecode** [comment] 2020-10-19 01:29
Hi, thanks for your help. Here are some updates:

1. I tried `ssh -v -i id_rsa ...@...`, didn't work. And there was this error message: `ssh_key_cmp: key types don't match!`
2. I tried to copy private key and then reimport it to Blink, still didn't work.
3. I created a new key on my Mac, and imported it to Blink, it worked. 

Hope these info could be helpful.

**Comment by carloscabanero** [comment] 2020-10-20 20:19
Thanks, this was very useful. Reviewing...

**Comment by yury** [comment] 2020-11-03 07:35
@AlanDecode do you use `geo` command?

**Comment by c0ppelius** [comment] 2020-12-04 03:06
Current setup: iPad Pro 2020 with iPadOS 14.2. Blink v 13.5.9.247. I am attempting to connect to an existing VM instance in Google Cloud with my keys added to OS Login. 

I have attempted: using existing key, newly generated key from my laptop, newly generated key in Blink. Adding these keys to the key list and adding these keys as files. Connecting via a configured host and connecting via `ssh -i user@address`. Nothing connects. With all newly generated keys, I am able to connect on my laptop (Ubuntu 18.04). I have uninstalled and reinstalled Blink. 

I enabled ssh passwords on the instance and am able to connect fine with `ssh user@address` and password authentication, though this is not ideal. (Mosh is also fine.) 

Any thoughts on what else to do? Thanks.

Below is the output of `ssh -vvvvv`
`ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.9p1 Debian-10+deb10u2
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.9 (70900)
ssh_client_select_hostkeys: Order of wanted host keys: "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
ssh_key_cmp: key types don't match!
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_client_select_hostkeys: Algorithms found in known_hosts files: "ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa"
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ssh-dss"
packet_send2: packet: wrote [type=20, len=1004, padding_size=4, comp=999, payload=999]
ssh_send_kex: SSH_MSG_KEXINIT sent
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,zlib@openssh.com,zlib@openssh.com,,
packet_send2: packet: wrote [type=30, len=44, padding_size=6, comp=37, payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
packet_send2: packet: wrote [type=21, len=12, padding_size=10, comp=1, payload=1]
crypt_set_algorithms2: Set input algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC input algorithm to aead-gcm
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_packet_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 196 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
ssh_packet_socket_callback: Processing 180 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 7 [len=160,padding=18,comp=141,payload=141]
ssh_packet_process: Dispatching handler for packet type 7
ssh_packet_ext_info: Received SSH_MSG_EXT_INFO
ssh_packet_ext_info: Follows 1 extensions
ssh_packet_ext_info: Extension: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
ssh_connect: current state : 7
blink: setting socket keepalive: 1
ssh_key_cmp: key types don't match!
packet_send2: packet: wrote [type=5, len=32, padding_size=14, comp=17, payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_packet_socket_callback: packet: read type 6 [len=32,padding=14,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [type=50, len=64, padding_size=12, comp=51, payload=51]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=16,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
blink: using auth methods attempt: 1 of 5
blink: import key another
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
blink: warning: key 'another' duplicate in SE and file system. Using key from SE   
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
packet_send2: packet: wrote [type=50, len=624, padding_size=11, comp=612, payload=612]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=16,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey`

**Comment by c0ppelius** [comment] 2020-12-04 03:36
This appears to be user error (probably). Copying the existing gcloud_compute_engine key from my laptop worked after a reinstall of Blink. My previous successful log in attempts from the laptop might have been mirages as the ssh login's cycled through all my keys including the gcloud one.

**Comment by carloscabanero** [comment] 2022-02-01 17:59
We rebuilt authentication a few versions ago. Not relevant anymore. Closing here.

**Closed by carloscabanero** 2022-02-01 17:59 UTC
Labels: WIP, support, ssh
