### ISSUE TITLE
16.0.3 ssh -i yubikey didn’t work 

### ISSUE THREAD

**Issue by lilarcor** [blinksh/blink#1646] opened 2022-12-04 15:27 UTC
Using the latest TestFlight version. 
ssh -i yubikey root@QWERTY will ask me the password for yubikey instead of authenticating with the physical key.

**Comment by carloscabanero** [comment] 2023-03-23 23:54
If it is asking for password, it is because the public key was not accepted by the server. Closing here as the issue is old and it looks like a configuration problem. Feel free to reopen if you can still replicate.

**Closed as completed by carloscabanero** 2023-03-23 23:54 UTC
Labels: bug

**Comment by carloscabanero** [comment] 2023-09-29 20:25
Opening a Discussion from the content on this thread:

https://github.com/blinksh/blink/discussions/1875
Please please leave your comments there. I need to know that there is real interest to solve this. Otherwise we won't know if it may be worth our time.
