### ISSUE TITLE
Caret stuck below fold on landscape iPhone

### ISSUE THREAD

**Issue by lukebrowell** [blinksh/blink#97] opened 2016-08-18 09:28 UTC
Device: iPhone 6
iOS: 9.3.4
Steps to reproduce:
  1. Open app on iOS
  2. Type 'help' and press enter (to put something in the buffer)
  3. Rotate device to landscape orientation
  4. Try to scroll down to see cursor/caret
Expected outcome:
It should display the row on which the cursor/caret is currently.
It should allow scrolling down to the cursor position and up from it.
Actual outcome:
It does not display the row on which the cursor/caret is currently.
It does not allow the user to scroll down to/from the cursor position.

**Comment by carloscabanero** [comment] 2016-08-18 19:31
Took a lot of care with this. It might be a regression since last version.

**Comment by carloscabanero** [comment] 2016-08-25 15:26
Closing here as Duplicate of #101. Should be fixed today too.

**Closed by carloscabanero** 2016-08-25 15:26 UTC
Labels: bug
