### ISSUE TITLE
Blink looses mosh sessions when not being used

### ISSUE THREAD

**Issue by botanicus** [blinksh/blink#691] opened 2019-02-25 18:40 UTC
Oftentimes when I switch from Blink to other apps, when I get back to Blink, the Blink sessions would be gone, leaving the tabs open, but only displaying `mosh` help in each rather than the actual running session.
![img_0115](https://user-images.githubusercontent.com/6171/53360093-40b39080-38fa-11e9-8597-ba34d308e20e.jpg)

I have to say this is happening all the time and makes it hard to use the app :/ Basically it's killing the utility of `mosh`, since Blink keeps loosing sessions.

And obviously, it leaves much of zombie sessions on the server and I have to kill them manually.

**Comment by yury** [comment] 2019-02-25 18:52
It is can be related to app crash. And it is trying to restore windows, but failed after crash. I will look tomorrow on this too.

**Comment by MakeItGreatAgain** [comment] 2019-04-25 00:36
I've been experiencing this as well - but blinksh actually sends "mosh hostname" to the remote server, which is really annoying especially if you were running a curses app or an IRC client!  When this happens, if you try to reconnect without restarting the app, another weird thing is sometimes the output goes to the wrong blink window.  This seems to have gotten worse in iOS 12.3b - but that might be my imagination.

I'd be happy to test a TestFlight release or try to capture a video of the issue to better explain it. It's difficult though because there is seemingly no way to reliably reproduce the problem.

**Comment by NightMachinary** [comment] 2019-05-15 18:25
My case that happens often is that when I come back to the app, the mosh sessions have turned to blink shells. But sometimes pressing enter repeatedly switches to the mosh session’s prompt! And the prompt keeps going back and forth. The output also switches between going to the local shell or the remote one (the switch actually not being bound to the current visible prompt.)
This issue is clearly a regression since it wasn’t present in earlier versions, and it’s super annoying. It would be nice if this issue was pinned so that a reproduction guide may emerge.

**Comment by yury** [comment] 2019-05-15 18:27
I’m noticed that issue today too, so I was trying to repro that... still no luck. Any repro steps will help a lot.

**Comment by symbiont-wilfred-denton** [comment] 2019-08-24 00:46
I have this problem as well. I think this has to do with how iOS manages memory. Just like sometimes when you go back to safari and it has to reload the page because the memory was cleared sometimes blink's memory is cleared and you have to "reload" your session. Just a guess.

**Comment by NightMachinary** [comment] 2019-08-24 05:31
I have noticed that it helps to wait when switching to blink; Sometimes if
I don’t touch anything the session loads up normally. But if I do touch it,
it no longer loads and resets to the blink shell.

**Comment by yury** [comment] 2019-08-31 18:40
should be fixed in next release

**Comment by yury** [comment] 2019-10-30 06:50
Blink 13 is out.

**Closed by yury** 2019-10-30 06:50 UTC
Labels: RTT
