### ISSUE TITLE
Version 8.0 crash in iPad Pro with iOS 11

### ISSUE THREAD

**Issue by xarubal** [blinksh/blink#350] opened 2017-09-25 18:47 UTC
Hi! When I try to open the keyboard settings, the application fails. Blink version 8.0, iOS 11, iPad Pro 12.9 second generation. I just updated to version 8 from App Store.

**Comment by carloscabanero** [comment] 2017-09-25 18:54
Ugh :( I just reproduced it myself. 

I definitely just broke this version for not pushing it to TestFlight first. I've been using it myself for the last days and everything else was fine. Didn't open Keyboard though.

Sorry, we will come up with a fix today.

**Comment by schroederd** [comment] 2017-09-27 20:38
Is there an ETA on the patch getting uploaded?  I just bought this today for the ability to map the caps lock key to control and I’m excited to actually be able to do that.

**Comment by carloscabanero** [comment] 2017-09-27 21:24
Sorry about that David, definitely not the experience we want to offer here. The new version has already been more than one day on the AppStore waiting for Review. Usually it takes between 1-2 days, but since iOS 11, the last version took 4 days. So they are definitely busy.

If the TestFlight version gets out sooner, I will get you on it.

**Comment by carloscabanero** [comment] 2017-09-27 22:48
Well, that was fast. Just got approved so it should appear on the device very soon.

Closing here!

**Closed by carloscabanero** 2017-09-27 22:48 UTC
