### ISSUE TITLE
Blink create new tabs (ocassionally)

### ISSUE THREAD

**Issue by andrius** [blinksh/blink#327] opened 2017-07-22 12:47 UTC
When I do switch to another application (ipad pro with smart keyboard), blink generates multiple tabs and becoming non-responsive:

![screenshot](https://dl.dropbox.com/s/s7b1xcjvr5pf6eu/Photo%2022-07-2017%2C%2014%2041%2059.png)

**Comment by goerz** [comment] 2017-07-22 20:11
Duplicate of #299

**Comment by carloscabanero** [comment] 2017-10-03 18:22
Closing here, tracking the other one.

**Closed by carloscabanero** 2017-10-03 18:22 UTC
