### ISSUE TITLE
Focus stolen by activity with 2× Blink windows in Split View

### ISSUE THREAD

**Issue by bretmartin** [blinksh/blink#1158] opened 2020-11-18 18:57 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)
  - My apologies if this is actually covered in an existing issue -- I looked for focus issues but none of them quite matched my problem.

### Configuration

Blink 13.5.9.247
iPadOS 14.2

### Describe the bug

I often run 2 Blink windows side-by-side in Split View. Any window activity steals the focus, even if I'm typing in the other window. For example: I'm using a shell on the left and `tail`ing a log file on the right; if a log line appears, focus moves to that window. This can be quite disruptive, obviously. :-)

Let me know if there are any settings you'd like me to provide or toggle or test. Thanks for a great app!

**Comment by larme** [comment] 2020-11-23 06:17
It seems to be similar to https://github.com/blinksh/blink/issues/1147. The focus stealing behavior is very annoying!

**Comment by bretmartin** [comment] 2020-11-25 17:11
@larme Ah, yes, it is similar. I didn't catch that because it's about external displays vs. Split View, but I wouldn't be surprised if the cause and fix are the same.

**Comment by larme** [comment] 2020-11-26 03:16
yep you state the issue more clearly (I'm not a native speaker). I just want to relate 2 issues together so that the blink team may have more cues :)

**Comment by t0d0r** [comment] 2020-12-29 13:18
👍, I faced the same issue running top(1).

**Comment by carloscabanero** [comment] 2021-01-18 14:30
Thanks a lot for your reports. Would you mind sending me a video? I could not replicate this properly, here is mine:

https://user-images.githubusercontent.com/536729/104927696-bb16af00-596f-11eb-9733-8e6600869beb.mov

**Comment by t0d0r** [comment] 2021-01-18 16:47
Hi, I found how to reproduce it:

1. split two blinks windows
2. start top(1) on one of them
3. enable your bluetooth keyboard and focus to the window running top(1)
4. then go back to the window  without top(1)
5. focus will jump on window with top(1)...

I found another issue - when only bluetooth mouse is attached, but no BT keyboard - there is no way to 
enable/show virtual keyboard.

P.S.
I'm using iPad github app to write this reply and did not find a way to upload the video... If you still need it, I will attach it later from my PC, still waiting to be synced.

Regards,
Todor

**Comment by larme** [comment] 2021-01-19 03:33
Yep the stealing is mainly between 2 blink windows.

Here I attached a video showing the focus of external display is stolen by ipad screen's blink running htop.


https://user-images.githubusercontent.com/66847/104984660-21700000-5a4a-11eb-934b-3e4b4d231c00.MOV

**Comment by carloscabanero** [comment] 2021-02-08 01:37
May not be related, but I am seeing now that blink often steals the focus the first time when in split view, but then after going again to the other app the focus is properly handled. @yury touched the focus last time, any idea what may be going on?

**Comment by kimburgess** [comment] 2021-07-25 22:31
This appears to be the cause of a behaviour that has been sending me mad. When running with an external monitor and a tmux session on each the update caused by the clock refreshing in the status bar will bounce focus once every minute.

**Comment by carloscabanero** [comment] 2024-02-13 17:55
Closing here. Should have been fixed and I haven't seen any focus mishaps in a long time.

**Closed by carloscabanero** 2024-02-13 17:55 UTC
Labels: bug
