### ISSUE TITLE
swipe up for dock on ipad causes repeated shortcut keys

### ISSUE THREAD

**Issue by unclespeedo** [blinksh/blink#352] opened 2017-09-28 21:34 UTC
When swiping up to access the dock on an ipad, I find whichever key (on the virtual keyboard) is nearest to my swipe gesture gets stuck (as if I'm holding that key down).

The only way to stop the repeating is to press the key again.

FWIW, I've only tested/experienced this with a physical keyboard.

**Comment by carloscabanero** [comment] 2017-10-03 15:30
Marking as a bug, maybe we can process the events for those buttons in a way that still allows for autorepeat, but do not trigger this behavior. The problem is that we never receive the finger up event, so we need a way to disable it if the application isn’t the first one anymore, or if the finger is just outside the area.

**Comment by carloscabanero** [comment] 2018-02-26 13:43
V10!

**Closed by carloscabanero** 2018-02-26 13:43 UTC
Labels: bug
