### ISSUE TITLE
Keyboard doesn't appear after Touch ID authentication

### ISSUE THREAD

**Issue by xharv14** [blinksh/blink#272] opened 2017-05-05 23:13 UTC
When attempting to unlock Blink with my Touch ID fingerprint, the shell opens up but no keyboard appears. Usually there's a black space at the bottom of the screen to bring up the keyboard, but this doesn't appear when using Touch ID to unlock the application. If you type in a passcode instead (by cancelling Touch ID and then manually entering), the keyboard appears as expected.

**Comment by treyharris** [comment] 2017-05-08 23:26
FYI, I can't reproduce on my 9.7" iPad Pro with the Smark Keyboard disconnected. @xHarv14, what device is this on?

**Comment by xHarv14** [comment] 2017-05-09 03:29
It seems that it only occurs upon occasion (I probably had bad luck when I submitted this issue), but the frequency is seeminly random. I've been playing around to see what might be triggering it, but I've had no success in figuring it out so far.

I've tested and successfully reproduced on both my iPhone 7+ and iPhone 6+ (but it doesn't always happen).

**Comment by xHarv14** [comment] 2017-05-17 18:57
After playing around with the issue.. it seems that it only happens during app startup (startup -> prompt -> shell), but when you minimize the app and then re-open it, the keyboard appears. The opposite may also be true (minimizing the app, and then the keyboard not coming back), but I haven't come across this issue so far.

**Comment by yury** [comment] 2018-02-27 07:56
@xharv14 should be fixed in version 10.

**Closed** 2018-02-27 14:59 UTC
Labels: bug
