### ISSUE TITLE
Caps lock toggles with caps lock mapped to ctrl modifier

### ISSUE THREAD

**Issue by kjstouffer** [blinksh/blink#341] opened 2017-08-20 03:30 UTC
Running into an issue (supposedly fixed in #4, and similarity brought up again in #108 ) where caps lock on an external keyboard is toggled even if mapped to a modifier key. Is this the currently expected behavior?

**Comment by goerz** [comment] 2017-08-20 18:40
Duplicate of #108?

**Comment by carloscabanero** [comment] 2017-10-03 16:25
Unfortunately there is no way within iOS11 to disable Caps Lock from toggling. There is a feature within settings > keyboards called “Disable Caps Lock”, that doesn’t seem to do anything. 

If this changes, we will be able to do something, but I will have to close for now :(

**Closed by carloscabanero** 2017-10-03 16:25 UTC

**Comment by Palleas** [comment] 2017-10-07 22:48
I have the same issue, so I’m trying to train myself to do a double tap on Caps Lock to exit insert mode and stay in lowercase mode. It’s not great but it’s starting to work for me 😀
