### ISSUE TITLE
Yubikey support through USB-C

### ISSUE THREAD

**Issue by jwr** [blinksh/blink#635] opened 2018-11-30 16:50 UTC
On the new iPad Pro, there is a USB-C port. If it exposes HID, it might be possible to support Yubikeys and other similar devices (like smartcards).

On a Mac or Linux, I use the GPG keys stored on a Yubikey for SSH authentication. This is very secure and works well. I would love to use the same setup on an iPad.

Specifically, I'd like to have Blink with a built-in gpg-agent which supports smartcards and yubikeys, to get a setup like this: https://github.com/drduh/YubiKey-Guide

**Comment by yury** [comment] 2018-12-14 10:40
Did research on iOS API and could find anything that gives access to usb flash drive. May be apple can give access to certified partners (works with iPhone).

**Comment by jwr** [comment] 2018-12-14 16:06
Hmm, but why would you need usb flash drive (storage) access? From what I understand, the YubiKey is a HID device, and since third-party USB keyboards work great, perhaps it could be made to work as well.

**Comment by yury** [comment] 2018-12-19 13:34
Hi @jwr,

Yep, totally didn't understand how it works from the start. Sorry.

But they don't ship to Russia :(

<img width="624" alt="screen shot 2018-12-19 at 4 31 48 pm" src="https://user-images.githubusercontent.com/5250/50223318-eb17b080-03ab-11e9-8ecc-75ae7218d344.png">

**Comment by jwr** [comment] 2018-12-19 16:06
Hmm, their website says they have a distributor in Russia: https://www.yubico.com/store/resellers/

**Comment by treyharris** [comment] 2018-12-21 19:10
Just some ancillary info that may be helpful here:

For discussion of the general issue of what the USB-C port makes possible, see [this post](https://www.reddit.com/r/yubikey/comments/9weoty/yubikey_on_new_ipad_pro_with_usba_to_usbc_adapter/?st=JPYE9HWV&sh=af3296bb) on the Yubikey subreddit.

Apparently for OTP, it can work without specific support because it implements the keyboard HID. This should already work for Blink, but is not the kind of usage discussed in the GPG/SSH doc linked in the OP. That usage requires FIDO bidirectional communication.

For its Titan Key suporting U2F, Google makes an iOS app called [Smart Lock](https://itunes.apple.com/us/app/google-smart-lock/id1152066360) — the existence of this app suggests that Apple-blessed apps can access the necessary external resources.

The [Yubikey demo site](https://demo.yubico.com/) will let you test OTP, FIDO and other protocols on various devices. A link that's been hidden a bit points to their [page for testing U2F](
https://demo.yubico.com/u2f).

Hope some of this background helps.

**Comment by yury** [comment] 2019-07-04 06:33
Status update:

I got keys (thanks @carloscabanero). We need special sdk from Yubikey to be able to do smth with them. We send request, but no response yet.

**Comment by ltning** [comment] 2019-07-29 23:16
@yury I don't think you need a special SDK in order to use the OpenPGP card. Plain GnuPG (1 or 2, with 2 preferred) should be able to talk to it. The U2F, OTP, etc. parts are not interesting for SSH key support. Use ykpersonalize on a computer to set it to the correct USB mode, use gnupg to create or load a key. Note that you either have to place the PUBLIC key at some internet-reachable URL and edit the key (gpg --card-edit) to stick that URL on the yubikey itself, OR have a facility to load that public key on the iDevice. The public key DOES NOT automatically follow the YK, only the private key is stored there.

**Comment by jwr** [comment] 2019-07-30 18:05
I could contribute a little money each month to the development of YubiKey+OpenPGP support for Blink. Is there a way to do this?

**Comment by Harwood** [comment] 2019-08-30 02:09
https://www.yubico.com/product/yubikey-5ci

Last week Yubico launched the 5Ci with Lightning and USB-C support.

**Comment by yury** [comment] 2019-08-30 05:54
I have submitted application for SDK once more time.

**Comment by yury** [comment] 2019-09-03 17:41
Current status

![8877D792-E69D-4123-A8B1-6175D3D53038](https://user-images.githubusercontent.com/5250/64195870-2bac5100-ce8b-11e9-8901-df16f8d14e3f.jpeg)

**Comment by jwr** [comment] 2019-09-09 13:02
So, what next? Did you try to appeal? Should we all start writing annoyed E-mails to YubiKey?

**Comment by RyanMorash** [comment] 2019-09-09 21:53
Yubico’s iOS SDK is available at https://github.com/Yubico/yubikit-ios
You just need to contact them to have Apple whitelist the app. 
However it does mention in the FAQ that “ The USB-C type iOS devices, such as the iPad Pro 3rd generation, have limited support when using the YubiKey 5Ci or another type of YubiKey with USB-C connector. The OS is not officially supporting external accessories on these devices.“

**Comment by ltning** [comment] 2019-09-10 05:01
Which yubikey is used is not important. Any of them with openPGP support will work the same way; difference being only that you'll need the lightning-to-usb or c-to-a dongle. So please don't get hung up on the yubikey model - and the sdk is probably not required either. GnuPG with libusb and its plain cud support has all you need. The sdk is probably only needed if libusb isn't permitted - and even then I'm not sure it's useful.

**Comment by mahnouel** [comment] 2019-11-09 16:18
Is this still being looked into?

**Comment by udf2457** [comment] 2019-11-20 23:33
https://www.yubico.com/product/yubikey-5ci .... please please please. 

Thank you. ;-)

**Comment by okdas** [comment] 2019-12-19 17:46
This is an important feature for me.

@yury does access to the YubiKey partner portal provides any value or is necessary? We surely can try to bother them to be heard if the lack of access is the dealbreaker.

Again, thank you for such an amazing product.

**Comment by Fuzen-py** [comment] 2019-12-20 01:52
I would also like to see this, or just gpg key support in general, as this is what I primarily use for SSH

**Comment by jwr** [comment] 2019-12-20 08:44
The upcoming YubiKey 5C NFC makes this even more interesting. Things should start moving faster now that Apple started supporting WebAuthN in iOS 13 and hardware devices like YubiKey should start becoming more popular.

So, is anybody actually working on anything related to Blink with a built-in gpg-agent which supports smartcards and yubikeys?

**Comment by treyharris** [comment] 2019-12-20 21:07
But iPads don’t have NFC at all, do they?

**Comment by jwr** [comment] 2019-12-21 13:22
No, they don't. But they do have a USB-C port, so a YubiKey 5C NFC will work with both an iPad (through USB-C), hopefully for Blink using gpg-agent (and WebAuthN elsewhere), and with an iPhone via NFC for WebAuthN. This is a very compelling 2FA solution.

**Comment by neffs** [comment] 2019-12-21 15:31
USB-C iPads probably don't fully support the Yubikey 5Ci, have a look at the FAQs here: https://github.com/Yubico/yubikit-ios

Full functionality only via Lightning and NFC.

**Comment by udf2457** [comment] 2019-12-27 09:28
> But iPads don’t have NFC at all, do they?

I suppose the idea is that you're not exactly going to be tapping your iPad against a card reader in Starbucks to buy your coffee. ;)

**Comment by yury** [comment] 2019-12-27 10:49
@neffs, I don't know how I missed it.

I need to make some experiments. But with yubikit-ios RAW commands and ObjectivePGP we can add PGP support to our ssh-agent.

**Comment by yury** [comment] 2019-12-27 11:33
Playing with demo app.
- on iPhone 11 - ok
- on iPad PRO 11"
![IMG_2786EA06DECF-1](https://user-images.githubusercontent.com/5250/71515685-b212f580-28b5-11ea-99fb-175604b7eeeb.jpeg)

**Comment by neffs** [comment] 2019-12-27 14:05
Probably easier to just use Yubikit raw directly from libssh2 / ssh-agent. We only need the authentication key. ObjectivePGP doesn‘t support smartcards yet.

**Comment by yury** [comment] 2019-12-27 14:14
@neffs, as far as i'm understanding, I need to convert PGP key to sshkey. Still researching... If you have any good links - please share.

**Comment by carloscabanero** [comment] 2020-01-14 13:49
I’m taking over this. I’ve been working with WebAuthn a lot for the last months and I feel like I can make it.

My goal is to make it work with the standard new Safari implementation, as that would ensure we don’t depend on other frameworks and we actually may support other keys. Only issue is that a message like this (“Blink Shell wants to use “localhost” to sign in”) would appear when you create the key and every time you login with that key. Do you think this may become annoying? I think it should be fine and it helps to get ready for the key and all that.

![51B42111-C390-49C4-B6FD-C9CA920F4875](https://user-images.githubusercontent.com/536729/72349601-cffc9a80-36aa-11ea-8b44-68c0c466a04a.jpeg)

**Comment by jwr** [comment] 2020-01-14 14:19
Well, it would be annoying, but it's definitely better than nothing :-)

In general, anybody who cares about security will have their YubiKey in touch-to-confirm mode, so there is always one interaction when logging in. Additionally, one usually unlocks the key once after inserting it.

The above seems like an additional step, but it's much better than not having anything.

I'm not sure what you mean by "when you create the key" — I am hoping this approach will still let me use the YubiKey in my Mac as well.

**Comment by carloscabanero** [comment] 2020-01-14 16:52
Very good last point, something to discuss too. So there are two ways to implement SSH keys support, already brought up here, one through PKCS#11 (the interface with smart cards) and the other through the new WebAuthn protocol. 

- PKCS#11 would have to be done through OpenPGP agent or similar. This is no small undertaking and even just the instructions to make it work under any distro are convoluted. Libssh may have implemented something but I'm not sure. Additionally, under the covers iOS will limit what solutions we can have, as just "interfacing through USB" won't work. It is a drivers problem, everything that talks through Lightning requires special approval, and through USBC it isn’t even sure it will work as a smart card. It seems like a lot of work for very little and very niche, only Yubikey supports PKCS#11. The only advantage is that you can, effectively, use the same key if you have all the OpenPGP incantations, in all of your machines.

- WebAuthn is my favorite option. The protocol is a lot easier, and there is already a library to make it work with OpenSSH (libfido2). On iOS we can make it work with both Safari in a more generic way, with interfaces over NFC, Lightning, USBC and potentially Bluetooth in the future (we could even support other keys and not just Yubikeys). The problem is that as I understand, using the same key on multiple machines depends on having the public information synchronized between those machines. This is unsolved, but easy to do. We could even help at some point to synchronize hosts and keys in all your devices, including computers.

So that’s the state of things. Feedback is really welcome as I’m deep on this right now.

**Comment by udf2457** [comment] 2020-01-14 17:43
@carloscabanero, I'm afraid I don't follow your argument over PKCS#11 vs WebAuthn.

More specifically, why should WebAuthn enable "other keys and not just Yubikeys" when PKCS#11 does not.

PKCS#11 is as much as an open standard as WebAuthn is ?

I would argue that it would be unwise to simply write-off PKCS#11, esepcially as it is the more established protocol of the two.

**Comment by carloscabanero** [comment] 2020-01-14 17:50
The problem is the part of the communication with the key. It isn't just "USB", and even less if we are talking about iOS. We would have to target the support for Yubikeys using their SDK, so we would be just using that.

PKCS#11 isn't easy to support, even in OpenSSH it has caused many issues and it didn't take off the way it should have. Porting OpenPGP for the agent is also not easy, and add to that the Yubikey part.

WebAuthn is already supported at the OS level, we just need to say "sign me this request", and that's pretty much it. It may be newer, but it is actually already supported in many more places and we could argue if in more hardware too.

**Comment by jwr** [comment] 2020-01-14 18:49
Thanks for explaining the tradeoffs and difficulties. I'm afraid I don't fully understand how the WebAuthn solution works. Does it require installing additional server-side support?

I was hoping the solution described by DrDuh in his guide could be reasonably easily repurposed, but if this is not the case, then I'd much rather go through the trouble of adding additional keys on servers than have nothing. And yes, gpg agent can be flaky and requires restarting sometimes.

**Comment by carloscabanero** [comment] 2020-01-14 22:45
No requirements server-side. WebAuthn just has two operations, "create" a key and "get" (more like a sign) with an authentication token. PKCS#11 is a full interface to abstract the smart cards, allows you to list all the keys, etc... Quite complex.

Reading the DrDuh guide (very cool!), I had another idea. This would be with the only purpose of someone using keys that are already within the Yubikey. Considering we don't need all the compatibility layer that PKCS#11 gives us, as we will have to tap into the Yubikey SDK, we could do another solution more tailored to that scenario. Using the RAW SDK we could potentially list all the keys, and then let you "import" those into Blink. Then just implement the signature part. Sounds simple, but the RAW interface is... raw and with not much docs.

I'm almost done with the WebAuthn solution, so let me finish that and then I can take a deeper look at the intricacies of this other approach.

**Comment by udf2457** [comment] 2020-02-14 11:48
Coming back to this one briefly, OpenSSH 8.2 was released today.   The release notes might contain some interesting ideas https://lists.mindrot.org/pipermail/openssh-unix-announce/2020-February/000138.html

**Comment by haupas** [comment] 2020-06-15 01:51
Any news about this? Would be awesome to use my yubikey in blink

**Comment by martijn** [comment] 2020-06-18 17:45
> Coming back to this one briefly, OpenSSH 8.2 was released today. The release notes might contain some interesting ideas https://lists.mindrot.org/pipermail/openssh-unix-announce/2020-February/000138.html
> 
> Edit: Actually, maybe not as good as it sounds. These new features require server-side 8.2 to work which, let's face it, is not likely to be in place for a few years.

In the meantime Ubuntu 20.04 came out with OpenSSH 8.2 and support for sk-ssh-ed22519 keys so there’s that. The GPG approach never appealed to me, but proper FIDO support (meaning sk- keys) would be great. Too bad that it seems impossible in iPad OS.

**Comment by svanstrom** [comment] 2020-07-10 18:18
Is this getting anywhere towards something that might make it into a release?

**Comment by carloscabanero** [comment] 2020-07-10 18:20
We need to take another look at it because Yubikey didn’t want to help. Will try to prioritize.

**Comment by NerdsvilleCEO** [comment] 2020-07-19 10:31
@carloscabanero https://github.com/Yubico/yubikit-ios

**Comment by rdamron** [comment] 2020-12-08 01:50
Wanted to jump in here and say I'm using sk-ssh-ed22519 keys with great success on bastion hosts. Adding yubikey support for them would be game changing.

**Comment by yury** [comment] 2020-12-08 06:15
@rdamron I have bad news for you. yubikey doesn't work via usb-c on iPadOS for that. It only works for FIDO. sk-ssh works with lightning and NFC on iOS only.

**Comment by rdamron** [comment] 2020-12-08 19:41
@yury Thanks for the update. I suppose NFC on my iPhone would be valuable for an emergency. Maybe iPadOS 15.

**Comment by JoernHe** [comment] 2021-01-18 09:55
@yury even just NFC support would be great. Thank you!

**Comment by rcombs** [comment] 2021-06-28 09:13
Shouldn't it be possible to support this on both iPhone and iPad using USB-C, Lightning, and NFC using OpenSSH's new support for FIDO2 resident keys?

**Comment by rdslw** [comment] 2021-07-04 08:28
@carloscabanero as to the sync part and fido2/webauthn approach, you may consider using "resident" keys, which means there shall be no need to sync any key component between devices. Non-resident keys (fido1/u2f) unfortunately do require synchronization of key parts. 

Also your analysis of PKC#11/OpenPGP looks on the spot for me. It would be hard and probably not even possible due to ipad/ios limitations. It's a pity as majority of ssh with hardware keys usage up to 2020 were done using OpenPGP/PIV approach. That is slowly changing with FIDO2/webauthn and openssh 8.2+. 

In the longterm that (webauthn) would be preferred solution. If you need some help on it, let me know.

**Comment by udf2457** [comment] 2021-07-10 11:43
@rdslw 

Re: "probably not even possible due to ipad/ios limitations"

I'm no iOS developer but not too sure about that,`CryptoTokenKit` is available on iOS 13.0+  (https://developer.apple.com/documentation/CryptoTokenKit)

Also there are manufacturers out there selling smart card readers for iOS (e.g. https://www.microcosm.com/it-security-hardware/smart-card-readers/ios-devices)

And tehre

**Comment by ghost** [comment] 2021-10-08 15:24
Secure ShellFish implements support for pam_yubico (at least via NFC, not sure about Lightning/USB-C), so it's definitely possible. But U2F may be a better solution as it also works on the cheaper Security Key series.

**Comment by carloscabanero** [comment] 2021-10-08 15:27
As far as I remember, the support on Secure Shellfish is just for 2FA, not for keys themselves which is what we were discussing here. An agent is required for that, and I am not sure Shellfish implemented one yet, but I may be wrong.

**Comment by ghost** [comment] 2021-10-08 15:36
Yeah, I use it for 2FA with `AuthenticationMethods publickey,keyboard-interactive:pam`. On my computer this seems to use OTP (emulating a keyboard), although I'm not sure how exactly it works under the hood on my iPhone via NFC as I don't see any simulated keypresses there. If you want YubiKey to be a single factor, couldn't you technically just do `AuthenticationMethods keyboard-interactive:pam` and optionally disable everything other than `pam_yubico.so` in `/etc/pam.d/sshd`?

I suppose using it as an SSH key via PGP or U2F is a cleaner solution for single factor authentication, but it's not the only way.

(I actually have a quite convoluted setup, I do `AuthenticationMethods publickey,publickey publickey,keyboard-interactive:pam`, so on my laptop it uses my regular ed25519 key plus the ed25519-sk key, and on my phone it uses a regular ed25519 key plus pam_yubico since Secure ShellFish doesn't currently support U2F. I find the U2F interaction nicer than OTP as the key flashes when authentication is needed and it seems quicker overall.)

**Comment by carloscabanero** [comment] 2021-10-08 16:41
> couldn't you technically just do AuthenticationMethods keyboard-interactive:pam and optionally disable everything other than pam_yubico.so in /etc/pam.d/sshd?

Unfortunately that is not how it works. We could port the libraries and all that, but the issue is that the device itself is completely ignored by the OS. We have to reimplement everything in compatibility with their SDK. U2F would be the way to go, but that does not properly work at the moment.

There was one way to make everything work, by injecting the JS and making it behave as if it was a webpage trying to get control. But they made it more difficult since iOS14.

**Comment by ghost** [comment] 2021-10-08 16:42
It works fine on an iPhone via NFC in Secure ShellFish. I have no idea about iPads though.

**Comment by yury** [comment] 2022-07-20 12:28
[more info](https://developers.yubico.com/WebAuthn/Supporting_U2F_or_FIDO2_Security_Keys_on_iOS_or_iPadOS/Paths_for_Supporting_U2F_or_FIDO2_Security_Keys.html)

**Comment by RyanMorash** [comment] 2022-07-21 04:00
> [more info](https://developers.yubico.com/WebAuthn/Supporting_U2F_or_FIDO2_Security_Keys_on_iOS_or_iPadOS/Paths_for_Supporting_U2F_or_FIDO2_Security_Keys.html)

From how I read that, Blink would need to implement a `ASWebAuthenticationSession` or `SFSafariViewController` opening a web page that would use WebAuthn to authenticate.

Apple does have an alternative FIDO2 authentication method now, however it mentions the public key needs to be provided by a domain associated with the app (via the associated domains entitlement and with a file hosted on the domain). [Apple Developer documentation](https://developer.apple.com/documentation/authenticationservices/public-private_key_authentication/supporting_security_key_authentication_using_physical_keys)

**Comment by udf2457** [comment] 2022-07-30 15:11
Coming to iOS 16....

> Smart Card support
> iOS 16 and iPadOS 16 will add support for PIV Smart Cards and CCID-compliant readers (this is currently supported in macOS). Administrators should contact the developer of their CCID reader to help ensure the reader can be used in iOS 16 and iPadOS 16 without third-party software.

https://support.apple.com/en-gb/guide/deployment/dep950aed53e/web

**Comment by carloscabanero** [comment] 2022-09-15 15:27
We did it!! 

https://twitter.com/BlinkShell/status/1570427813819486212?s=20&t=UoLIPGrXWsQiTw2lZrhgqA

And we are able to support other keys as well, not just Yubikeys. This is coming to TestFlight this weekend, so we need your help to try different keys and setups!

**Comment by jwr** [comment] 2022-09-15 15:34
This is fantastic news! Thank you very much for the effort, really looking forward to using this!

**Comment by udf2457** [comment] 2022-09-15 16:42
Flippin' genius

**Comment by DarkDimius** [comment] 2022-09-15 21:50
Outstanding. Unclear from the tweet, would there be support for fido2 resident keys as well?

**Comment by carloscabanero** [comment] 2022-09-16 17:03
@DarkDimius I think the answer to that is yes. This is a Webauthn flow, which is an extension to FIDO2. What the resident key does is that the CredentialID itself is the generated & encrypted credential from the key, so it is not really "kept" inside the key itself. All that is handled for you by Blink.

What we do not do at the moment, is to "generate" a Private Key based on the Attested Credential information, that then you could possibly move to other computers and use as well. We are keeping the information though so it may come in the future.

**Comment by carloscabanero** [comment] 2022-09-16 17:04
Just a heads up as I mentioned that this was coming this weekend. We are close to make things work with the Agent and got a bit caught up with it, so we will postpone the launch on TestFlight a few days.

**Comment by DarkDimius** [comment] 2022-09-17 05:56
@carloscabanero , sorry, I'm slightly confused by your answer on if resident keys are supported or not.

Let me ask it differently if you don't mind.
Let's say on my laptop I used `ssh-keygen -t ed25519-sk -O resident` to generate a resident key on my Yubikey series 5 nfc. As far as I know, this does store information about the credential itself on the key, as it can be obtained using `ykman fido credentials list`. The same  information can be used on a differe device via importing the key with `ssd-add -K`.
Would it be possible to use the same key in blink?

**Comment by cweagans** [comment] 2022-09-27 23:28
Is this functionality in the App Store version of blink now? Or is it still pending TestFlight testing?

**Comment by yury** [comment] 2022-09-28 09:54
@cweagans only TestFlight for now.

**Comment by carloscabanero** [comment] 2022-09-28 12:26
@DarkDimius Using a key created somewhere else inside Blink will not be supported at the start. This is related to #1574. We need to know the public key as it is stored on the device, and through WebAuthn atm we only know that when the key is created. I think it is doable, but our resources are very very limited, and this seems like it will be very niche.

**Comment by uajqq** [comment] 2022-10-21 14:25
Using the TestFlight version, I am able to authenticate to my Linux server using both YubiKey and Passkey as options. It throws a bunch of errors but then connects successfully:
```
socket_callback_connected: Socket connection callback: 1 (0)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
ssh_key_type_to_hash: Digest algorithm to be used with key type 15 is not defined
ssh_key_type_to_hash: Digest algorithm to be used with key type 15 is not defined
Connected to ***.***.***.***
ssh_packet_global_request: Invalid SSH_MSG_GLOBAL_REQUEST packet
channel_request: Channel request env failed
```

However, trying to connect to my MacOS 13 (Ventura) system is unsuccessful:
```
socket_callback_connected: Socket connection callback: 1 (0)
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
Error connecting to ***. authFailed(methods: [SSH.AuthAgent])
```

Incidentally, I would also be very interested in support for discoverable PGP keys (like @DarkDimius mentioned), which is the way I connect using desktop. I find it much more convenient than having to keep track of which keys are added to which `authorized_host` files.

**Comment by F30** [comment] 2022-10-24 08:16
> However, trying to connect to my MacOS 13 (Ventura) system is unsuccessful:

Which SSH server are you using on macOS? Afaik, macOS's bundled OpenSSH doesn't support FIDO2, I assume that also applies to the server.

**Comment by carloscabanero** [comment] 2022-10-24 20:40
About macOS, we mention this limitation in the documentation. Our recommended approach is to use OpenSSH from Homebrew, as that one is kept a lot more updated, as a replacement. 

I'm closing here as we consider the main feature has been implemented. Keep in mind these keys are really new and we are the first ones to provide support for them in the wild, which is why we decided to launch them as an Early Access feature. Support may improve in the next months, but I do not think that supporting obscure features limited to Yubikeys will be a way to go for us. It looks like even Git will have support for signatures using this key type.

In any case, for improvements please feel free to open Ideas or Feature requests in [Discussions](https://github.com/blinksh/blink/discussions).

**Closed** 2022-10-24 20:41 UTC
Labels: RTT

**Comment by uajqq** [comment] 2022-11-19 18:07
To anyone who was struggling with this like I was: I had OpenSSH installed from Homebrew and working, but the problem was that the default `sshd` was accepting new SSH connections instead of the Homebrew version. I disabled SSH in system preferences and added a plist in LaunchDaemons to start the Homebrew version of `sshd` instead, and incoming connections can now use Yubikey/passkey/etc.

**Comment by Tahpo2** [comment] 2022-12-19 01:56
> @carloscabanero , sorry, I'm slightly confused by your answer on if resident keys are supported or not.
> 
> Let me ask it differently if you don't mind. Let's say on my laptop I used `ssh-keygen -t ed25519-sk -O resident` to generate a resident key on my Yubikey series 5 nfc. As far as I know, this does store information about the credential itself on the key, as it can be obtained using `ykman fido credentials list`. The same information can be used on a differe device via importing the key with `ssd-add -K`. Would it be possible to use the same key in blink?

I think the terminology “resident key” is discouraged by Yubico, but I will continue using it here. I confirmed that the Blink implementation for security keys does use resident keys. I found a dirty hack which let me use the Blink key on a Linux computer. OpenSSH seems to identify keys by seeing ssh: at the beginning of the key address. If you name your key “name”, then Blink will save it as a resident key with key address “name@blink.sh” or something like that. So name your key “ssh:yubikey” or something similar starting with the “ssh:” string. Then you can use the key on a Linux computer running SSH 8.3 or later after by running “ssh-keygen -K” on the command line and using the resulting identity to access your remote host.

This is almost certainly not intended behavior for either of these applications, so who knows whether it will continue working.

**Comment by uajqq** [comment] 2023-06-25 02:53
> @DarkDimius Using a key created somewhere else inside Blink will not be supported at the start. This is related to #1574. We need to know the public key as it is stored on the device, and through WebAuthn atm we only know that when the key is created. I think it is doable, but our resources are very very limited, and this seems like it will be very niche.

Has there been any progress on this issue? It'd be great to be able to use the PGP key that's already on my YubiKey for SSH through Blink.

**Comment by carloscabanero** [comment] 2023-09-29 20:25
Opening a Discussion from the content on this thread:

https://github.com/blinksh/blink/discussions/1875
Please please leave your comments there. I need to know that there is real interest to solve this. Otherwise we won't know if it may be worth our time.
