### ISSUE TITLE
Crash when trying to copy Private Key iPadOS 14

### ISSUE THREAD

**Issue by neoighodaro** [blinksh/blink#1117] opened 2020-09-16 09:29 UTC
Hey,

Every time I try to copy my private key, the app triggers Face ID but crashes and nothing is copied. The public key works just fine. The share button on the page also just copies the public key, I would expect it to have both, but in the least I should be able to copy the private keys

**Comment by javierdemartin** [comment] 2020-09-16 09:33
I'm testing this on iPad OS 14GM with the latest Blink version from the App Store and it works, copying the private key successfully. 

Tried both the default `id_rsa` and a new one created from scratch.

Is this crashing on an imported key or a key created from inside Blink? Is this happening on the default `id_rsa` key or a new one you could create to test this out?

**Comment by neoighodaro** [comment] 2020-09-16 09:47
One created from Blink and it is only happening on the default. Any one I create now works. But when i try to copy the default, it crashes @javierdemartin

**Comment by javierdemartin** [comment] 2020-09-17 05:38
I am not able to reproduce this crash at all with the latest version in the App Store. I know this is inconvenient but could you try to create a new default key, `id_rsa`, and see if that still happens?

**Comment by carloscabanero** [comment] 2024-01-15 17:31
Closing. I think this may have been because there was no private key anymore if it happened to be from an iCloud backup, etc...

**Closed by carloscabanero** 2024-01-15 17:31 UTC
Labels: support
