### ISSUE TITLE
Unable to exit sessions

### ISSUE THREAD

**Issue by wjr1985** [blinksh/blink#1003] opened 2020-04-25 15:50 UTC
Hello! This seems to have started with the latest Blink update. I seem to have some sessions that are stuck and that I’m unable to exit no matter what. I’ve tried force-quitting Blink, restarting my iPad, and doing everything except uninstall Blink and the sessions still persist. When I type “exit” to exit the sessions, they just hang. I can create new sessions and exit those new ones no problem, it’s just these few that are stuck. I’ve linked a video below to show what I mean. Let me know what else you need to troubleshoot this. Thank you!

[https://billrastello.com/IMG_0105.MP4](http://billrastello.com/IMG_0105.MP4)

**Comment by sbromberger** [comment] 2020-04-25 18:20
FWIW, I've noticed this too in the last 2 TF versions.

**Comment by peterlewis** [comment] 2020-05-08 06:06
Have you been mosh-ing? I’ve had similar issues in the latest TestFlight and these were able to be resolved with the following series of key combinations:

```
1. Ctrl + ^
2. .
3. Ctrl + ^
```


I agree though, a kill command would be jolly useful!

**Comment by bs** [comment] 2020-05-14 06:14
Oh! It took me quite a while to figure this out today. I read the message in Blink and in @peterlewis’ comment as Ctrl + Ctrl. I had to stare at it a bit.

Perhaps another key would be slightly less confusing for a dumb dumb like me?  (I realize this was likely going for clever.)

**Comment by mattgillard** [comment] 2020-05-17 00:34
Have the same issue. In my case the cause is a dropped ssh tunnel. When I try to reestablish the tunnel it causes the session to hang and I need to create a new one...

**Comment by jmeosbn** [comment] 2021-01-05 21:30
I've been noticing this same issue, and fwiw, with a newly started app just typing exit as the first command.

Additionally, I've noticed typing `enter` afterward returns to the shell.

While I'd prefer the restoration of `ctrl-d`, this workaround seems broken somewhat too. 😢

![image](https://user-images.githubusercontent.com/530912/103701012-3904ae80-4f9d-11eb-8caf-461c22a10bee.jpeg)

**Comment by chovyprognos** [comment] 2021-11-18 18:34
How do I get to be blink prompt from tmux? My session is frozen

**Comment by carloscabanero** [comment] 2021-11-18 18:36
You can force exit with Cmd-W or whatever shortcut you may have configured, and also three finger tap and doing close from the menu

**Comment by carloscabanero** [comment] 2021-11-18 18:40
Closing here as there doesn’t seem to be anything to fix anymore. We are already closing the session if we identify it as inactive by the server, and if that doesn’t happen it needs to be force-closed.

**Closed by carloscabanero** 2021-11-18 18:40 UTC
