### ISSUE TITLE
Using clear while inside SSH session makes cursor dissapear

### ISSUE THREAD

**Issue by Alsaezgu** [blinksh/blink#707] opened 2019-03-25 14:39 UTC
Hello Everyone, first poster here.

I’m using blink and i love it.

However, when I SSH into a server and use clear command, the cursor disappears.

I discovered it just goes up by a lot, and using clear again solves it, however, it’s a bit of a pain having to make an alias for double clear in every instance i ssh into.

In case I did something wrong or more info is needed just let me know!
Thank you!

**Comment by yury** [comment] 2019-03-25 14:51
Hmm, can't reproduce that. What server do you use?

**Comment by Alsaezgu** [comment] 2019-03-26 09:43
Do you mean SSH server ? Or OS ?

**Comment by yury** [comment] 2019-03-26 09:50
OS

**Comment by Alsaezgu** [comment] 2019-03-26 10:56
The OS is:
Debian 8.10 Jessie

**Comment by Stevenmqnguyen** [comment] 2020-06-26 16:04
I can reproduce it on iPad Pro 10.5 by using an external keyboard and disable show smart keys with external keyboard. Server is running Ubuntu 18.4. Does not occur when I enable the option.

**Comment by carloscabanero** [comment] 2024-01-15 17:43
Closing as it may not apply anymore. We have a new SSH and still could not replicate. Please re-open in Support if you see this again.

**Closed by carloscabanero** 2024-01-15 17:43 UTC
