### ISSUE TITLE
Mosh corruption when switching back to Blink

### ISSUE THREAD

**Issue by zevlg** [blinksh/blink#484] opened 2018-04-17 08:28 UTC
Got subj almost every time when switching back to Blink. ssh seems to be ok

Here is the demonstration - https://drive.google.com/file/d/1JY1xn7Z5sTS0WlUch4EOp1PFsF-CCRqN/view

**Comment by yury** [comment] 2018-04-18 15:08
@zevlg thanks for feedback.

It seem dupe of ref #485, #437.

On your video and on screenshots from #437 I spotted, that it is look like device was rotated. My initial thought was, that mosh save state was in different orientation.

But I think, I found the original root of this problem. Problem is that iOS try to make snapshot for the app and rotate window in portrait mode for that!

<img width="519" alt="screen shot 2018-04-18 at 6 07 37 pm" src="https://user-images.githubusercontent.com/5250/38940705-8058ffe4-4333-11e8-8c18-8d9960fc96d1.png">

**Comment by yury** [comment] 2018-04-21 10:55
@carloscabanero I implemented simple workaround of rotation issue.

I just remove webview from superview when app becomes inactive. Also I put snapshot on its place.
Main drawback of this approach is preview becomes still. 

We need to test it and see how UX feels.

**Closed** 2018-05-31 14:50 UTC
