### ISSUE TITLE
code command fails to open remote directory

### ISSUE THREAD

**Issue by mazzy89** [blinksh/blink#1440] opened 2022-03-19 18:02 UTC
### Checklist

- [x] Using latest version on the [App Store](http://itunes.apple.com/app/id1156707581)
- [x] Read the [docs](http://blink.sh/docs/)
- [x] Searched for [existing GitHub issues](https://github.com/blinksh/blink/issues)

### Configuration

I have configured a host on my configuration. alias `MiniM1`.
### Describe the bug

 Connecting to it via `ssh MiniM1` it works without issues.
Now I would like to use the `code` CLI to remote into the machine.

I run `code MiniM1:~/git` but I get the error:

```
  98   │ [info] Mar 19 2022, 18:59:00 FileSystem Registered mount 17 for xxx at blinksftp://MiniM1/~/git
  99   │ [info] Mar 19 2022, 18:59:05 CodeWebSocketServer Connection state update - preparing
 100   │ [info] Mar 19 2022, 18:59:05 CodeWebSocketServer Connection state update - ready
 101   │ [debug] Mar 19 2022, 18:59:05 Optional("minim1") stat /~/git
 102   │ [error] Mar 19 2022, 18:59:05 Connection ::1.49787 Error completing operation - connError(msg: "Socket error: No such file or directory")
 103   │ [info] Mar 19 2022, 18:59:20 FileSystem De-registering mount 17
```

The folder `~/git` Is in place in the remote. Also is very weird the way the string is built up. ` /~/git`. I've tried all the combinations even using the full path but I did not find a solution.

but I've found something interesting

running the command

```
scp .blink/blinkCode.log MiniM1:~/git
```
it copies the files into the $HOME dir into the remote machine instead of `~/git`

the directory would be found

**Comment by mazzy89** [comment] 2022-03-19 18:17
my gut feeling tells me that the `scp/sftp` utility from which `code` relies is buggy and the `remotePath` interpolation is wrong. but is it just me having this issue?

**Comment by carloscabanero** [comment] 2022-03-19 18:22
Not right. The SCP/SFTP commands have a different implementation but share the same backend. What you mention with the location is a regression which has been fixed and will be available in next TF.

On the code mapping, is it able to access your home directory or any other folder there? The files.app has a more similar implementation so you may be able to gather better feedback from it.

**Comment by mazzy89** [comment] 2022-03-19 18:27
> will be available in next TF.

would you be able to provide an ETA?

I've tried the mapping in the Files.app but it did not work either.

**Comment by carloscabanero** [comment] 2022-03-19 18:30
Will be out on Monday.

If the Files.app doesn’t work, there may be something more going on with your configuration. I would try to enable LogLevel and check out the logging there. https://docs.blink.sh/advanced/files-app

is that a special folder like a link?

**Comment by mazzy89** [comment] 2022-03-19 18:40
just normal folder in my home dir on the the remote machine.

just to be sure I set correctly the files.app. once I set the folder in the files.app, I can call the command `code` in this way:

```
code MiniM1:<name-folder-file-app>
```

right?

**Comment by carloscabanero** [comment] 2022-03-19 18:41
If you are able to browse in the Files.app, do a long tap and select “code”. It will do the transform and all that for you.

**Comment by mazzy89** [comment] 2022-03-19 19:05
I can access the folder in the files.app but when I try to run with `code` after a long tap I cannot see any files in the VS Code UI.

**Comment by mazzy89** [comment] 2022-03-19 19:35
At this point, I will wait for Monday for the new release and re-test this. Thanks @carloscabanero

**Comment by mazzy89** [comment] 2022-03-21 20:14
Is the new version around to be tested?

**Comment by carloscabanero** [comment] 2022-03-22 15:35
As soon as it gets approved by Apple.

**Comment by mazzy89** [comment] 2022-03-24 10:28
Have been any issues in releasing the latest build 15.0.7, haven't it?
Because I can't still see in the App Store.

**Comment by carloscabanero** [comment] 2022-03-24 16:37
Usually the process is that we release on TF, and then in the AppStore. TF was approved yesterday, we will release on AppStore tomorrow as soon as it gets approved by Apple, and they seem to be slower these days.

**Comment by mazzy89** [comment] 2022-03-30 08:01
Updated with the latest patched version but unfortunately no luck here

```
[info] Mar 30 2022, 09:58:49 CodeWebSocketServer Starting WebSocket...
[info] Mar 30 2022, 09:58:49 FileSystem Registered mount 1 for xxx at blinksftp://fr24.MiniM1/~/git/terraform
[info] Mar 30 2022, 09:58:49 CodeWebSocketServer WebSocket Listener ready
[info] Mar 30 2022, 09:58:51 CodeWebSocketServer Connection state update - preparing
[info] Mar 30 2022, 09:58:51 CodeWebSocketServer Connection state update - ready
[debug] Mar 30 2022, 09:58:51 Optional("fr24.minim1") stat /~/git/terraform
[error] Mar 30 2022, 09:58:51 Connection ::1.51656 Error completing operation - connError(msg: "Socket error: No such file or directory")
[info] Mar 30 2022, 09:59:11 FileSystem De-registering mount 1
```

I have tried both Files.app and via blink cli but I get that issue.

The command works only with Linux systems. The target system is a MacOS and it does not work. There is definitely an issue with the interpolation of the target path.

**Comment by carloscabanero** [comment] 2022-03-30 13:25
From the logs, the path looks good to me. Not sure what you mean by interpolation, am I missing something?

The issue is a connection error, so you are not even getting connected to the remote yet. It is a Socket error throwing a "No such file or directory". Unfortunately that is a standard error description, which in this context may be misunderstood. As you are not connected it means the socket cannot find the remote host. Ie:
```
blink> ssh whateverhostdoesnotexist
Error connecting to whateverhostdoesnotexist. connError(msg: "Socket error: No such file or directory")
```

Can you screenshot your host configuration? Also, you say via Blink CLI you also get that issue, does that mean doing `ssh <host>`?

**Comment by mazzy89** [comment] 2022-03-30 13:29
that’s weird because I can perfectly connect running
```
ssh fr24.MiniM1
```
but I cannot connect when I run

```
code fr24.MiniM1:~/git/terraform
```

For me it’s a path issue. Because it tries to run `stat` againt the path `/~/git/terraform` but this path does not make any sense. The correct path should be `~/git/terraform`. there is that slash at the beginning that ruins things.

**Comment by mazzy89** [comment] 2022-03-30 13:35
I’m able to reproduce the issue. I’ll get back with more data.

**Comment by carloscabanero** [comment] 2022-03-30 13:42
> For me it’s a path issue. Because it tries to run stat againt the path /~/git/terraform but this path does not make any sense. The correct path should be ~/git/terraform. there is that slash at the beginning that ruins things.

No, that is just the representation we do for our logs. The real internal path we use is a b64 of your host with the "root path", which in this case is the ~.

It is a connection issue, 100%. The operation that is trying to start the connection is "stat", but you are not connected yet.

**Comment by mazzy89** [comment] 2022-03-30 13:44
Yes I can confirm that you are right. Apologies for the bad interpreation of the data at my side.
I can replicate the issue on the machine. I;ve tried to login to another MacOS machine and I do not have issue. so need to understand why this exact machine can’t login using the code command but can login using the ssh command.

**Comment by carloscabanero** [comment] 2022-03-30 13:47
You can get more information using the Files.App and the `LogLevel DEBUG` flag at the SSH Config section. The code that is resolving on ssh and any of our sftp variants is the same, so kinda weird that one solves it and the other does not. We may be able to help if you show us your ssh configuration.

**Comment by mazzy89** [comment] 2022-03-30 13:51
Ok i’ve solved the issue.

the issue was that in my ssh config on Blink I add as alias `fr24.MiniM1` and the hostname was `myhostnamefoo.network.home`. in this way it did not work.

when I have changed the alias from `fr24.MiniM1` to `myhostnamefoo` started to work using code.

so it seems that code cannot handle aliases.

**Comment by carloscabanero** [comment] 2022-03-30 14:06
Glad you got it to work. I do access code daily using an alias to an IP, so I don't think aliases are to blame here. I will try to replicate your home route and see if I find something.

**Comment by yaozhenghangma** [comment] 2022-04-12 08:49
I got the same problem when I tried to connect a linux server. 

But the problem is solved, when the value of alias and hostname is same, as mazzy89 said.

The difference is that the scp command work well for me.

**Comment by yaozhenghangma** [comment] 2022-04-12 09:11
It seems that the alias must only contain lowercase. And the problem can be solved.

**Comment by carloscabanero** [comment] 2022-04-18 15:31
Ugh thanks. Someone reported that to me a while ago on Discord and I completely forgot. Will fix that.

**Comment by mcx808** [comment] 2022-04-23 10:55
I just found this thread as I have the same issue. I’m connecting to a Debian 11 machine, hostname & alias are the same and all lowercase. Here’s my blinkcode.log:

```
[info] Apr 23 2022, 11:48:24 CodeWebSocketServer Starting WebSocket...
[info] Apr 23 2022, 11:48:24 CodeWebSocketServer WebSocket Listener ready
[info] Apr 23 2022, 11:49:08 FileSystem Registered mount 5 for xxx at blinksftp://dev-lx/~/Projects
[info] Apr 23 2022, 11:49:20 FileSystem De-registering mount 5
```

**Comment by cblavier** [comment] 2022-05-02 11:31
same issue for me, no error at all but vscode is launched without opening any folder

**Comment by carloscabanero** [comment] 2022-05-02 11:53
Is the BlinkFS extension installed? It looks like it isn’t sending any messages to the socket.

**Comment by cblavier** [comment] 2022-05-02 12:09
Got it, it's solved now. 

What I think caused the issue: 
- I immediately installed blinkFS installed as a first step
- then I signed in with my github account to enable vscode settings synchronization
- my local settings have been overriden (including blinkFS extension)

Thanks for your help 👍

**Comment by mcx808** [comment] 2022-05-02 12:10
> Is the BlinkFS extension installed? It looks like it isn’t sending any messages to the socket.

Ok... so this was the solution I needed; install Blink-FS extension on the remote host.
However that isn't mentioned [in the documentation here](https://docs.blink.sh/advanced/code#code-in-the-cloud), only in the section above it (which I already did on the local blink instance). 

I created a [PR](https://github.com/blinksh/docs/pull/5) on the documentation to clarify this.

**Comment by ktaletsk** [comment] 2022-05-25 17:53
Same issue as well. Blink-FS is installed, but does not open my folder. Is there any way to debug this?

**Comment by gabr1elt-arc** [comment] 2022-06-07 16:17
Solved using only lowercase alphanumeric chars on the alias!!!. Alias does not need to be the same as hostname.

PS. In my case folders did not open at all but files opened after a lot of struggle.

**Comment by palermog** [comment] 2022-06-09 04:16
I had this issue as well, and it was also fixed by changing the alias to be lowercase characters!

**Comment by ljcucc** [comment] 2022-06-19 12:57
I have same problem, but the error message is different this time:

iPad Air 4, Blink Shell 14 (self compile) and 15 (App Store) tried

Command: `code local:~/`

Host: local localhost:22000 (which is hosted on iSH shell) with  SSH key login.

SSH: works

V15: 
```

[info] Jun 19 2022, 20:40:27 FileSystem De-registering mount 2
[info] Jun 19 2022, 20:40:37 FileSystem Registered mount 3 for xxx at blinksftp://local/~/~
[info] Jun 19 2022, 20:40:40 CodeWebSocketServer Connection state update - preparing
[info] Jun 19 2022, 20:40:40 CodeWebSocketServer Connection state update - ready
[error] Jun 19 2022, 20:40:40 Connection ::1.50520 Error completing operation - connError(msg: "Remote channel is closed.")

```

V14:

```

[info] Jun 19 2022, 21:24:52 CodeWebSocketServer Starting WebSocket...
[info] Jun 19 2022, 21:24:52 FileSystem Registered mount 1 for xxx at blinksftp://local/~/~
[info] Jun 19 2022, 21:24:52 CodeWebSocketServer WebSocket Listener ready
[info] Jun 19 2022, 21:24:55 CodeWebSocketServer Connection state update - preparing
[info] Jun 19 2022, 21:24:55 CodeWebSocketServer Connection state update - ready
[debug] Jun 19 2022, 21:24:56 Optional("local") stat /~/~
[error] Jun 19 2022, 21:24:57 Connection ::1.50598 Error completing operation - connError(msg: "Remote channel is closed.")

```

**Comment by carloscabanero** [comment] 2022-10-03 14:10
All of these are fixed on next TestFlight. The main problem was that Code used URLs internally, which are not case-sensitive. We had to do a small refactor to support this.

**Closed as completed** 2022-10-24 20:34 UTC
Labels: bug, RTT

**Comment by devgony** [comment] 2023-01-26 09:26
@mcx808 
So.. how did you install blink-fs on the target host?

**Comment by erikhedin** [comment] 2023-01-26 11:12
@devgony, I think the blink file system extension needs to be installed in VS Code from the extensions menu, not on the remote host. 

That was a little confusing to me as well. 

Could someone confirm that is correct?

Thanks 😀

**Comment by mcx808** [comment] 2023-01-26 11:43
> @mcx808
> So.. how did you install blink-fs on the target host?

I just used regular command `code <host>` which brings up vscode on the remote with no folder open.
Then add the blink-fs extension in this session. Once it's installed you can run `code host:/path` and vscode will open in that location.

**Comment by carloscabanero** [comment] 2023-01-26 13:56
There is a quick tutorial here https://docs.blink.sh/advanced/code

Please send us a PR if you think any of that could be clarified. And if you don't mind, let's move these support questions to Discussions so we can leave this issue closed :)

**Comment by endymion** [comment] 2023-03-13 16:11
After weeks of struggling with trying to get Blink to open files in VS Code for a remote connection, I'm concluding that Blink has some kind of limitation and cannot really connect VS Code to a remote folder over an SSH connection.

The documentation is incredibly vague about how to do it.  'Install Blink-Fs on the target.'  Okay, but how?  Through the VS Code UI, or am I missing some daemon on my workstation?  Various GitHub Issue comments have recommended first connecting to my workstation with no path ("code workstation") and installing the Blink FS extension through VS Code.  Then killing the connection and re-connecting to my specific project folder. ("code workstation:project")  That does not work.  The file explorer in VS Code says "Open Folder", etc.  And if I try then it says, "Opening Local Folders is Unsupported."

If it really is possible to use Blink to run VS Code remotely over SSH then please, someone, please document how to do it.  Is there some secret video tutorial somewhere or something?  Or does this really only work with some specific system like GitHub Codespaces or something?

**Comment by carloscabanero** [comment] 2023-03-13 16:44
This works without issue, there are no limitations. Sorry if it is not clear how to make it work. I will make a quick video as well soon, but let me help you out now.

There is a typo there. It is not “installing blink-fs on the target”, that probably slipped in one of the revisions. Just install Blink-FS in VS Code (do `code .` and after installing Blink-FS, it should show . Make sure you have ssh and stop enabled on the remote. And then just do `code <remote>:~/`

If you want to, join us on Discord or open a Discussion, instead of continue here with a Closed Issue.
Thanks

**Comment by carloscabanero** [comment] 2023-03-13 16:46
Another simple way to test it is using the Files.app integration. If Files.app is able to connect, it means SFTP is working. Long tap in a project and then just go to `Code`. It should auto complete the location for you and does the trick.

**Comment by mcx808** [comment] 2023-03-13 17:10
> This works without issue, there are no limitations. Sorry if it is not clear how to make it work. I will make a quick video as well soon, but let me help you out now.
> 
> There is a typo there. It is not “installing blink-fs on the target”, that probably slipped in one of the revisions. Just install Blink-FS in VS Code (do `code .` and after installing Blink-FS, it should show . Make sure you have ssh and stop enabled on the remote. And then just do `code <remote>:~/`
> 
> If you want to, join us on Discord or open a Discussion, instead of continue here with a Closed Issue. Thanks

Hi @carloscabanero, actually I made the PR to update this text, because it's what I had to do. Install the Blink-FS extension in VSCode on the target machine. Once I did this it worked. However I just ran another test on a new machine and found I did not have to do this. 

**However** I did have to configure the ssh host in `config` and setup a host alias and ssh keys. Then I had to run `code ssh_alias:/path` and it worked. `code user@host:/path` did not. It was a while ago I made the PR so perhaps some more recent update changed the behaviour.

**Comment by carloscabanero** [comment] 2023-03-13 17:28
Hehe, so it looks like the confusion comes from what VS Code we are using. If you are using a VS Code server installed in a remote machine, you need to install Blink-FS in the target server. But if you are using `code .` or `code <host>:<path>`, that will load vscode.dev, and you need to install Blink-FS there. So wherever or whatever VS Code you use, just make sure you have Blink-FS installed in the extension.

I usually assume that people accessing their own VS Code server installations will not use that to access the local or other file systems, they are just interested to access the one in the machine.

I will open a new Issue so we can figure out what the proper guidance for this is.

**Comment by mcx808** [comment] 2023-03-13 17:35
> Hehe, so it looks like the confusion comes from what VS Code we are using. If you are using a VS Code server installed in a remote machine, you need to install Blink-FS in the target server. But if you are using `code .` or `code <host>:<path>`, that will load vscode.dev, and you need to install Blink-FS there. So wherever or whatever VS Code you use, just make sure you have Blink-FS installed in the extension.

Do you mean if I run `code ssh-alias:/path` like I just tested than it creates a tunnel using vscode.dev? I wasn't aware of this, and makes sense since my other server which has code-server installed which prompted me to create the PR for the documentation.

**Comment by carloscabanero** [comment] 2023-03-13 17:46
Yes, that should expose the File System over SFTP. You will not have access to the Terminal as it is VSCode.dev only, but it will go through. If you want to have your own code-server, this is our new “recommended” way https://youtube.com/shorts/2QDsyR0kvo0?feature=share  (using Blink Build or not, the process should be similar)
