### ISSUE TITLE
Having issues with the build.

### ISSUE THREAD

**Issue by rolurq** [blinksh/blink#1622] opened 2022-11-04 10:21 UTC
### Discussed in https://github.com/blinksh/blink/discussions/1620

<div type='discussions-op-text'>

<sup>Originally posted by **rolurq** November  2, 2022</sup>
I was following the build guide and I'm stuck on running `./get_frameworks.sh`, it throws this error
```
error: 'xcfs': Invalid manifest
/Users/.../Projects/blink/xcfs/Package.swift:2:8: error: no such module 'PackageDescription'
import PackageDescription
```</div>

**Comment by carloscabanero** [comment] 2022-11-05 01:38
Closing here as duplicate of already answered Discussion https://github.com/blinksh/blink/discussions/1620

**Closed as completed by carloscabanero** 2022-11-05 01:38 UTC

**Comment by rolurq** [comment] 2022-11-07 09:37
Discussion is not answered. Issue still exists.

**Comment by yury** [comment] 2022-11-07 10:52
Yep, we moved that to discussions, so it more visible to people and may be someone could help.
