### ISSUE TITLE
Odd app hang/crash mode on reactivation

### ISSUE THREAD

**Issue by treyharris** [blinksh/blink#260] opened 2017-03-20 17:53 UTC
I was switching between Blink while doing some coding and Chrome in order to view documentation using ⌘⇥. At one point, I quickly switched from Blink, read a sentence in Chrome, switched back to Blink, immediately thought maybe I'd read it wrong and switched back to Chrome to verify and back to Blink again—maybe 4 apps switches in a second.

On the final switch, I got this:
![img_0074](https://cloud.githubusercontent.com/assets/97895/24113672/e0027584-0d73-11e7-8f29-bbfffb92e156.PNG)

That is, an _all-white_ screen with the SmartKeys bar; my theme is Solarized Dark Higher Contrast and there was text on display. Blink did not appear to respond, so I two-finger-tapped the screen, and got:
![img_0076](https://cloud.githubusercontent.com/assets/97895/24113727/0f8c368c-0d74-11e7-82a8-73eaf57af68e.PNG)

The overlay (appearing to show a bunch of Blink windows at 0x0 size) disappeared in a moment as usual; I could return it with another two-finger tap. But I couldn't get anything else out of the program so I had to force-close it. After re-opening it ran normally and I could not reproduce the issue by quickly flipping again.

**Comment by carloscabanero** [comment] 2017-04-04 15:05
Thanks Trey! This might be one of two things: you either discovered The Matrix and entered in a black hole of terminals within terminals, or maybe an event just got stuck and as memory crashed the terminals couldn't get started. I vote for number one, but I will put a limit on the number of terminals we can create, just in case.

**Comment by bergie** [comment] 2017-10-04 11:04
Seems like dupe of #299

**Comment by carloscabanero** [comment] 2017-10-10 16:33
It is, and it seems like we might actually have a fix, will test on TestFlight

**Closed by carloscabanero** 2017-10-10 16:33 UTC
Labels: bug
