### ISSUE TITLE
mouse scroll in tmux sessions

### ISSUE THREAD

**Issue by saptarshiguha** [blinksh/blink#584] opened 2018-11-02 19:09 UTC
I have `set -g mouse on` in my tmux session. On MacOS this allows me to use my mouse to scroll up and down the tmux window.  On blink i need to use the keyboard to scroll and cannot use the mouse.

Could this feature be added?

**Comment by andrius** [comment] 2018-11-03 06:56
I'll comment on this: mouse actually works, i.e. I can click on tmux and vim tabs. But that's how it react on touches

**Comment by saptarshiguha** [comment] 2018-11-06 19:46
mouse touch to select a tmux tab works. But the scrolling doesn't. I don't know if this is a bug, but would be nice to have.

**Comment by yury** [comment] 2018-11-06 20:22
It is not a bug. It is not implemented yet. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by NyaMisty** [comment] 2018-11-08 04:46
It seems that only mousedown and mouseup are implemented, so can we have the mousescoll event implemented? 
mosh doesn't support scroll back, so the tmux scollback history is quite essential :(

**Comment by saptarshiguha** [comment] 2018-11-08 19:17
Thanks @yury . Willing wait to when you get a chance to implement this. I'm already comfortable with the tmux key controls, this would be a nice to have .

**Comment by botanicus** [comment] 2018-12-18 00:07
I'd love to see this one as well.

If it's not anywhere near on top of the roadmap, I'd at least like the scroll disabled for tmux, because I tend to move it constantly, for instance when I pull down from the top to see the notifications, very often I move my tmux which is rather annoying.

Thank you for all the great work! Blink is my main work tool these days, I do all my coding on there.

**Comment by treyharris** [comment] 2018-12-21 19:13
Can someone please edit this issue so that it reads "tmux" and not "tux"?

**Comment by sdotz** [comment] 2019-02-07 22:27
Would love this feature.

**Comment by yury** [comment] 2019-09-26 06:26
2f pan gesture is terminal wheel now

**Comment by JeremyIglehart** [comment] 2020-01-13 20:51
I'm super excited for this feature.  Every time I see the badge for the App Store I think - "Did they update Blinksh!?" :)

Just wanted you to know that there are some of us out there excited for this feature :)

**Comment by yury** [comment] 2020-01-14 05:39
Hi @JeremyIglehart this feature is implemented in blink v13.0.

Set `set -g mouse on` on tmux config and you will be able to scroll tmux panes with 2f.
Set `set mouse=a` in vim and you will able to scroll in vim too.

Closing this issue. Feel free to reopen if needed.

**Closed by yury** 2020-01-14 05:39 UTC
