### ISSUE TITLE
Mapping CapsLock to Esc not working in vim

### ISSUE THREAD

**Issue by goerz** [blinksh/blink#105] opened 2016-08-28 00:18 UTC
I was assuming that if I map CapsLock to Esc in the Keyboard settings, then when I hit the CapsLock key on the Apple SmartKeyboard while I'm in vim on a remote host, it should take me to normal mode (i.e., send an Esc). It doesn't seem to do that.

**Comment by carloscabanero** [comment] 2016-08-28 00:29
We currently are changing the "modifier", so it is sending the escape sequence. 
What I will do is to implement right below it another section for Key Mappings. In this way, you can map the key "taps" like Caps to ESC, or Ctrl to ESC, etc... While at the same time being able to maintain the modifier, even to a different combination. For example, caps tap can send ESC and long press become a Ctrl modifier.

Related to #85.

**Comment by goerz** [comment] 2016-08-28 00:32
Ah, I see, so if I understand correctly, pressing e.g. "CapsLock + a" will send "Esc + a". But it only works for a key combination, just CapsLock by itself will not send Esc.

**Comment by lukebrowell** [comment] 2016-08-28 07:10
On OSX I sometimes map single tap capslock to esc and caps hold to ctrl so I can use it as a modifier.

**Comment by carloscabanero** [comment] 2016-08-28 16:30
That's exactly what we want to have here ;)





On Sun, Aug 28, 2016 at 3:10 AM -0400, "Luke Browell" <notifications@github.com> wrote:












On OSX I sometimes map single tap capslock to esc and caps hold to ctrl so I can use it as a modifier.

**Comment by carloscabanero** [comment] 2016-08-29 13:29
Will close here as a dupe of #85, as the feature will be implemented there.

**Closed by carloscabanero** 2016-08-29 13:29 UTC
