### ISSUE TITLE
View is not resized when the on-screen keyboard is enabled (with Cross-Fade Transitions disabled)

### ISSUE THREAD

**Issue by mistakenideas** [blinksh/blink#1770] opened 2023-05-06 08:29 UTC
### Configuration

Blink Version: 16.1.7 (747)
iPadOS 16.4.1 (a)

### Describe the bug

When the on-screen keyboard is enabled, the view is not updated to reflect the reduced viewable area, resulting in any content in the bottom of the screen hidden behind the keyboard. The view is updated when the keyboard is disabled or the screen is rotated. Update: The view is also updated and correctly resized when swiping between active shells, so this can also be used as a workaround.

- Launch Blink without an external keyboard
- Using the on-screen keyboard repeatedly enter a command (e.g. help) to fill the screen with text
- Observe how the text is obscured by the on screen keyboard
- Rotate your device
- Again enter a command to fill the screen with text and observe the results 
- Toggle the on-screen keyboard or rotate the device and repeat as needed to observe the inconsistency in behaviour

When the on-screen keyboard is enabled, disabled or the screen rotated the view should update to reflect the new dimensions. 

https://user-images.githubusercontent.com/64734924/236614108-f7ee09eb-42c8-4ff5-b12e-fa0b411ee4bb.mov

**Comment by mistakenideas** [comment] 2023-05-07 18:46
Video of behaviour when swiping between shells

https://user-images.githubusercontent.com/64734924/236696694-9f7dd2c1-239e-4658-86d5-bdd104377b40.mov

**Comment by mistakenideas** [comment] 2023-08-06 15:58
Some additional info, on the recent Beta 16.2.0 (785) there is a workaround for this issue.
- Ensure the view is in the state wanted by following the steps above
- Double tap CMD to bring up the Blink quick actions menu
- Choose to Lock the view
From now on the view is resized correctly when launching, as it used to be in older versions.

Hope this helps.

**Comment by yury** [comment] 2023-08-07 08:05
Hello @mistakenideas 
Why you don't update OS to latest? 

Apple messed up with keyboard detection in 16 but fixed in 16.2, I believe.

**Comment by mistakenideas** [comment] 2023-08-07 08:31
Hi @yury, thanks for the suggestion but I am already running latest. When I originally reported this bug I was on the latest iPadOS version at the time (16.4.1). I am now on 16.6 and the issue is still occurring, so I don’t believe that is the problem. 

I am surprised others aren’t seeing this though, are you not able to reproduce it? Is there any further information I can provide to help get to the bottom of the problem?

**Comment by yury** [comment] 2023-08-07 09:16
@mistakenideas we can't reproduce that yet.
can you try to turn off AssistiveTouch and try without it?

**Comment by mistakenideas** [comment] 2023-08-07 10:13
Thanks @yury that’s really useful to know. Turning off AssistiveTouch didn’t help but I’m obviously missing some detail so will have a think and get back to you.

**Comment by mistakenideas** [comment] 2023-08-07 13:52
I think I’ve tracked it down, your AssistiveTouch suggestion got me thinking and I use some other Accessibility features.  

To reproduce the issue turn on Accessibility->Motion->Reduce Motion and Prefer Cross-Fade Transitions.
Specifically, with Prefer Cross-Fade Transitions off the issue does not occur, with it on it does. 

This explains why the issue is fairly niche. I’ve had these options enabled for some time so assumed a change in Blink (or as you say in iOS) around early May triggered the issue. Hopefully this will help you reproduce the issue and see if there is anything that needs fixing your end. If not I have the Lock workaround described above.

Thanks for your help and suggestions @yury

**Comment by yury** [comment] 2023-08-07 13:59
Thank you for investigation! I will try to repro and fix this.

**Comment by yury** [comment] 2023-08-07 14:01
@mistakenideas yep, can repro now! Debugging...

**Comment by yury** [comment] 2023-08-10 07:29
@mistakenideas I fixed this issue. (It actually uncover our layout manager issue).
Can I send you custom build TF to try?

**Comment by mistakenideas** [comment] 2023-08-10 09:04
@yury Great, glad the report helped. Sure, I’m happy to test the change, what’s the best way to do that?

**Comment by yury** [comment] 2023-08-10 09:08
@mistakenideas  email me (yury at blink.sh) from email account you use in TestFlight

**Comment by smorkin** [comment] 2023-08-11 11:41
Just want to say I'm seeing the same thing without having that setting ON, so it can happen in other cases as well (I'm compiling the app from code, having tried both _16cleanup_ and _snippets_ branches). Or at least I hope it is the same bug I'm seeing, and that your fix will fix it.

**Comment by yury** [comment] 2023-08-16 10:25
@smorkin can you try `ios-17` branch?

**Comment by smorkin** [comment] 2023-08-16 11:20
The ios-17 branch successfully fixes this issue; thanks!

Small footnote: I noticed that #1747 is still relevant on this branch, whereas it was fixed in the _snippets_ branch. And #1819 is present; understandable, since I don't think it's been fixed anywhere yet (as mentioned in that case, I do have a code fix but I'm not sure it is good enough for a pull request).

**Comment by yury** [comment] 2023-08-16 12:02
@smorkin  for #1747,  you need update submodules when you switching branches.

**Comment by smorkin** [comment] 2023-08-17 13:19
@yury I'm pretty sure I did that, but I might have been mistaken, for sure!

**Comment by yury** [comment] 2023-08-17 13:59
@smorkin my bad. Pushed fix.

**Comment by mistakenideas** [comment] 2023-08-17 15:49
I’ve been testing the build @yury gave me for a few days now and the fix seems solid. Thanks @yury!

**Comment by smorkin** [comment] 2023-08-17 20:14
@yury Got it, and I'll try it out next build I do; thanks for your work!

**Closed as completed** 2023-09-04 13:39 UTC
Labels: bug
