### ISSUE TITLE
Closing 1st tab crashes the app (v12)

### ISSUE THREAD

**Issue by kurko** [blinksh/blink#602] opened 2018-11-08 20:42 UTC
Blink: v12.1.43. Nov 2 2018

When you have multiple tabs open, closing the 1st one (Ctrl+w w external keyb) crashes the app. I can reproduce it every time.

**Comment by yury** [comment] 2018-11-08 20:44
Hi @kurko,

I can't reproduce it so easily. Do use ssh or mosh in tabs? how many of them? Can you record a shot video?

**Comment by kurko** [comment] 2018-11-08 20:49
@yury new piece of information: it only occurs when you executed `mosh MYSERVER` on that 1st tab. 

Steps to reproduce:

1. open mosh
2. ctrl+t to open a 2nd tab
3. cmd+shift+[ to go to 1st tab
4. type `mosh myserver` and hit Enter
5. while it's still loading, ctrl+w (focused on 1st tab)

It crashes. 

I found it while experiencing this 
https://github.com/blinksh/blink/issues/601 because the `mosh` command hangs forever, so ctrl+w always crashes.

**Comment by yury** [comment] 2018-11-08 20:56
Still can't reproduce that. Will look on #601 first

**Comment by botanicus** [comment] 2019-02-07 02:15
For me closing any tab results in a crash pretty much every time (or possibly every single time).

It only started recently.

I run `mosh` in all the tabs. I usually have 2 or 3 tabs. I have Blink from the App Store.

**Comment by botanicus** [comment] 2019-02-25 18:17
@yury here's a video of the crash 
https://www.dropbox.com/s/xlmvltpeifmotpr/ScreenRecording_02-25-2019%2009-44-28.MP4?dl=0

**Comment by yury** [comment] 2019-02-25 18:20
@botanicus thank you. Got it reproduced. Will fix tomorrow.

**Comment by botanicus** [comment] 2019-03-06 14:27
@yury is it fixed?

By can I get a TestFlight invite? I'd gladly use the test version.

**Comment by yury** [comment] 2019-03-06 19:30
@botanicus I can't crash it anymore.

Send me a message to yury.korolev@gmail.com ( I will send you ivite).
But v12.7 got reviewed by Apple already. So we will be releasing it today or so.

**Comment by yury** [comment] 2019-03-09 12:04
Fixed in v12.7

I will close this issue. Feel free to reopen if it is not fixed for you.

Thank you.

**Closed by yury** 2019-03-09 12:04 UTC
