### ISSUE TITLE
Stuck (repeating) keys when switching back to Blink

### ISSUE THREAD

**Issue by bchallenor** [blinksh/blink#398] opened 2017-11-26 11:09 UTC
Often when I switch back to the Blink app, there is a stuck key, so my terminal fills with e.g. `***`... or `{{{`...

I suspect it has something to do with the smart keys bar, because even though I am using the iPad Pro smart keyboard, and I have the option “Show with external keyboard” disabled, the smart keys sometimes appear for me anyway - and if a key is repeating and I press one of the buttons in the smart key bar, the key unsticks (stops repeating). Also, the stuck key always seems to be one of the special keys in the smart keys bar (i.e. `*`, `{`, etc).

(Perhaps the fact that “Show with external keyboard” is not respected deserves its own issue?)

**Comment by ahmadseleem** [comment] 2017-12-01 07:07
Disable smart keys.
The problem is that when you swip up to go control center you have to swip over one of the smart keys. so that's why it keeps repeating.

**Comment by bchallenor** [comment] 2017-12-01 07:17
That makes sense - but I do have “Show with external keyboard” disabled already, so I don’t expect to see the smart keys in the first place. They just show up occasionally. I haven’t worked out exactly what causes them to appear.

**Comment by nullicorn** [comment] 2017-12-05 18:30
@bchallenor I have the same problem. I have Smart keys “Show with external keyboard” disabled, but when switching to Blink from another app in split view, the smart keys show up almost always. Occasionally it causes the key repeating as well.

**Comment by carloscabanero** [comment] 2017-12-18 20:06
SmartKeys sometimes show while in SplitView. Should be an easy fix.

**Comment by bchallenor** [comment] 2018-01-10 12:20
Yes, good spot that it involves split view. I've been avoiding split view since you mentioned it and have not seen the bug without it.

**Comment by carloscabanero** [comment] 2018-02-16 20:59
Fixed on 10! Closing...

**Closed by carloscabanero** 2018-02-16 20:59 UTC
Labels: RTT, bug
