### ISSUE TITLE
Cannot use Blink since ios 15 update 

### ISSUE THREAD

**Issue by fortressofsolitude** [blinksh/blink#1274] opened 2021-09-27 23:16 UTC
Hi 

I've been a happy Blink user. It seems that coinciding with either the ios15 release or a recent Blink update (they both occurred around the same time to me) I can no longer mosh or ssh. 

A mosh to a saved host yields:

Did not find remote IP address
blink> 

Pinging the host within Blink does get the correct IP address. 

Using ssh just gives a pause then drops back to the blink prompt. 

I looked on discord and also tried uninstalling and reinstalling Blink and the same issue prevails. It is the same on both iPhone and ipad. I use mosh all the time with several hosts and different computers so I know the hosts are presently working normally; is an issue with Blink. 

Not sure if you are aware of the issue?

Regards 
David

**Comment by enquora** [comment] 2021-09-28 00:07
The Deployment target needs to be updated from 1OS 14.3 to iOS 15.0

**Comment by carloscabanero** [comment] 2021-09-28 12:37
Hi @fortressofsolitude, can you send us more information about what version you are running? We currently only have one known issue that will be solved soon: when switching back and forth eventually you may get a blank screen.

**Comment by edjroz** [comment] 2021-09-28 19:34
I just started using blink, I'm experiencing this as described on version 13.5.14

trying to ssh, will only go back to blink

and trying to mosh won't find the ip

![image](https://user-images.githubusercontent.com/14135788/135153913-f72a2c63-5a2b-40da-b119-e22b9d259356.png)

I've also tried using the IP directly in case I may have put wrong the IP address on the hostname

**Comment by carloscabanero** [comment] 2021-09-28 19:51
The blank exit was a known issue that we fixed on TestFlight. We are cutting down our plans to release that version asap, but while that happens, let me try to help.

Usually that is due to authentication issues. You can see a better output doing ssh -vvvv root@dev. Usually this happens with key based authentication. Have you generated a proper key and installed it on server? Can you see that key being used in the more verbose output?

If that doesn't help, please feel free to send us the dump from -vvvv and I will try to offer more help.

**Comment by fortressofsolitude** [comment] 2021-09-28 22:04
Hello

iOS = 15.0
Blink = v13.5.14.264

Attached are screen shots. 

Blink0.PNG - this host has been set up in Blink and working for months until iOS15+latest Blink
Blink1.PNG - demonstrates that the resolved IP address for the host is listening (telnet), that a plain ssh just returns to the prompt with no error, and a mosh gets the "Did not find remote IP address" error.
Blink2.PNG - is the tail of the result of ssh -vvv skynet.aus1.net. The key is of course stored in the config Keys section and was working before the upgrade.

Thank you for looking at the issue. :-)

Blink0.png:
![blink0](https://user-images.githubusercontent.com/10265886/135172203-5c8c2435-a172-4c15-95d8-7e8c77b1511c.PNG)

Blink1.png:
![blink1](https://user-images.githubusercontent.com/10265886/135172229-2db8c219-1b33-41f2-aaba-863fbd56ca3a.PNG)

Blink2.png:
![blink2](https://user-images.githubusercontent.com/10265886/135172260-fbd9d06c-19e4-4bbf-873a-03fc101210d8.PNG)


> On 28 Sep 2021, at 22:37, carloscabanero ***@***.***> wrote:
> 
> 
> Hi @fortressofsolitude <https://github.com/fortressofsolitude>, can you send us more information about what version you are running? We currently only have one known issue that will be solved s
oon: when switching back and forth eventually you may get a blank screen.

**Comment by tobiasps** [comment] 2021-09-28 22:44
I’m also having issues with my hosts using key auth. I’m on version v13.5.14.264 on iOS15 on an iPhone 13 Pro. I recently switched phone and migrated from the old phone including the blink configuration.

SSH with key auth to same server from my macOS computer works.

Here’s the debug output:
```
blink> ssh -vvvv dev
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_7.6p1 Ubuntu-4ubuntu0.5
ssh_analyze_banner: We are talking to an OpenSSH client version: 7.6 (70600)
ssh_client_select_hostkeys: Order of wanted host keys: "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_client_select_hostkeys: Algorithms found in known_hosts files: "ecdsa-sha2-nistp256"
ssh_client_select_hostkeys: Changing host key method to "ecdsa-sha2-nistp256,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
packet_send2: packet: wrote [type=20, len=1004, padding_size=4, comp=999, payload=999]
ssh_send_kex: SSH_MSG_KEXINIT sent
ssh_packet_socket_callback: packet: read type 20 [len=1068,padding=10,comp=1057,payload=1057]
ssh_packet_process: Dispatching handler for packet type 20
ssh_kex_select_methods: Negotiated curve25519-sha256,ecdsa-sha2-nistp256,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,zlib@openssh.com,zlib@openssh.com,,
packet_send2: packet: wrote [type=30, len=44, padding_size=6, comp=37, payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=260,padding=11,comp=248,payload=248]
ssh_packet_process: Dispatching handler for packet type 31
packet_send2: packet: wrote [type=21, len=12, padding_size=10, comp=1, payload=1]
crypt_set_algorithms2: Set output algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC output algorithm to aead-gcm
crypt_set_algorithms2: Set input algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC input algorithm to aead-gcm
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_packet_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 196 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
blink> 
```

**Comment by carloscabanero** [comment] 2021-09-29 00:59
@tobiasps On a new device, Blink will not be copying the keys as that is part of the protected area inside the device. Depends on how you migrated the device, some people have been lucky by copying the file .blink/keys. If that does not work, you will have to generate new keys.

**Comment by carloscabanero** [comment] 2021-09-29 01:00
@fortressofsolitude It seems like an issue with the key. Are you sure the key is stored there and that the public key is the same? Is it accessible? Can you copy the private key?

**Comment by fortressofsolitude** [comment] 2021-09-29 01:21
Thanks. Yes, on all counts. The key hadn't changed anyway across the upgrades, but in troubleshooting I did a complete uninstall of Blink, copied the private key as you say, and re-installed. So the key is there and is accessible and was working prior to upgrade. 

However I did just create a new key and that works!  So despite not touching the stored key in Blink at all, and restoring it as just stated in the last paragraph, it becomes somehow unusable. Creating a new key works and I'm off and running again, thank you. 

Many thanks,

David

**Comment by edjroz** [comment] 2021-09-29 02:21
I was able to modifying my hostname and resolve the issue by connecting using only my hostname, such that:

`mosh dev` || `ssh dev`

**Comment by tobiasps** [comment] 2021-09-29 08:09
> @tobiasps On a new device, Blink will not be copying the keys as that is part of the protected area inside the device. Depends on how you migrated the device, some people have been lucky by copying the file .blink/keys. If that does not work, you will have to generate new keys.

Thanks @carloscabanero it was it, I imported the key again and it works now. I think I was confused by the fact that I did not see any authentication error on the server or in blink.

**Comment by maiksd** [comment] 2021-09-30 09:21
I'm also having major problems since iOS 15. Can't connect anywhere any more really. Keys are not recognized/used. Here is the last part of the ssh -vvvv output, and the second to last line looks suspicious imho:

ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey,password
ssh_userauth_agent: Public key of  refused by server
Trying password...

**Comment by carloscabanero** [comment] 2021-09-30 11:55
Hey @maiksd, it is definitely a key issue. What version are you using, TestFlight or AppStore? Could check that the keys are actually there and that the private key can be copied as well? Did you switch devices?

**Comment by maiksd** [comment] 2021-09-30 12:29
Hi @carloscabanero, I didn't switch devices. Currently using TestFlight version, but checked AppStore version as well, same behaviour. And yes, I can copy the private keys.

I'm also seeing "connection refused" often, until I kill the app. That was there before the iOS 15 update as well, though.

**Comment by carloscabanero** [comment] 2021-09-30 12:49
@maiksd thanks for the help, if you don't mind please do not make any changes yet, so we can nail what may be going on. Please lets go back to the TestFlight version if you don't mind. Here is the thing, the keys are being used (the message "Public key of refused by server", means that the agent was trying to use a specific key, but the public key was rejected by it, so they did not even attempt to sign anything). Is it possible for you to send the lines above it (please hide sensitive info)?

What type of key and server is it?

Also, could you maybe try, if the host is configured within hosts, to send the command with the parameters replaced, like explicit user, IP, maybe the key as well. Maybe the issue is that some parameter for that host is not properly being passed for whatever reason.

**Comment by maiksd** [comment] 2021-09-30 13:33
I have an RSA key on blink. I do have a config for these hosts, and username and key is specified there. Have been for years, and nothing really changed.

Here's the full ssh -vvvv output. This goes against an Ubuntu 20.04 LTS machine, but I have similar behaviour with any other hosts, including older Linuxes or macOS workstations:
```
blink> ssh -vvvv <redacted>
Setting up connection callbacks.
Starting connection to <redacted>
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
ssh_connect: current state : 1
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
Starting connection to <redacted>
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.3
ssh_analyze_banner: We are talking to an OpenSSH client version: 8.2 (80200)
ssh_client_select_hostkeys: Order of wanted host keys: "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or directory
ssh_client_select_hostkeys: Algorithms found in known_hosts files: "ssh-ed25519"
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
ssh_list_kex: kex algos: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group18-sha512,diffie-hellman-group16-sha512,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1,ext-info-c
ssh_list_kex: server host key algo: ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss
ssh_list_kex: encryption client->server: aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
ssh_list_kex: encryption server->client: aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc
ssh_list_kex: mac algo client->server: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
ssh_list_kex: mac algo server->client: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
ssh_list_kex: compression algo client->server: zlib@openssh.com,zlib,none
ssh_list_kex: compression algo server->client: zlib@openssh.com,zlib,none
ssh_list_kex: languages client->server: 
ssh_list_kex: languages server->client: 
packet_send2: packet: wrote [type=20, len=1020, padding_size=10, comp=1009, payload=1009]
ssh_send_kex: SSH_MSG_KEXINIT sent
Starting connection to <redacted>
ssh_connect: current state : 4
ssh_packet_socket_callback: packet: read type 20 [len=1052,padding=10,comp=1041,payload=1041]
ssh_packet_process: Dispatching handler for packet type 20
ssh_list_kex: kex algos: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256
ssh_list_kex: server host key algo: rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2-nistp256,ssh-ed25519
ssh_list_kex: encryption client->server: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
ssh_list_kex: encryption server->client: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
ssh_list_kex: mac algo client->server: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
ssh_list_kex: mac algo server->client: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,uma
c-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1
ssh_list_kex: compression algo client->server: none,zlib@openssh.com
ssh_list_kex: compression algo server->client: none,zlib@openssh.com
ssh_list_kex: languages client->server: 
ssh_list_kex: languages server->client: 
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,zlib@openssh.com,zlib@openssh.com,,
packet_send2: packet: wrote [type=30, len=44, padding_size=6, comp=37, payload=37]
Starting connection to <redacted>
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
packet_send2: packet: wrote [type=21, len=12, padding_size=10, comp=1, payload=1]
ssh_packet_set_newkeys: called, direction = OUT 
crypt_set_algorithms2: Set output algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC output algorithm to aead-gcm
crypt_set_algorithms2: Set input algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC input algorithm to aead-gcm
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_packet_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 244 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_pki_signature_verify: Going to verify a ssh-ed25519 type signature
pki_verify_data_signature: Signature valid
ssh_packet_newkeys: Signature verified and valid
ssh_packet_set_newkeys: called, direction = IN 
ssh_packet_socket_callback: Processing 228 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 7 [len=208,padding=4,comp=203,payload=203]
ssh_packet_process: Dispatching handler for packet type 7
ssh_packet_ext_info: Received SSH_MSG_EXT_INFO
ssh_packet_ext_info: Follows 1 extensions
ssh_packet_ext_info: Extension: server-sig-algs=<ssh-ed25519,sk-ssh-ed25519@openssh.com,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ecdsa-sha2-nistp256@openssh.com>
Starting connection to <redacted>
ssh_connect: current state : 7
Connection succeeded...
Authenticating...
Trying none...
packet_send2: packet: wrote [type=5, len=32, padding_size=14, comp=17, payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_packet_socket_callback: packet: read type 6 [len=32,padding=14,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [type=50, len=48, padding_size=12, comp=35, payload=35]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=7,comp=24,payload=24]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
Trying publickey...
agent_talk: Request length: 1
ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
ssh_agent_get_ident_count: Agent count: 1
ssh_userauth_agent: Trying identity 
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
packet_send2: packet: wrote [type=50, len=608, padding_size=11, comp=596, payload=596]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=7,comp=24,payload=24]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey,password
ssh_userauth_agent: Public key of  refused by server
Trying password...
password:
```

**Comment by carloscabanero** [comment] 2021-09-30 13:42
Ok, so the key is being read by the agent, we are connecting to the proper server and all that. The agent is sending the public key to the server for acceptance, but the server is rejecting it, what means that it does not have it inside its list. I'm assuming the key is either the default, or that we are passing it as part of the host.

Could we try `ssh -i <key_name> <user>@<host>`, as to make sure the user is not being replaced by mistake or something like that? 

Another thing, does either `cssh <host>` or `ssh2 <host>` work?

**Comment by maiksd** [comment] 2021-09-30 13:59
Specifying the key yields the same result, as do cssh or ssh2 (while the latter asks to accept the host key again).

SSH logins from anywhere else, like a shell on my Mac, continue to work as normal including public key auth.

**Comment by carloscabanero** [comment] 2021-09-30 14:22
Well, it looks like maybe Blink has changed the key somehow. Is the Public Key the same as on authorized_keys? 

The other thing that may be going on (if there is a bug) is that there may be two keys named the same (somehow), and the interface is showing one but then using the other. To check if that is the case, we can try adding the ssh key manually to the agent with `ssh-add <keyname>`, you can then check the public key that was added with `ssh-add -l`. If it is the same as the one at the server, then we can try to connect again using `ssh <host>`.

I will check that the key on authorized_keys is properly stored. If it is the last one, there has to be a jump line and all that, no spaces at the end, etc...

**Comment by maiksd** [comment] 2021-09-30 14:43
Wow, you are right. The key is not the same as I have on all my hosts in `authorized_keys`. I added the "new" key to the hosts, and now it works again. I have no idea how this happened.

**Comment by carloscabanero** [comment] 2021-09-30 15:30
So iOS15 introduced a bug when loading the app that may have triggered your previous key to be rewritten. We have disabled automatic key creation completely, so this does not mess around anymore, but the AppStore version is now so behind that it may still triggered it. Your key may have been wiped when switching between them.

**Comment by maiksd** [comment] 2021-09-30 15:36
That's plausible, because I usually switch to and back from App Store version whenever I encounter some faulty behaviour to check if there's a difference between App Store and TestFlight versions. Ok thanks for the help!

**Comment by carloscabanero** [comment] 2021-09-30 16:08
Thanks a lot for the message exchange, needed to understand and get to the core of the problem.

I will leave the issue open in case anyone else have problems.

**Comment by michaelperel** [comment] 2021-09-30 23:47
+1 on issues since iPad OS 15.

I use key pairs generated by `config`, and when I upgraded to iOS 15, I could no longer connect to my VM. I decided to provision a new VM and connect, and while this worked for a few days, it mysteriously stopped working again. The key in blink now differs from that in `~/.ssh/authorized_keys`.

**Comment by carloscabanero** [comment] 2021-09-30 23:48
Is that the AppStore version or TestFlight?

**Comment by michaelperel** [comment] 2021-09-30 23:49
The app store version

**Comment by carloscabanero** [comment] 2021-09-30 23:55
Thanks a lot for your report. Fix should be coming soon.

As a workaround, with a default key, like id_ecdsa, this should not be an issue.

**Comment by maiksd** [comment] 2021-10-04 15:30
TestFlight update 13.90.3 (340) wiped my ssh keys. The one I newly created in the previous release (see above) is gone.

**Comment by carloscabanero** [comment] 2021-10-06 20:44
Just a heads up, this should now have been fixed for everyone.

**Comment by michaelperel** [comment] 2021-10-09 01:34
For those without test flight access, when would the update reach the app store? Thank you so much for the fix!

**Comment by tonilampela** [comment] 2021-10-10 16:46
Also experiencing bunch of issues connecting to my servers either via SSH or mosh since updating to iPadOS 15. If these issues have been resolved, I really hope the update gets to AppStore soon.

**Comment by gin66** [comment] 2021-11-09 22:35
+1 for app store version

My error is related to the ssh-agent, as can seen below. Fallback is the uncomfortable password entry. For my internet connected machine, I have disabled password authentication in general. So I need first to login to my home server via vpn and from there to my internet host. Works, but….

```
Starting connection to nuc1
ssh_connect: current state : 7
Connection succeeded...
Authenticating...
Trying none...
packet_send2: packet: wrote [type=5, len=32, padding_size=14, comp=17, payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
ssh_packet_socket_callback: packet: read type 6 [len=32,padding=14,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [type=50, len=48, padding_size=10, comp=37, payload=37]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=7,comp=24,payload=24]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey,password
Trying publickey...
agent_talk: Request length: 1
ssh_agent_get_ident_count: Answer type: 12, expected answer: 12
ssh_agent_get_ident_count: Agent count: 0
Trying password...
password:
```

**Comment by carloscabanero** [comment] 2021-12-08 23:51
Closing here as we already launched in the AppStore. Please reopen if you are still experiencing specific issues.

**Closed as completed by carloscabanero** 2021-12-08 23:51 UTC
Labels: support, iOS 15 bug
