### ISSUE TITLE
iPadOS 14.2 often gets stuck

### ISSUE THREAD

**Issue by Simon-live** [blinksh/blink#1172] opened 2020-12-07 06:22 UTC
iPados14.2的系统（12.9寸 第四代），安装了blink shell之后经常会出现卡住的情况（会发生在切屏或者刚启动的时候），且无法自己恢复，清除后台也无效，关机重启也无效，只有卸载重新安装。希望解决一下问题，这是一个非常好用的软件，我希望可以继续使用它，而不是在App Store中进行退款。

**Comment by nanzhong** [comment] 2020-12-08 12:18
English translation:

> On iPadOS 14.2 (iPad 12.9 inch, 4th gen) blink shell often gets stuck (happens when switching apps or fresh start), and it is not able to recover itself. Force closing the app and restarting the device also have no effect. The only thing that works is uninstalling the app and re-installing. Hoping to find a solution to this problem, this is a great app, and I would like to continue using it instead of refunding the app store purchase.

**Comment by nanzhong** [comment] 2020-12-08 12:22
@SUPXT I'm unable to type in chinese on my current device, but could you explain what you mean by getting stuck? I've seen something like this happen with a custom theme configured that can't be loaded because of network issues. I end up seeing just a black screen with nothing rendered. However, I've not had consistent network issues for this to happen often.

Are you using any custom themes? Are you based in China? I have not looked to see if blink does anything over the network that could be affected by something like China's great firewall that could cause this.

**Comment by javierdemartin** [comment] 2020-12-08 12:27
Thank you for chiming in @nanzhong. First off, Blink does nothing in the background or network related neither it does collect any personal data. 

We're sorry you're having issues @SUPXT, if you could provide any more info on your configuration (themes, Blink version and so on) that could help us pinpoint where the issue might be it'd be of great help. Does Blink get stuck with open sessions or just the whole Blink app?

**Comment by SUPXT** [comment] 2020-12-08 12:55
For example, when I open blinkshell and enter config to add a new server, my page of host will be stuck. I suspect that it may be a problem with Chinese input method, because the default is Chinese input method before input, but this doubt has not been verified. In addition, when I put blinkshell in the background and closed the iPad for a while, my mush display is trying to connect and will display the number of seconds. At this time, the number of seconds will suddenly jam and no longer increase, and the whole blink shell will be frozen. Another case is that the resolution adjustment of blinkshell will jam. In these cases, the freeze cannot recover by itself, including restarting the iPad.

**Comment by carloscabanero** [comment] 2020-12-08 13:35
@javierdemartin I think @nanzhong was referring to maybe downloading some of the themes or fonts over the network, that may cause loading times to go awry if we had a bug there, and the great firewall could trigger that.

Thanks for the thorough report @SUPXT, I think we have never heard anything like that. Would you mind to record a simple video to see if we can figure out how to trigger something like this? It is really weird that a freeze cannot be recovered even after closing the app or restarting the iPad. Could you try to see if other gestures like 3 finger tap work?

Thanks!

**Comment by iarchean** [comment] 2020-12-10 02:22
I have the same issue, sometimes it happens when I switch between Blink and another apps, then cursor stops blink, cant input any letter and cant switch between tabs. Like I pressed command+O, I have to force quit Blink and reopen it to fix.

My device is the same model as @SUPXT’s, running iPadOS 14.2 and Blink v13.5.9.247.

**Comment by d6rkaiz** [comment] 2020-12-17 23:02
I have same problem here at japanese input method.
I feel that it often occurs when it is not in English when switching.

my devise is the iPad Pro 12.9 3gen. It continues to occur on iPadOS 14.3.

**Comment by wangfenjin** [comment] 2020-12-18 01:58
Same issue. Do you guys use your product everyday? I think it’s easy to reproduce if you also use your product in iPadPro

**Comment by Zhanweelee** [comment] 2020-12-28 14:32
> For example, when I open blinkshell and enter config to add a new server, my page of host will be stuck. I suspect that it may be a problem with Chinese input method, because the default is Chinese input method before input, but this doubt has not been verified. In addition, when I put blinkshell in the background and closed the iPad for a while, my mush display is trying to connect and will display the number of seconds. At this time, the number of seconds will suddenly jam and no longer increase, and the whole blink shell will be frozen. Another case is that the resolution adjustment of blinkshell will jam. In these cases, the freeze cannot recover by itself, including restarting the iPad.

This problem often happens on my device as well.
iPad Pro 10 inch, iOS 14.2, with Blink newest version 13.5.9

**Comment by opeltantra** [comment] 2021-01-24 09:55
I'm suffering from the same problem with Korean/english keyboard in iPadOS 14.2. Blink crashes quite often when i switch between apps or languages. This is super annoying.

**Comment by epheien** [comment] 2021-03-17 17:17
same issue on `ssh myhost`

**Comment by yury** [comment] 2023-03-23 11:48
Closing as fixed. Feel free to reopen if needed.

**Closed by yury** 2023-03-23 11:48 UTC
Labels: bug, support, critical
