### ISSUE TITLE
Import key failures

### ISSUE THREAD

**Issue by tyrylu** [blinksh/blink#1106] opened 2020-08-25 14:19 UTC
Hello.
In the latest testflight beta i am unable to import either a RSA 4096 or ED25519 private key. They work fine when passed as identity files for ssh, but when imported from a file i get just the not much informative could not validate as a private key error. They are unprotected PEM keys.

**Comment by javierdemartin** [comment] 2020-09-25 15:46
Does this only happen when importing from a file from iCloud? If that's the case the problem is due to the sandbox requirements on iOS, see [`startAccessingSecurityScopedResource()`](https://developer.apple.com/documentation/foundation/nsurl/1417051-startaccessingsecurityscopedreso#). 

This has been fixed in Blink14 and we're working on releasing as soon as we can. Sorry for the inconvenience. In the meantime you could import them from the clipboard.

**Comment by tyrylu** [comment] 2020-09-25 17:28
Yeah, importing from clipboard works.

**Comment by javierdemartin** [comment] 2020-09-25 18:19
Great, that's gotta be the issue. I'll get back to this issue when the new version is released!

**Comment by javierdemartin** [comment] 2020-12-10 11:49
Apologies for the delay. This has meen merged to the codebase and will be available on next release.

**Closed by javierdemartin** 2020-12-10 11:49 UTC
Labels: bug
