### ISSUE TITLE
mosh reports "Did not find remote IP address", ssh exits silently

### ISSUE THREAD

**Issue by fingolfin** [blinksh/blink#998] opened 2020-04-24 13:51 UTC
I haven't used Blink on my iPhone 7 for quite some time, but just updated to v13.4.231 (excited to test the scrolling feature in vim & tmux!!!). Note that everything used to work fine here, but I really didn't touch it for quite some time.

Also note that I am syncing my config via iCloud to my iPad, <s>where everything still works, even right now!</s> [UPDATE: actually, I was wrong, it is broken on the iPad as well]

But on the iPhone, I can't connect: `ssh` exits silently, and mosh give an error:
```
blink> ssh CONFIGNAME  # I used tab-completion to enter the configname!
blink> mosh CONFIGNAME
Did not find remote IP address
blink> ping CONFIGNAME
ping: cannot resolve CONFIGNAME: Unknown host
blink> ping FULLNAME
 ... successfully pings the server
blink> mosh FULLNAME
Did not find remote IP address
```
Searching the issues I found https://github.com/blinksh/blink/issues/628 which suggested to try `mosh -2` resp. use `ssh2`: Doing that indeed helped a bit:
```
blink> ssh2 CONFIGNAME
Connected to 12.34.56.78
user@FULLNAME's password: 
```
So at least it managed to resolve CONFIGNAME and the server and get a connection! It then failed to complete the pubkey authentication (I've setup an RSA key). I verified that the pubkey is setup on the server... but anyhow, this is a secondary problem.

My primary concern is: why do ssh / mosh not understand CONFIGNAME anymore, why do I need to switch to ssh2?!

**Comment by fingolfin** [comment] 2020-04-24 14:49
OK, I tried to do get a log now, and this is what I am seeing... perhaps it contains a hint as to what might be wrong?

I thought that perhaps the server config changed; but my key is an RSA key, and the server seems to list ssh-rsa in the list of allowed key types? 

What confuse me most is that `ssh` doesn't even print an error, it just silently gives up. Huh?

```
blink> ssh -vvvvvvvv FULL-QUALIFIED-NAME
ssh_connect: libssh 0.9.3 (c) 2003-2019 Aris Adamantiadis, Andreas Schneider and libssh contributors. Distributed
 under the LGPL, please refer to COPYING file for information about your rights, using threading threads_pthread
ssh_connect: Socket connecting, now waiting for the callbacks to work
-[IO stream:handleEvent:]: Received POLLOUT in connecting state
socket_callback_connected: Socket connection callback: 1 (0)
ssh_connect: current state : 2
callback_receive_banner: Received banner: SSH-2.0-OpenSSH_8.1
ssh_client_connection_callback: SSH server banner: SSH-2.0-OpenSSH_8.1
ssh_analyze_banner: Analyzing banner: SSH-2.0-OpenSSH_8.1
ssh_analyze_banner: We are talking to an OpenSSH client version: 8.1 (80100)
ssh_client_select_hostkeys: Order of wanted host keys: "ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa
-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss"
ssh_key_cmp: key types don't match!
ssh_known_hosts_read_entries: Failed to open the known_hosts file '/etc/ssh/ssh_known_hosts': No such file or dir
ectory
ssh_client_select_hostkeys: Algorithms found in known_hosts files: "ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa
"
ssh_client_select_hostkeys: Changing host key method to "ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ecdsa-sha2
-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,ssh-dss"
packet_send2: packet: wrote [type=20, len=980, padding_size=10, comp=969, payload=969]
ssh_send_kex: SSH_MSG_KEXINIT sent
ssh_packet_socket_callback: packet: read type 20 [len=1076,padding=6,comp=1069,payload=1069]
ssh_packet_process: Dispatching handler for packet type 20
ssh_kex_select_methods: Negotiated curve25519-sha256,ssh-ed25519,aes256-gcm@openssh.com,aes256-gcm@openssh.com,hm
ac-sha2-256-etm@openssh.com,hmac-sha2-256-etm@openssh.com,zlib@openssh.com,zlib@openssh.com,,
packet_send2: packet: wrote [type=30, len=44, padding_size=6, comp=37, payload=37]
ssh_connect: current state : 6
ssh_packet_socket_callback: packet: read type 31 [len=188,padding=8,comp=179,payload=179]
ssh_packet_process: Dispatching handler for packet type 31
packet_send2: packet: wrote [type=21, len=12, padding_size=10, comp=1, payload=1]
crypt_set_algorithms2: Set output algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC output algorithm to aead-gcm
crypt_set_algorithms2: Set input algorithm to aes256-gcm@openssh.com
crypt_set_algorithms2: Set HMAC input algorithm to aead-gcm
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_init_rekey_state: Set rekey after 4294967296 blocks
ssh_packet_client_curve25519_reply: SSH_MSG_NEWKEYS sent
ssh_packet_socket_callback: Processing 196 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 21 [len=12,padding=10,comp=1,payload=1]
ssh_packet_process: Dispatching handler for packet type 21
ssh_packet_newkeys: Received SSH_MSG_NEWKEYS
ssh_packet_newkeys: Signature verified and valid
ssh_packet_socket_callback: Processing 180 bytes left in socket buffer
ssh_packet_socket_callback: packet: read type 7 [len=160,padding=18,comp=141,payload=141]
ssh_packet_process: Dispatching handler for packet type 7
ssh_packet_ext_info: Received SSH_MSG_EXT_INFO
ssh_packet_ext_info: Follows 1 extensions
ssh_packet_ext_info: Extension: server-sig-algs=<ssh-ed25519,ssh-rsa,rsa-sha2-256,rsa-sha2-512,ssh-dss,ecdsa-sha2
-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521>
ssh_connect: current state : 7
ssh_key_cmp: key types don't match!
packet_send2: packet: wrote [type=5, len=32, padding_size=14, comp=17, payload=17]
ssh_service_request: Sent SSH_MSG_SERVICE_REQUEST (service ssh-userauth)
blink: setting socket keepalive: 1
ssh_packet_socket_callback: packet: read type 6 [len=32,padding=14,comp=17,payload=17]
ssh_packet_process: Dispatching handler for packet type 6
ssh_packet_service_accept: Received SSH_MSG_SERVICE_ACCEPT
packet_send2: packet: wrote [type=50, len=48, padding_size=12, comp=35, payload=35]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=16,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'none'. Authentication that can continue: publickey
blink: using auth methods attempt: 1 of 5
blink: import key id_rsa
ssh_pki_import_privkey_base64: Trying to decode privkey passphrase=false
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-
cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-5
12-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.c
om,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-
dss>
ssh_key_algorithm_allowed: Checking rsa-sha2-512 with list <ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-
cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-5
12-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.c
om,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-
dss>
packet_send2: packet: wrote [type=50, len=608, padding_size=11, comp=596, payload=596]
ssh_packet_socket_callback: packet: read type 51 [len=32,padding=16,comp=15,payload=15]
ssh_packet_process: Dispatching handler for packet type 51
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
ssh_packet_userauth_failure: Access denied for 'publickey'. Authentication that can continue: publickey
blink: warning: no key found: 'id_dsa' 
blink: warning: no key found: 'id_ecdsa' 
blink: warning: no key found: 'id_ed25519' 
blink>
```

**Comment by rubyroobs** [comment] 2020-04-25 07:12
I have almost the same issue (mosh gives "Did not find remote IP address", SSH fails silently) but it seems to find the key and gives me "Access denied for 'none'". Would love to know if there's a solution for this.

**Comment by fingolfin** [comment] 2020-04-25 10:47
So, here is the thing: I just discovered that my "RSA" key apparently is an "DSA" key. It was created by Blink.sh. I can repeat this: if I ask Blink.sh to generate an RSA key (I choose 4096 bits), then it always ends up producing a DSA key instead.

That doesn't explain or justify the weird non-error message by `ssh` and the wrong failure message by `mosh`. So there seem to be several issues going on at once here?

**Comment by perelin** [comment] 2020-04-25 15:01
I just just encountered the same behavior after restoring an icloud backup to a new ipad. The config is still working without issues on the old ipad. Turn out my private keys where not part of the icloud backup :) After importing my keys on the new ipad and setting them on the hosts everything worked again. Still ssh/mosh failing like this is kind of confusing.

**Comment by aofei** [comment] 2020-04-27 07:34
Confirmed. The `Did not find remote IP address` appears too often.

Sometimes it makes my Mosh session unrecoverable. Then I have to restart the app several times to reconnect, because not every time it can reconnect successfully.

**Comment by sheriferson** [comment] 2021-05-23 02:41
I’m running into this too, same series of events as @perelin. Except on the new iPad restored from iCloud backup, I see the keys listed in Blink configuration. When I try to copy a private key, Blink crashes. ssh and mosh sessions no longer connect as they did before.
I’ll try to restore those keys from the old iPad and see if that fixes it.

**Comment by pimoore** [comment] 2021-09-16 20:05
Is there any progress on this issue, as I’m still experiencing the exact same problem:
- ssh fails silently
- Mosh throws “did not find remote IP address” error

I can successfully connect using Secure ShellFish to the same remote machine using the same SSH key.

**Comment by carloscabanero** [comment] 2021-09-16 20:13
There are a bunch of issues reported here, which all of them were fixed one way or another, and are available on TF We will be releasing to the public soon. In the meantime:

- When Mosh throws a "did not find remote IP address" error, this is most of the time due to either not having access over ssh, or not being able to execute mosh-server command.
- We suggest enabling verbose mode when connecting over ssh to debug if the issue is there. If ssh works, then see what mosh reports.
- Usually, ssh failing silently in previous versions was due to authentication issues. Most of reports here are "restoring from a backup", and reporting that key material is lost. Private keys are never backed up as they are always stored at the keychain. Restoring them will restore the key public information, but not the private.

@pimoore If you are still having issues with SSH, feel free to open a separate issue or contact us over Discord - email.

**Closed by carloscabanero** 2021-09-16 20:13 UTC
